// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/systimer.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `systimer` block (36 registers, 1 with a non-zero reset).
pub static SYSTIMER: RegNames = RegNames {
    block: "systimer",
    entries: &[
        (0x000, "conf"),
        (0x004, "unit0_op"),
        (0x008, "unit1_op"),
        (0x00c, "unit0load.hi"),
        (0x010, "unit0load.lo"),
        (0x014, "unit1load.hi"),
        (0x018, "unit1load.lo"),
        (0x01c, "trgt0.hi"),
        (0x020, "trgt0.lo"),
        (0x024, "trgt1.hi"),
        (0x028, "trgt1.lo"),
        (0x02c, "trgt2.hi"),
        (0x030, "trgt2.lo"),
        (0x034, "target0_conf"),
        (0x038, "target1_conf"),
        (0x03c, "target2_conf"),
        (0x040, "unit0_value.hi"),
        (0x044, "unit0_value.lo"),
        (0x048, "unit1_value.hi"),
        (0x04c, "unit1_value.lo"),
        (0x050, "comp0_load"),
        (0x054, "comp1_load"),
        (0x058, "comp2_load"),
        (0x05c, "unit0_load"),
        (0x060, "unit1_load"),
        (0x064, "int_ena"),
        (0x068, "int_raw"),
        (0x06c, "int_clr"),
        (0x070, "int_st"),
        (0x074, "real_target0.lo"),
        (0x078, "real_target0.hi"),
        (0x07c, "real_target1.lo"),
        (0x080, "real_target1.hi"),
        (0x084, "real_target2.lo"),
        (0x088, "real_target2.hi"),
        (0x0fc, "date"),
    ],
    resets: &[(0x000, 0x46000000)],
};
