// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/uart0.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `uart0` block (38 registers).
pub static UART0: RegNames = RegNames {
    block: "uart0",
    entries: &[
        (0x000, "fifo"),
        (0x004, "int_raw"),
        (0x008, "int_st"),
        (0x00c, "int_ena"),
        (0x010, "int_clr"),
        (0x014, "clkdiv"),
        (0x018, "rx_filt"),
        (0x01c, "status"),
        (0x020, "conf0"),
        (0x024, "conf1"),
        (0x02c, "hwfc_conf"),
        (0x030, "sleep_conf0"),
        (0x034, "sleep_conf1"),
        (0x038, "sleep_conf2"),
        (0x03c, "swfc_conf0"),
        (0x040, "swfc_conf1"),
        (0x044, "txbrk_conf"),
        (0x048, "idle_conf"),
        (0x04c, "rs485_conf"),
        (0x050, "at_cmd_precnt"),
        (0x054, "at_cmd_postcnt"),
        (0x058, "at_cmd_gaptout"),
        (0x05c, "at_cmd_char"),
        (0x060, "mem_conf"),
        (0x064, "tout_conf"),
        (0x068, "mem_tx_status"),
        (0x06c, "mem_rx_status"),
        (0x070, "fsm_status"),
        (0x074, "pospulse"),
        (0x078, "negpulse"),
        (0x07c, "lowpulse"),
        (0x080, "highpulse"),
        (0x084, "rxd_cnt"),
        (0x088, "clk_conf"),
        (0x08c, "date"),
        (0x090, "afifo_status"),
        (0x098, "reg_update"),
        (0x09c, "id"),
    ],
};
