//! LightPlayer engine↔client wire model (`Wire*` types where needed).

#![no_std]

extern crate alloc;

#[cfg(feature = "std")]
extern crate std;

pub mod budget;
pub mod json;
pub mod message;
pub mod messages;
#[cfg(feature = "ser-write-json")]
pub mod pack_sink;
#[cfg(feature = "ser-write-json")]
pub mod packed_frame;
pub mod packed_json_decode;
pub mod project;
pub mod project_command;
pub mod project_inventory;
pub mod project_overlay;
#[cfg(feature = "ser-write-json")]
pub mod ser_write;
pub mod serde_base64;
pub mod server;
pub mod slot;
#[cfg(test)]
mod test_traffic;
pub mod transport_error;
pub mod tree;
// Generated by `just wire-dict`; rustfmt would reflow the tables.
#[rustfmt::skip]
pub mod wire_dictionary;
#[cfg(feature = "wire-dict-gen")]
pub mod wire_dictionary_gen;
pub mod wire_encoding;

pub use messages::{
    BindingGraphProbeRequest, BindingGraphProbeResult, ControlProductGeometry,
    ControlProductProbeRequest, ControlProductProbeResult, ControlProductProbeResultHeader,
    GeometryDisplayLayout, KnownOutputFrameGeometry, NodeReadQuery, NodeReadSelection,
    OutputFrameEntry, OutputFrameEntryHeader, OutputFrameGeometry, OutputFrameGeometryRead,
    OutputFrameProbeRequest, OutputFrameProbeResult, OutputFrameProbeResultHeader,
    PROJECT_READ_FRAME_MAX_BYTES, PROJECT_READ_FRAME_SERIAL_BUFFER_BYTES,
    PROJECT_READ_FRAME_SERIAL_MARGIN_BYTES, PROJECT_READ_PROBE_HEADER_RESERVE_BYTES,
    PROJECT_READ_RUNTIME_CHUNK_BYTES, ProjectProbeRequest, ProjectProbeResult,
    ProjectProbeResultHeader, ProjectReadEvent, ProjectReadNodeEvent, ProjectReadProbeEvent,
    ProjectReadQuery, ProjectReadQueryEvent, ProjectReadRequest, ProjectReadResourceEvent,
    ProjectReadShapeEvent, ProjectRuntimeStatus, ReadLevel, RenderProductProbeRequest,
    RenderProductProbeResult, RenderProductProbeResultHeader, ResourcePayloadRead,
    ResourceReadQuery, ResourceReadResult, RevisionGateRead, RevisionGateResult, RuntimeReadQuery,
    RuntimeReadResult, ServerRuntimeStatus, ShapeReadQuery, TimebaseProbeRequest,
    TimebaseProbeResult, WireBindingDirection, WireBindingEndpoint, WireBindingGraph,
    WireBindingGraphRead, WireBindingOrigin, WireBusChannel, WireBusChannelValue,
    WireBusChannelValues, WireCellProjection, WireConsumerPolicy, WireEffectiveBinding,
    WireOutputPlacement, WirePhasorOrigin, WirePhasorReading, WirePhasorRow, WireProjectionOrigin,
    WireProjectionShape, WireScopeRef, WireVisualSpace,
};
pub use messages::{ClientMessage, ClientRequest, Message, ServerMessage};
#[cfg(feature = "ser-write-json")]
pub use pack_sink::PackSink;
#[cfg(feature = "ser-write-json")]
pub use packed_frame::ser_packed_frame_to;
pub use packed_json_decode::{PackedDecodeError, decode_packed_to_json};
pub use project::{
    NodeRuntimeStatus, WireChannelSampleFormat, WireColorLayout, WireProjectHandle,
    WireResourceAvailability, WireResourceKindSummary, WireResourceMetadataSummary,
    WireResourceSummary, WireRuntimeBufferKind, WireRuntimeBufferMetadataPayload,
    WireRuntimeBufferPayload, WireTextureFormat,
};
pub use project_command::{
    WireCreateNodeRequest, WireCreateNodeResponse, WireNodeCommand, WireNodeCommandResponse,
    WirePanelAutoSaveRequest, WirePanelClearRequest, WirePanelCommandResponse,
    WirePanelWriteRequest, WireProjectCommand, WireProjectCommandResponse, WireRemoveNodeRequest,
    WireRemoveNodeResponse,
};
pub use project_inventory::{
    WireProjectInventoryReadRequest, WireProjectInventoryReadResponse,
    WireProjectNodeInventoryEntry, WireProjectNodeOrigin,
};
pub use project_overlay::{
    WireOverlayCommitRequest, WireOverlayCommitResponse, WireOverlayMutationRequest,
    WireOverlayMutationResponse, WireOverlayReadRequest, WireOverlayReadResponse,
};
#[cfg(feature = "ser-write-json")]
pub use ser_write::{
    CountingSerWrite, ErasedWriteError, WireWriteError, ser_wire_to, ser_write_json_fnv64,
    ser_write_json_len, ser_write_json_to,
};
pub use server::{
    AvailableProject, BuildFacts, FAULT_MESSAGE_CAP_BYTES, FAULT_NODES_CAP, FaultedNodeWire,
    FsRequest, FsResponse, HardwareFacts, HardwareIdentity, HeartbeatIdentity, HelloIdentity,
    LinkCounters, LoadedProject, MemoryStats, ProjectFaultWire, SampleStats, ServerConfig,
    ServerHello, ServerMsgBody, WIRE_PROTO_VERSION,
};
pub use slot::{
    WireSlotChange, WireSlotData, WireSlotFullSync, WireSlotPatch, WireSlotRootSnapshot,
    WireSlotRootsSnapshot, build_slot_full_sync, build_slot_roots_snapshot, collect_slot_diff,
    snapshot_slot_root, snapshot_slot_shape, wire_slot_data_from_slot_access,
};
pub use transport_error::TransportError;
pub use tree::{WireChildKind, WireEntryState, WireSlotIndex, WireTreeDelta};
pub use wire_dictionary::{WIRE_DICTIONARY, WIRE_DICTIONARY_FINGERPRINT, WIRE_DICTIONARY_PROTO};
pub use wire_encoding::WireEncoding;

/// Canonical project-read message envelope.
pub type WireMessage = Message;
/// Canonical project-read server message.
pub type WireServerMessage = ServerMessage;
/// Canonical project-read server message body.
pub type WireServerMsgBody = ServerMsgBody;
