//! The wire's JSON Pack dictionary: what a packed frame is coded against.
//!
//! GENERATED by `just wire-dict`
//! (`cargo run -p lpc-wire --features wire-dict-gen --bin wire-dict`). Do not
//! edit: `just wire-dict-check` (in `check-lint`) fails when this file is not
//! what the generator writes, and when the dictionary changed without a
//! `WIRE_PROTO_VERSION` bump.
//!
//! - Keys: every struct field name and every data-carrying enum variant name
//!   reachable from `WireServerMessage` and `ClientMessage`, found by tracing
//!   their `Deserialize` impls (`wire_dictionary_gen`).
//! - Values: every unit variant name.
//! - Both: the keys and string tags of the slot text codec
//!   (`lpc-model`'s `slot_sync_codec` / `slot_codec` writers), which writes
//!   `WireSlotData`'s pre-serialized JSON.
//! - Order: by frequency in the committed traffic sample
//!   (`lp-base/lp-json-pack/tests/fixtures/choker-lens-sample.txt`),
//!   then by name. The commonest get the one-byte codes.
//!
//! 419 keys (205 ranked by the sample), 186 values (38 ranked); 9188 bytes
//! of statics.

use lp_json_pack::{Dictionary, PackStrings};

/// The `WIRE_PROTO_VERSION` this dictionary was generated at.
pub const WIRE_DICTIONARY_PROTO: u32 = 21;

/// [`WIRE_DICTIONARY`]'s `fingerprint()`, as generated.
pub const WIRE_DICTIONARY_FINGERPRINT: u32 = 0x02624794;

/// The wire's dictionary.
pub static WIRE_DICTIONARY: Dictionary = Dictionary {
    keys: KEYS,
    values: VALUES,
    key_hash: KEY_HASH,
    value_hash: VALUE_HASH,
};

const KEYS: PackStrings = PackStrings {
    text: concat!(
        "revision", // 0
        "id", // 1
        "event", // 2
        "index", // 3
        "node", // 4
        "msg", // 5
        "query", // 6
        "value", // 7
        "geometry", // 8
        "nodes", // 9
        "kind", // 10
        "projectRead", // 11
        "begin", // 12
        "output_frame", // 13
        "output", // 14
        "probe", // 15
        "result", // 16
        "state", // 17
        "unchanged", // 18
        "level", // 19
        "change_frame", // 20
        "status", // 21
        "outputs", // 22
        "entry_changed", // 23
        "sample_format", // 24
        "product", // 25
        "bytes", // 26
        "end", // 27
        "events", // 28
        "channels", // 29
        "frame", // 30
        "changed_at", // 31
        "if_changed", // 32
        "handle", // 33
        "shapes", // 34
        "rows", // 35
        "samples_per_row", // 36
        "request", // 37
        "since", // 38
        "freeBytes", // 39
        "largestFreeBlock", // 40
        "memory", // 41
        "totalBytes", // 42
        "usedBytes", // 43
        "probes", // 44
        "samples", // 45
        "known", // 46
        "values", // 47
        "preferred_extent", // 48
        "runtime", // 49
        "binding_graph", // 50
        "structure", // 51
        "name", // 52
        "path", // 53
        "baseMac", // 54
        "data", // 55
        "avg", // 56
        "bootCount", // 57
        "deltas", // 58
        "demand_root_count", // 59
        "fps", // 60
        "frame_count", // 61
        "frame_delta_ms", // 62
        "frame_num", // 63
        "frame_total_ms", // 64
        "heartbeat", // 65
        "hostDrainingAgainMs", // 66
        "hostNotDrainingMs", // 67
        "identity", // 68
        "lastCrash", // 69
        "last_frame_time_us", // 70
        "link", // 71
        "loaded_projects", // 72
        "max", // 73
        "min", // 74
        "notDrainingCount", // 75
        "outputClamp", // 76
        "overlay_changed_at", // 77
        "panel_auto_save", // 78
        "parseFailures", // 79
        "paths", // 80
        "project", // 81
        "queueFullDrops", // 82
        "recovery", // 83
        "resetReason", // 84
        "runtime_buffer_count", // 85
        "rxErrors", // 86
        "safeMode", // 87
        "sdev", // 88
        "server", // 89
        "stalePartialFlushes", // 90
        "theoretical_fps", // 91
        "tree_deltas", // 92
        "uptime_ms", // 93
        "control", // 94
        "fields", // 95
        "fields_revision", // 96
        "graph", // 97
        "ids_revision", // 98
        "shape", // 99
        "slot_root", // 100
        "structure_revision", // 101
        "time", // 102
        "visual", // 103
        "known_revision", // 104
        "filesystem", // 105
        "control_product", // 106
        "include_slots", // 107
        "queries", // 108
        "include_values", // 109
        "error", // 110
        "artifact", // 111
        "color_order", // 112
        "count", // 113
        "encoding", // 114
        "len", // 115
        "rgb_pixels", // 116
        "row", // 117
        "start", // 118
        "extent", // 119
        "preview", // 120
        "parent", // 121
        "location", // 122
        "segments", // 123
        "ty", // 124
        "slot", // 125
        "origin", // 126
        "write", // 127
        "child_kind", // 128
        "children", // 129
        "children_ver", // 130
        "created", // 131
        "created_frame", // 132
        "def_location", // 133
        "key", // 134
        "loaded", // 135
        "prefix", // 136
        "runtime_id", // 137
        "deleteDir", // 138
        "input", // 139
        "invocation", // 140
        "offset", // 141
        "project_child", // 142
        "role", // 143
        "source", // 144
        "writeChunk", // 145
        "boardId", // 146
        "build", // 147
        "button", // 148
        "chipRevision", // 149
        "commit", // 150
        "deviceUid", // 151
        "dirty", // 152
        "eui64", // 153
        "features", // 154
        "hardware", // 155
        "hello", // 156
        "listLoadedProjects", // 157
        "package", // 158
        "profile", // 159
        "projects", // 160
        "proto", // 161
        "radio", // 162
        "totalLedBudget", // 163
        "written", // 164
        "available", // 165
        "content_type", // 166
        "hash", // 167
        "hashPackage", // 168
        "loadProject", // 169
        "packageHash", // 170
        "projectCommand", // 171
        "read_inventory", // 172
        "response", // 173
        "assets", // 174
        "by_ids", // 175
        "c", // 176
        "changed", // 177
        "changes", // 178
        "changesSince", // 179
        "command", // 180
        "cursor", // 181
        "defs", // 182
        "display_layout", // 183
        "entries", // 184
        "h", // 185
        "ids", // 186
        "lamps", // 187
        "layout", // 188
        "layout2d", // 189
        "membership", // 190
        "next", // 191
        "p", // 192
        "placements", // 193
        "rev", // 194
        "reversed", // 195
        "s", // 196
        "sample_layout", // 197
        "seq", // 198
        "source_lamp", // 199
        "source_lamps", // 200
        "spans", // 201
        "version", // 202
        "w", // 203
        "wire_lamp", // 204
        "Error", // 205
        "Fault", // 206
        "Field", // 207
        "Index", // 208
        "InitError", // 209
        "Unsupported", // 210
        "Warn", // 211
        "accepted", // 212
        "added", // 213
        "array", // 214
        "artifact_changes", // 215
        "artifacts", // 216
        "assign_value", // 217
        "attach", // 218
        "availability", // 219
        "b_vec2", // 220
        "b_vec3", // 221
        "b_vec4", // 222
        "base_display", // 223
        "base_values", // 224
        "batch", // 225
        "bindings", // 226
        "body", // 227
        "bool", // 228
        "bootsAgo", // 229
        "buffer", // 230
        "bus", // 231
        "by_refs", // 232
        "byte_length", // 233
        "byte_length_hint", // 234
        "cause", // 235
        "channel", // 236
        "children_changed", // 237
        "clearFaults", // 238
        "clear_artifact", // 239
        "codec", // 240
        "commands", // 241
        "commit_overlay", // 242
        "consumers", // 243
        "crashCount", // 244
        "create_node", // 245
        "custom", // 246
        "cycle", // 247
        "default_1d_to_2d", // 248
        "default_bind", // 249
        "deleteFile", // 250
        "delta_seconds", // 251
        "description", // 252
        "direction", // 253
        "domain", // 254
        "dropdown", // 255
        "edit", // 256
        "editor", // 257
        "edits", // 258
        "effect", // 259
        "elem", // 260
        "enabled", // 261
        "endpoint", // 262
        "engaged", // 263
        "entry", // 264
        "enum", // 265
        "f32", // 266
        "failed", // 267
        "fault", // 268
        "field", // 269
        "file", // 270
        "fin", // 271
        "fixture_colors", // 272
        "flip", // 273
        "force", // 274
        "format", // 275
        "from", // 276
        "gpio", // 277
        "gpu_resident", // 278
        "header", // 279
        "height", // 280
        "i32", // 281
        "i_vec2", // 282
        "i_vec3", // 283
        "i_vec4", // 284
        "inline", // 285
        "keys_revision", // 286
        "knob", // 287
        "label", // 288
        "ledger_cleared", // 289
        "list", // 290
        "listAvailableProjects", // 291
        "listDir", // 292
        "literal", // 293
        "log", // 294
        "map", // 295
        "mat2x2", // 296
        "mat3x3", // 297
        "mat4x4", // 298
        "materialized", // 299
        "merge", // 300
        "message", // 301
        "meta", // 302
        "metadata", // 303
        "mirror", // 304
        "move_slot_entry", // 305
        "mutate_overlay", // 306
        "mutation", // 307
        "mux", // 308
        "node_command", // 309
        "node_slot", // 310
        "normalized_to_removal", // 311
        "number", // 312
        "oomRetrySaves", // 313
        "op", // 314
        "option", // 315
        "options", // 316
        "output_channels", // 317
        "overlay", // 318
        "overlay_changed", // 319
        "overlay_revision", // 320
        "owner", // 321
        "panel", // 322
        "panel_clear", // 323
        "panel_show", // 324
        "panel_write", // 325
        "parse_error", // 326
        "payload", // 327
        "payloads", // 328
        "period_seconds", // 329
        "phase", // 330
        "phase_offset", // 331
        "phasors", // 332
        "playlist_activate_entry", // 333
        "playlist_entry", // 334
        "policy", // 335
        "posted", // 336
        "presence_revision", // 337
        "present", // 338
        "primary", // 339
        "primary_visual", // 340
        "priority", // 341
        "project_nodes", // 342
        "projection", // 343
        "providers", // 344
        "put", // 345
        "put_slot_edit", // 346
        "queueWaitMaxUs", // 347
        "read", // 348
        "read_error", // 349
        "read_overlay", // 350
        "readings", // 351
        "reason", // 352
        "record", // 353
        "recursive", // 354
        "ref", // 355
        "refs", // 356
        "rejected", // 357
        "rejection", // 358
        "remove_node", // 359
        "remove_slot_edit", // 360
        "removed", // 361
        "render_product", // 362
        "replace_body", // 363
        "resources", // 364
        "result_begin", // 365
        "result_bytes", // 366
        "results", // 367
        "runtime_buffer", // 368
        "runtime_buffer_payload", // 369
        "runtime_buffer_payload_begin", // 370
        "runtime_buffer_payload_bytes", // 371
        "runtime_buffer_payload_end", // 372
        "scope", // 373
        "seconds", // 374
        "semantics", // 375
        "sent", // 376
        "setLogLevel", // 377
        "set_artifact_body", // 378
        "sidecar", // 379
        "sinceMs", // 380
        "site", // 381
        "slider", // 382
        "some", // 383
        "space", // 384
        "staged", // 385
        "staged_deletes", // 386
        "step", // 387
        "string", // 388
        "struct", // 389
        "summary", // 390
        "swept_pending_edits", // 391
        "tagged", // 392
        "texture", // 393
        "timebase", // 394
        "to", // 395
        "torn", // 396
        "total", // 397
        "ttl_ms", // 398
        "u32", // 399
        "u_vec2", // 400
        "u_vec3", // 401
        "u_vec4", // 402
        "unit", // 403
        "unknown", // 404
        "unloadProject", // 405
        "unsupported", // 406
        "validation_error", // 407
        "variant", // 408
        "variant_revision", // 409
        "variants", // 410
        "vec2", // 411
        "vec3", // 412
        "vec4", // 413
        "waved", // 414
        "waveform", // 415
        "width", // 416
        "wire", // 417
        "words", // 418
    ),
    offsets: &[
        0, 8, 10, 15, 20, 24, 27, 32, 37, 45, 50, 54, 65, 70, 82, 88,
        93, 99, 104, 113, 118, 130, 136, 143, 156, 169, 176, 181, 184, 190, 198, 203,
        213, 223, 229, 235, 239, 254, 261, 266, 275, 291, 297, 307, 316, 322, 329, 334,
        340, 356, 363, 376, 385, 389, 393, 400, 404, 407, 416, 422, 439, 442, 453, 467,
        476, 490, 499, 518, 535, 543, 552, 570, 574, 589, 592, 595, 611, 622, 640, 655,
        668, 673, 680, 694, 702, 713, 733, 741, 749, 753, 759, 778, 793, 804, 813, 820,
        826, 841, 846, 858, 863, 872, 890, 894, 900, 914, 924, 939, 952, 959, 973, 978,
        986, 997, 1002, 1010, 1013, 1023, 1026, 1031, 1037, 1044, 1050, 1058, 1066, 1068, 1072, 1078,
        1083, 1093, 1101, 1113, 1120, 1133, 1145, 1148, 1154, 1160, 1170, 1179, 1184, 1194, 1200, 1213,
        1217, 1223, 1233, 1240, 1245, 1251, 1263, 1269, 1278, 1283, 1288, 1296, 1304, 1309, 1327, 1334,
        1341, 1349, 1354, 1359, 1373, 1380, 1389, 1401, 1405, 1416, 1427, 1438, 1452, 1466, 1474, 1480,
        1486, 1487, 1494, 1501, 1513, 1520, 1526, 1530, 1544, 1551, 1552, 1555, 1560, 1566, 1574, 1584,
        1588, 1589, 1599, 1602, 1610, 1611, 1624, 1627, 1638, 1650, 1655, 1662, 1663, 1672, 1677, 1682,
        1687, 1692, 1701, 1712, 1716, 1724, 1729, 1734, 1750, 1759, 1771, 1777, 1789, 1795, 1801, 1807,
        1819, 1830, 1835, 1843, 1847, 1851, 1859, 1865, 1868, 1875, 1886, 1902, 1907, 1914, 1930, 1941,
        1955, 1960, 1968, 1982, 1991, 2001, 2012, 2018, 2023, 2039, 2051, 2061, 2074, 2085, 2094, 2100,
        2108, 2112, 2118, 2123, 2129, 2133, 2140, 2148, 2155, 2160, 2164, 2167, 2173, 2178, 2183, 2187,
        2190, 2204, 2208, 2213, 2219, 2223, 2227, 2239, 2245, 2251, 2254, 2260, 2266, 2272, 2278, 2291,
        2295, 2300, 2314, 2318, 2339, 2346, 2353, 2356, 2359, 2365, 2371, 2377, 2389, 2394, 2401, 2405,
        2413, 2419, 2434, 2448, 2456, 2459, 2471, 2480, 2501, 2507, 2520, 2522, 2528, 2535, 2550, 2557,
        2572, 2588, 2593, 2598, 2609, 2619, 2630, 2641, 2648, 2656, 2670, 2675, 2687, 2694, 2717, 2731,
        2737, 2743, 2760, 2767, 2774, 2788, 2796, 2809, 2819, 2828, 2831, 2844, 2858, 2862, 2872, 2884,
        2892, 2898, 2904, 2913, 2916, 2920, 2928, 2937, 2948, 2964, 2971, 2985, 2997, 3006, 3018, 3030,
        3037, 3051, 3073, 3101, 3129, 3155, 3160, 3167, 3176, 3180, 3191, 3208, 3215, 3222, 3226, 3232,
        3236, 3241, 3247, 3261, 3265, 3271, 3277, 3284, 3303, 3309, 3316, 3324, 3326, 3330, 3335, 3341,
        3344, 3350, 3356, 3362, 3366, 3373, 3386, 3397, 3413, 3420, 3436, 3444, 3448, 3452, 3456, 3461,
        3469, 3474, 3478, 3483,
    ],
};

const VALUES: PackStrings = PackStrings {
    text: concat!(
        "no_provider", // 0
        "u8", // 1
        "alive", // 2
        "Ok", // 3
        "detail", // 4
        "value", // 5
        "end", // 6
        "green", // 7
        "record", // 8
        "time", // 9
        "all", // 10
        "rgb", // 11
        "show", // 12
        "stopAllProjects", // 13
        "gfx.lpvm", // 14
        "hello", // 15
        "listLoadedProjects", // 16
        "node.button", // 17
        "node.clock", // 18
        "node.fixture", // 19
        "node.fluid", // 20
        "node.playlist", // 21
        "node.radio", // 22
        "node.shader", // 23
        "node.texture", // 24
        "svc.button", // 25
        "svc.radio-espnow", // 26
        "committed", // 27
        "Clock", // 28
        "Created", // 29
        "Fixture", // 30
        "Module", // 31
        "Output", // 32
        "Shader", // 33
        "always", // 34
        "fixture_map2d", // 35
        "root", // 36
        "shader_source", // 37
        "Button", // 38
        "ComputeShader", // 39
        "ControlRadio", // 40
        "Debug", // 41
        "Error", // 42
        "Fluid", // 43
        "Info", // 44
        "Playlist", // 45
        "Texture", // 46
        "Trace", // 47
        "Warn", // 48
        "accepted", // 49
        "affine2d", // 50
        "amplitude", // 51
        "angle", // 52
        "angular", // 53
        "any", // 54
        "audio_level", // 55
        "authored", // 56
        "available", // 57
        "b_vec2", // 58
        "b_vec3", // 59
        "b_vec4", // 60
        "bgr", // 61
        "binary", // 62
        "bool", // 63
        "brg", // 64
        "by_key", // 65
        "choice", // 66
        "clear", // 67
        "clearFaults", // 68
        "color", // 69
        "compute_shader_source", // 70
        "consumed", // 71
        "consumes", // 72
        "control", // 73
        "control_product", // 74
        "count", // 75
        "debug", // 76
        "declared", // 77
        "default", // 78
        "delete", // 79
        "deleted", // 80
        "diag.unwind", // 81
        "dimensions", // 82
        "duration", // 83
        "edit_failed", // 84
        "empty", // 85
        "ensure_present", // 86
        "enum", // 87
        "error", // 88
        "external", // 89
        "extrude_x", // 90
        "extrude_y", // 91
        "f32", // 92
        "fixed", // 93
        "fixture_colors", // 94
        "fixture_patch", // 95
        "forced", // 96
        "fragments", // 97
        "frequency", // 98
        "gbr", // 99
        "gfx.null", // 100
        "gfx.wgpu", // 101
        "gradient", // 102
        "grb", // 103
        "i32", // 104
        "i_vec2", // 105
        "i_vec3", // 106
        "i_vec4", // 107
        "ids", // 108
        "image", // 109
        "instant", // 110
        "invalid_body", // 111
        "invalid_path", // 112
        "latest", // 113
        "listAvailableProjects", // 114
        "local", // 115
        "map", // 116
        "mat2x2", // 117
        "mat3x3", // 118
        "mat4x4", // 119
        "node_ref", // 120
        "none", // 121
        "not_a_value_leaf", // 122
        "not_found", // 123
        "not_writable", // 124
        "omitted", // 125
        "one_d", // 126
        "option", // 127
        "output_channels", // 128
        "overlay_replace", // 129
        "panel", // 130
        "panel_writer", // 131
        "path", // 132
        "pending", // 133
        "phase", // 134
        "plain", // 135
        "position2d", // 136
        "position3d", // 137
        "power", // 138
        "produced", // 139
        "publishes", // 140
        "radial", // 141
        "ratio", // 142
        "raw", // 143
        "rbg", // 144
        "reboot", // 145
        "red", // 146
        "remove", // 147
        "resource", // 148
        "result_end", // 149
        "rgb8", // 150
        "rgba16", // 151
        "runtime_buffer", // 152
        "runtime_buffer_resource", // 153
        "setLogLevel", // 154
        "setting", // 155
        "shader.f32", // 156
        "srgb8", // 157
        "state", // 158
        "string", // 159
        "summary", // 160
        "target_occupied", // 161
        "text", // 162
        "texture", // 163
        "two_d", // 164
        "type_mismatch", // 165
        "u16", // 166
        "u32", // 167
        "u_vec2", // 168
        "u_vec3", // 169
        "u_vec4", // 170
        "unit", // 171
        "unknown_artifact", // 172
        "unknown_slot_path", // 173
        "unloadProject", // 174
        "unresolved", // 175
        "unset", // 176
        "unsupported", // 177
        "upsert", // 178
        "vec2", // 179
        "vec3", // 180
        "vec4", // 181
        "visual", // 182
        "visual_product", // 183
        "xy", // 184
        "yellow", // 185
    ),
    offsets: &[
        0, 11, 13, 18, 20, 26, 31, 34, 39, 45, 49, 52, 55, 59, 74, 82,
        87, 105, 116, 126, 138, 148, 161, 171, 182, 194, 204, 220, 229, 234, 241, 248,
        254, 260, 266, 272, 285, 289, 302, 308, 321, 333, 338, 343, 348, 352, 360, 367,
        372, 376, 384, 392, 401, 406, 413, 416, 427, 435, 444, 450, 456, 462, 465, 471,
        475, 478, 484, 490, 495, 506, 511, 532, 540, 548, 555, 570, 575, 580, 588, 595,
        601, 608, 619, 629, 637, 648, 653, 667, 671, 676, 684, 693, 702, 705, 710, 724,
        737, 743, 752, 761, 764, 772, 780, 788, 791, 794, 800, 806, 812, 815, 820, 827,
        839, 851, 857, 878, 883, 886, 892, 898, 904, 912, 916, 932, 941, 953, 960, 965,
        971, 986, 1001, 1006, 1018, 1022, 1029, 1034, 1039, 1049, 1059, 1064, 1072, 1081, 1087, 1092,
        1095, 1098, 1104, 1107, 1113, 1121, 1131, 1135, 1141, 1155, 1178, 1189, 1196, 1206, 1211, 1216,
        1222, 1229, 1244, 1248, 1255, 1260, 1273, 1276, 1279, 1285, 1291, 1297, 1301, 1317, 1334, 1347,
        1357, 1362, 1373, 1379, 1383, 1387, 1391, 1397, 1411, 1413, 1419,
    ],
};

const KEY_HASH: &[u16] = &[
    0x0109, 0x017a, 0x0163, 0x017e, 0x001a, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x016b, 0x00d3, 0x000d, 0xffff, 0xffff, 0xffff, 0xffff, 0x0041, 0xffff, 0x0077, 0xffff, 0xffff, 0xffff, 0x00dd, 0xffff, 0x00ce,
    0xffff, 0xffff, 0xffff, 0x006f, 0x018b, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x004f,
    0x0173, 0x008a, 0xffff, 0xffff, 0x011d, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ac, 0x002f, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0x013d, 0xffff, 0x006c, 0x00da, 0x0142, 0xffff, 0x0165, 0x0080, 0xffff, 0x016d, 0x0042, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00b0, 0x0167, 0xffff, 0x0016, 0xffff, 0xffff, 0xffff, 0x003f, 0x0009, 0xffff, 0x00e9, 0xffff, 0xffff, 0x0097,
    0x0117, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x002c, 0x0111, 0xffff, 0xffff, 0xffff, 0x0036, 0x0038, 0x0086, 0x00f6, 0x00fa,
    0xffff, 0x0094, 0x0136, 0x017f, 0xffff, 0x001d, 0x0114, 0x0135, 0x0162, 0xffff, 0xffff, 0x00e6, 0x0106, 0xffff, 0xffff, 0xffff,
    0xffff, 0x0122, 0xffff, 0xffff, 0x0112, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0024, 0xffff, 0xffff, 0xffff, 0x007b,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x004e, 0x016e, 0xffff, 0x0191, 0x0044, 0x00b1, 0xffff, 0xffff, 0x0002,
    0x0138, 0xffff, 0xffff, 0xffff, 0xffff, 0x0119, 0x013c, 0xffff, 0xffff, 0xffff, 0x013a, 0x009c, 0x0199, 0xffff, 0xffff, 0x019a,
    0xffff, 0x018f, 0xffff, 0x00c3, 0xffff, 0xffff, 0xffff, 0x00a0, 0xffff, 0xffff, 0xffff, 0x0083, 0x0192, 0xffff, 0x014d, 0xffff,
    0x00a4, 0xffff, 0x012b, 0x00e2, 0x0137, 0xffff, 0x0150, 0xffff, 0xffff, 0xffff, 0x0069, 0x0018, 0x0161, 0xffff, 0xffff, 0x0022,
    0x0040, 0xffff, 0xffff, 0xffff, 0x0141, 0x00ed, 0xffff, 0x00f4, 0xffff, 0x00be, 0x0104, 0xffff, 0xffff, 0xffff, 0x00c5, 0x0076,
    0xffff, 0xffff, 0x019c, 0xffff, 0x0125, 0x012d, 0xffff, 0xffff, 0xffff, 0x0084, 0x0065, 0x0181, 0x0152, 0xffff, 0xffff, 0x00fb,
    0xffff, 0x00cd, 0xffff, 0x0179, 0x0187, 0x0189, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0096, 0x0079, 0xffff, 0x00bc,
    0x0087, 0x013f, 0xffff, 0x013e, 0x0039, 0x019d, 0xffff, 0x00cf, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0146, 0xffff, 0x011e,
    0xffff, 0x015b, 0xffff, 0xffff, 0xffff, 0xffff, 0x003a, 0x00db, 0x00c8, 0x0058, 0x00de, 0x010f, 0xffff, 0xffff, 0x0028, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0063, 0x00d6, 0x0166, 0xffff, 0xffff, 0x0031, 0x0019, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0045, 0xffff, 0x0035, 0xffff, 0x00ae, 0x0184, 0xffff, 0xffff, 0xffff, 0x00e4, 0xffff, 0x003b,
    0x00d4, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0099, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0156, 0x0126, 0x0113, 0xffff, 0x0103, 0xffff, 0xffff, 0x004a, 0x015d, 0xffff, 0xffff, 0x002b, 0x0132, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ba, 0xffff, 0xffff, 0x00ea, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00f5, 0x008c, 0xffff, 0x00e3, 0xffff, 0xffff, 0xffff, 0x0067, 0xffff, 0x0075, 0x005f, 0x00b3, 0x0064, 0xffff,
    0x0157, 0xffff, 0x00c4, 0xffff, 0xffff, 0xffff, 0x0092, 0x0198, 0xffff, 0xffff, 0x003d, 0xffff, 0xffff, 0xffff, 0x0043, 0xffff,
    0xffff, 0x0008, 0x0100, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x01a1, 0xffff, 0x005d, 0xffff, 0x0056, 0x0026, 0x0154, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x001e, 0x007a, 0xffff, 0xffff, 0x001b, 0x0003, 0x005a, 0xffff, 0x0029, 0x0197,
    0xffff, 0x000f, 0x0025, 0xffff, 0xffff, 0x00f0, 0xffff, 0x00ee, 0xffff, 0xffff, 0xffff, 0x0030, 0x00cc, 0xffff, 0xffff, 0x004b,
    0xffff, 0x0091, 0x0130, 0xffff, 0xffff, 0xffff, 0x0033, 0xffff, 0xffff, 0x0088, 0xffff, 0xffff, 0xffff, 0x0188, 0x011b, 0x00a8,
    0x00d2, 0x005c, 0x0059, 0x0081, 0x0085, 0x00f1, 0x0139, 0x019f, 0x0090, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ad, 0x0143,
    0x0074, 0xffff, 0x0148, 0x0006, 0x0164, 0xffff, 0x0034, 0x012a, 0x00bf, 0xffff, 0x0176, 0xffff, 0xffff, 0xffff, 0x0159, 0x00ab,
    0x0072, 0x00d8, 0xffff, 0xffff, 0x0071, 0x0032, 0xffff, 0x0014, 0x014a, 0x009b, 0x00e7, 0x00c7, 0x00e0, 0x0115, 0xffff, 0x0048,
    0xffff, 0xffff, 0x00a9, 0xffff, 0xffff, 0xffff, 0xffff, 0x0193, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0004, 0x009d, 0x00b5,
    0x0124, 0x0183, 0x019e, 0xffff, 0xffff, 0xffff, 0x015e, 0x0177, 0x0000, 0x008f, 0x0160, 0x00d1, 0x002a, 0xffff, 0xffff, 0x01a0,
    0x00eb, 0x011f, 0x0185, 0xffff, 0x0010, 0xffff, 0xffff, 0x012c, 0xffff, 0x00bd, 0x0145, 0xffff, 0xffff, 0x0190, 0x007c, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c9, 0xffff, 0xffff, 0xffff, 0xffff, 0x004c, 0xffff, 0xffff, 0xffff, 0x00e8,
    0x0121, 0xffff, 0xffff, 0x000a, 0xffff, 0xffff, 0xffff, 0x0061, 0xffff, 0xffff, 0xffff, 0x0057, 0x00d0, 0xffff, 0x017d, 0x007e,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00bb, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0129,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0131, 0x010d, 0xffff, 0x0047, 0xffff, 0x0168, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0151, 0x019b, 0xffff, 0xffff, 0x0101, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x000c, 0x00e5,
    0x014f, 0x018e, 0xffff, 0xffff, 0xffff, 0x0180, 0xffff, 0x011c, 0xffff, 0xffff, 0x00dc, 0x01a2, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ca, 0x00a5, 0xffff, 0xffff, 0x0098, 0xffff, 0x0134, 0x0095, 0xffff,
    0x017b, 0xffff, 0xffff, 0x0093, 0x00a3, 0x0037, 0x00ec, 0xffff, 0x003c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0017, 0xffff, 0x00b4, 0xffff, 0x00a2, 0x00af, 0x0170, 0xffff, 0xffff, 0x017c, 0xffff, 0x0062, 0x0068, 0x00aa, 0x0012, 0x0051,
    0x014c, 0xffff, 0xffff, 0xffff, 0x010a, 0xffff, 0x0102, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x004d, 0x018a, 0x00c2, 0x0144, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ff, 0x001f, 0xffff, 0xffff, 0xffff, 0x0158, 0xffff, 0xffff,
    0x0001, 0x003e, 0xffff, 0xffff, 0xffff, 0x00d5, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0182, 0x016a, 0x009f, 0xffff,
    0xffff, 0xffff, 0x0116, 0x00b8, 0x0195, 0x016f, 0x0011, 0x0128, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x018d, 0xffff, 0xffff,
    0xffff, 0x0020, 0x0005, 0xffff, 0x000e, 0x0052, 0x0053, 0xffff, 0xffff, 0x0155, 0xffff, 0xffff, 0x0073, 0xffff, 0xffff, 0x0110,
    0x0082, 0xffff, 0xffff, 0x0186, 0xffff, 0x00d7, 0xffff, 0xffff, 0x015f, 0x0049, 0xffff, 0xffff, 0x0054, 0xffff, 0xffff, 0xffff,
    0xffff, 0x0174, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00f8, 0xffff, 0xffff,
    0x0196, 0x0172, 0xffff, 0xffff, 0xffff, 0xffff, 0x00cb, 0xffff, 0xffff, 0xffff, 0xffff, 0x0171, 0xffff, 0xffff, 0xffff, 0xffff,
    0x012f, 0xffff, 0x0118, 0x010e, 0x0133, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b2, 0xffff, 0xffff, 0xffff, 0x0149, 0xffff,
    0xffff, 0x006e, 0xffff, 0xffff, 0xffff, 0xffff, 0x00d9, 0x0078, 0x00b9, 0x005b, 0x012e, 0xffff, 0x007f, 0xffff, 0x006d, 0xffff,
    0xffff, 0x011a, 0xffff, 0xffff, 0xffff, 0x006b, 0xffff, 0xffff, 0xffff, 0x00fc, 0x00fd, 0xffff, 0xffff, 0x00b6, 0x0027, 0xffff,
    0xffff, 0x007d, 0xffff, 0xffff, 0xffff, 0xffff, 0x000b, 0xffff, 0xffff, 0xffff, 0xffff, 0x008b, 0xffff, 0xffff, 0x0107, 0x010c,
    0x0178, 0xffff, 0xffff, 0xffff, 0x001c, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c1, 0xffff, 0x008e, 0x002e, 0x0060, 0xffff, 0x00f2,
    0xffff, 0x0089, 0xffff, 0x0108, 0x013b, 0xffff, 0xffff, 0xffff, 0x0023, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x005e, 0x0050,
    0x0105, 0xffff, 0xffff, 0xffff, 0xffff, 0x0147, 0xffff, 0xffff, 0x00b7, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x014e, 0x00a1, 0x0127, 0xffff, 0x010b, 0x015a, 0xffff, 0xffff, 0xffff, 0x0140, 0x0055, 0x0194, 0x002d, 0x00c6, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x015c, 0x0046, 0xffff, 0xffff, 0x00ef, 0x0007, 0x008d, 0x009a, 0xffff, 0x00f3, 0xffff,
    0xffff, 0x00a7, 0xffff, 0x0021, 0xffff, 0x00df, 0x0123, 0x0070, 0xffff, 0x0153, 0xffff, 0x0169, 0xffff, 0x0013, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0066, 0x018c, 0xffff, 0xffff, 0xffff, 0xffff, 0x006a, 0x014b, 0x0175, 0xffff, 0xffff, 0x0015,
    0x00c0, 0x00f7, 0x00fe, 0x016c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x009e, 0x00e1, 0x00f9, 0x0120, 0x00a6,
];

const VALUE_HASH: &[u16] = &[
    0x0057, 0x0062, 0xffff, 0xffff, 0xffff, 0xffff, 0x0002, 0x00ab, 0x0025, 0xffff, 0x00af, 0xffff, 0x0096, 0x0089, 0x0010, 0xffff,
    0xffff, 0x0030, 0x00b7, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0034, 0xffff, 0xffff, 0xffff, 0x00ad, 0x003b, 0xffff, 0xffff,
    0xffff, 0xffff, 0x0043, 0xffff, 0xffff, 0x002c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00a8, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0048, 0xffff, 0xffff, 0xffff, 0x0063, 0xffff, 0x000c, 0xffff, 0x00a2, 0xffff,
    0xffff, 0x0080, 0xffff, 0xffff, 0xffff, 0x0024, 0x0071, 0x0082, 0xffff, 0x00b9, 0x004f, 0xffff, 0xffff, 0x0036, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00a4, 0xffff, 0xffff, 0xffff, 0x0042, 0xffff, 0x0045, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0076,
    0x007c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0018, 0xffff, 0x0050, 0xffff, 0xffff, 0x0019, 0x006f, 0x008d,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0028, 0x00b3, 0xffff, 0xffff, 0xffff, 0x0046, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x008e, 0xffff, 0xffff, 0x006b, 0x0021, 0x0099, 0x003a, 0x0059, 0x0081, 0xffff, 0x000d, 0xffff,
    0xffff, 0x0026, 0xffff, 0xffff, 0x0004, 0xffff, 0x0040, 0x009d, 0x0039, 0x001b, 0x00a9, 0x0054, 0x007e, 0xffff, 0xffff, 0x0014,
    0x0060, 0xffff, 0x0033, 0xffff, 0xffff, 0x0066, 0x0068, 0xffff, 0xffff, 0x0012, 0xffff, 0x000f, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0052, 0x00a7, 0xffff, 0x004d, 0xffff, 0xffff, 0x0090, 0x0098, 0xffff, 0xffff, 0xffff, 0x00aa, 0x0007, 0x001f, 0x003d, 0xffff,
    0xffff, 0xffff, 0xffff, 0x0056, 0x005c, 0xffff, 0xffff, 0xffff, 0x00ac, 0xffff, 0xffff, 0xffff, 0x0008, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x001e, 0xffff, 0xffff, 0xffff, 0xffff, 0x0038, 0xffff, 0xffff, 0xffff, 0xffff, 0x0092, 0xffff, 0xffff, 0x001a,
    0x0016, 0xffff, 0x00b4, 0xffff, 0xffff, 0x0051, 0xffff, 0xffff, 0xffff, 0xffff, 0x0061, 0xffff, 0xffff, 0xffff, 0x0055, 0xffff,
    0xffff, 0x002a, 0x008f, 0x009a, 0x00a3, 0x00ae, 0x009e, 0x0075, 0x0001, 0xffff, 0xffff, 0xffff, 0x003e, 0x001c, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0x00b5, 0xffff, 0xffff, 0x0095, 0xffff, 0x0073, 0xffff, 0xffff, 0xffff, 0xffff, 0x0053, 0xffff, 0x005e,
    0xffff, 0xffff, 0xffff, 0x002b, 0x00a0, 0xffff, 0xffff, 0xffff, 0x003c, 0x0041, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00a6,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0020, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x00b1, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0084, 0x0078, 0x0029, 0x009f, 0xffff, 0xffff, 0x0085, 0x003f, 0xffff, 0xffff,
    0x0031, 0x0083, 0xffff, 0xffff, 0xffff, 0xffff, 0x008a, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0013, 0x002f,
    0xffff, 0x0058, 0xffff, 0x0027, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x007d, 0xffff, 0x001d, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0037, 0x0023, 0x0069, 0xffff, 0xffff, 0xffff, 0xffff, 0x0087, 0xffff, 0x006c, 0xffff, 0xffff, 0xffff, 0x005a, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b6, 0x00b0, 0xffff, 0x000b, 0x0097, 0x0070, 0x009c,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0032, 0xffff, 0xffff, 0x002d, 0xffff, 0x0011, 0xffff, 0x000e,
    0xffff, 0xffff, 0xffff, 0x0064, 0x002e, 0x007f, 0xffff, 0xffff, 0x004c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0049, 0xffff,
    0xffff, 0xffff, 0x00b2, 0xffff, 0x0088, 0xffff, 0xffff, 0x0065, 0xffff, 0xffff, 0x0006, 0x009b, 0x00a5, 0xffff, 0x0000, 0xffff,
    0xffff, 0x0074, 0x006e, 0xffff, 0xffff, 0xffff, 0xffff, 0x0015, 0x0044, 0x0091, 0x00a1, 0x005f, 0xffff, 0xffff, 0xffff, 0x0047,
    0xffff, 0xffff, 0xffff, 0xffff, 0x000a, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0005, 0xffff, 0xffff, 0xffff, 0x006a, 0x0003,
    0xffff, 0x007b, 0x008b, 0xffff, 0xffff, 0xffff, 0x0072, 0xffff, 0xffff, 0xffff, 0x005b, 0x0067, 0x0017, 0x0079, 0x004e, 0x00b8,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0009, 0x0022, 0xffff, 0x0077, 0xffff, 0x0035, 0x004a, 0x007a, 0x008c, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x004b, 0x0094, 0xffff, 0xffff, 0x0086, 0x005d, 0x006d, 0xffff, 0xffff, 0x0093, 0xffff, 0xffff,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_well_formed_and_match_their_fingerprint() {
        assert_eq!(WIRE_DICTIONARY.check(), Ok(()));
        assert_eq!(WIRE_DICTIONARY.fingerprint(), WIRE_DICTIONARY_FINGERPRINT);
    }
}
