//! The wire's JSON Pack dictionary: what a packed frame is coded against.
//!
//! GENERATED by `just wire-dict`
//! (`cargo run -p lpc-wire --features wire-dict-gen --bin wire-dict`). Do not
//! edit: `just wire-dict-check` (in `check-lint`) fails when this file is not
//! what the generator writes, and when the dictionary changed without a
//! `WIRE_PROTO_VERSION` bump.
//!
//! - Keys: every struct field name and every data-carrying enum variant name
//!   reachable from `WireServerMessage` and `ClientMessage`, found by tracing
//!   their `Deserialize` impls (`wire_dictionary_gen`).
//! - Values: every unit variant name.
//! - Both: the keys and string tags of the slot text codec
//!   (`lpc-model`'s `slot_sync_codec` / `slot_codec` writers), which writes
//!   `WireSlotData`'s pre-serialized JSON.
//! - Order: by frequency in the committed traffic sample
//!   (`lp-base/lp-json-pack/tests/fixtures/choker-lens-sample.txt`),
//!   then by name. The commonest get the one-byte codes.
//!
//! 445 keys (214 ranked by the sample), 195 values (46 ranked); 9533 bytes
//! of statics.

use lp_json_pack::{Dictionary, PackStrings};

/// The `WIRE_PROTO_VERSION` this dictionary was generated at.
pub const WIRE_DICTIONARY_PROTO: u32 = 27;

/// [`WIRE_DICTIONARY`]'s `fingerprint()`, as generated.
pub const WIRE_DICTIONARY_FINGERPRINT: u32 = 0x1615671f;

/// The wire's dictionary.
pub static WIRE_DICTIONARY: Dictionary = Dictionary {
    keys: KEYS,
    values: VALUES,
    key_hash: KEY_HASH,
    value_hash: VALUE_HASH,
};

const KEYS: PackStrings = PackStrings {
    text: concat!(
        "revision", // 0
        "kind", // 1
        "event", // 2
        "index", // 3
        "value", // 4
        "node", // 5
        "query", // 6
        "output", // 7
        "nodes", // 8
        "changed_at", // 9
        "level", // 10
        "product", // 11
        "id", // 12
        "msg", // 13
        "begin", // 14
        "geometry", // 15
        "probe", // 16
        "result", // 17
        "shapes", // 18
        "unchanged", // 19
        "projectRead", // 20
        "output_frame", // 21
        "data", // 22
        "values", // 23
        "rows", // 24
        "samples_per_row", // 25
        "sample_format", // 26
        "outputs", // 27
        "if_changed", // 28
        "known", // 29
        "presence_revision", // 30
        "present", // 31
        "bytes", // 32
        "binding_graph", // 33
        "runtime", // 34
        "structure", // 35
        "preferred_extent", // 36
        "fields", // 37
        "fields_revision", // 38
        "freeBytes", // 39
        "largestFreeBlock", // 40
        "memory", // 41
        "totalBytes", // 42
        "usedBytes", // 43
        "handle", // 44
        "name", // 45
        "end", // 46
        "events", // 47
        "channels", // 48
        "frame", // 49
        "shape", // 50
        "slot_root", // 51
        "control", // 52
        "demand_root_count", // 53
        "frame_delta_ms", // 54
        "frame_num", // 55
        "frame_total_ms", // 56
        "graph", // 57
        "ids_revision", // 58
        "last_frame_time_us", // 59
        "overlay_changed_at", // 60
        "panel_auto_save", // 61
        "project", // 62
        "runtime_buffer_count", // 63
        "server", // 64
        "structure_revision", // 65
        "theoretical_fps", // 66
        "time", // 67
        "visual", // 68
        "request", // 69
        "since", // 70
        "probes", // 71
        "samples", // 72
        "path", // 73
        "include_slots", // 74
        "include_values", // 75
        "queries", // 76
        "control_product", // 77
        "baseMac", // 78
        "avg", // 79
        "bootCount", // 80
        "color_order", // 81
        "count", // 82
        "encoding", // 83
        "fps", // 84
        "frame_count", // 85
        "heartbeat", // 86
        "hostDrainingAgainMs", // 87
        "hostNotDrainingMs", // 88
        "identity", // 89
        "lastCrash", // 90
        "len", // 91
        "link", // 92
        "loaded_projects", // 93
        "max", // 94
        "min", // 95
        "notDrainingCount", // 96
        "outputClamp", // 97
        "parseFailures", // 98
        "paths", // 99
        "queueFullDrops", // 100
        "recovery", // 101
        "resetReason", // 102
        "rgb_pixels", // 103
        "row", // 104
        "rxErrors", // 105
        "safeMode", // 106
        "sdev", // 107
        "stalePartialFlushes", // 108
        "start", // 109
        "uptime_ms", // 110
        "key", // 111
        "extent", // 112
        "filesystem", // 113
        "preview", // 114
        "artifact", // 115
        "entries", // 116
        "state", // 117
        "keys_revision", // 118
        "error", // 119
        "parent", // 120
        "location", // 121
        "segments", // 122
        "ty", // 123
        "variant", // 124
        "variant_revision", // 125
        "slot", // 126
        "origin", // 127
        "write", // 128
        "change_frame", // 129
        "child_kind", // 130
        "children", // 131
        "children_ver", // 132
        "created", // 133
        "created_frame", // 134
        "def_location", // 135
        "loaded", // 136
        "prefix", // 137
        "runtime_id", // 138
        "space", // 139
        "status", // 140
        "input", // 141
        "invocation", // 142
        "offset", // 143
        "project_child", // 144
        "role", // 145
        "source", // 146
        "writeChunk", // 147
        "listLoadedProjects", // 148
        "projects", // 149
        "written", // 150
        "auth", // 151
        "available", // 152
        "boardId", // 153
        "build", // 154
        "button", // 155
        "c", // 156
        "changed", // 157
        "chipRevision", // 158
        "commit", // 159
        "content_type", // 160
        "deleteDir", // 161
        "deviceUid", // 162
        "dirty", // 163
        "display_layout", // 164
        "eui64", // 165
        "features", // 166
        "granted", // 167
        "h", // 168
        "hardware", // 169
        "hash", // 170
        "hashPackage", // 171
        "hello", // 172
        "layout", // 173
        "layout2d", // 174
        "loadProject", // 175
        "p", // 176
        "packDictionary", // 177
        "package", // 178
        "packageHash", // 179
        "period_seconds", // 180
        "phase_offset", // 181
        "profile", // 182
        "projectCommand", // 183
        "proto", // 184
        "radio", // 185
        "read_inventory", // 186
        "required", // 187
        "response", // 188
        "rev", // 189
        "s", // 190
        "sample_layout", // 191
        "spans", // 192
        "totalLedBudget", // 193
        "w", // 194
        "waveform", // 195
        "assets", // 196
        "changes", // 197
        "changesSince", // 198
        "command", // 199
        "cursor", // 200
        "defs", // 201
        "deltas", // 202
        "height", // 203
        "lamps", // 204
        "next", // 205
        "placements", // 206
        "reversed", // 207
        "source_lamp", // 208
        "source_lamps", // 209
        "tree_deltas", // 210
        "version", // 211
        "width", // 212
        "wire_lamp", // 213
        "Error", // 214
        "Fault", // 215
        "Field", // 216
        "Index", // 217
        "InitError", // 218
        "Unsupported", // 219
        "Warn", // 220
        "accepted", // 221
        "accessAdd", // 222
        "accessList", // 223
        "accessRemove", // 224
        "accessSetSwitches", // 225
        "added", // 226
        "addedAt", // 227
        "array", // 228
        "artifact_changes", // 229
        "artifacts", // 230
        "assign_value", // 231
        "attach", // 232
        "availability", // 233
        "b_vec2", // 234
        "b_vec3", // 235
        "b_vec4", // 236
        "base_display", // 237
        "base_values", // 238
        "batch", // 239
        "bindings", // 240
        "bleEnabled", // 241
        "body", // 242
        "bool", // 243
        "bootsAgo", // 244
        "buffer", // 245
        "bus", // 246
        "by_ids", // 247
        "by_refs", // 248
        "byte_length", // 249
        "byte_length_hint", // 250
        "cause", // 251
        "channel", // 252
        "children_changed", // 253
        "clearFaults", // 254
        "clear_artifact", // 255
        "codec", // 256
        "commands", // 257
        "commit_overlay", // 258
        "consumers", // 259
        "crashCount", // 260
        "create_node", // 261
        "custom", // 262
        "cycle", // 263
        "default_1d_to_2d", // 264
        "default_bind", // 265
        "deleteFile", // 266
        "delta_seconds", // 267
        "description", // 268
        "dictionary", // 269
        "direction", // 270
        "domain", // 271
        "dropdown", // 272
        "edit", // 273
        "editor", // 274
        "edits", // 275
        "effect", // 276
        "elem", // 277
        "enabled", // 278
        "endpoint", // 279
        "engaged", // 280
        "entry", // 281
        "entry_changed", // 282
        "enum", // 283
        "f32", // 284
        "failed", // 285
        "fault", // 286
        "field", // 287
        "file", // 288
        "fin", // 289
        "fixture_colors", // 290
        "flip", // 291
        "force", // 292
        "format", // 293
        "from", // 294
        "gpio", // 295
        "gpu_resident", // 296
        "header", // 297
        "i32", // 298
        "i_vec2", // 299
        "i_vec3", // 300
        "i_vec4", // 301
        "ids", // 302
        "inline", // 303
        "iterations", // 304
        "k", // 305
        "knob", // 306
        "label", // 307
        "ledger_cleared", // 308
        "list", // 309
        "listAvailableProjects", // 310
        "listDir", // 311
        "literal", // 312
        "log", // 313
        "loginAnswer", // 314
        "loginChallenge", // 315
        "loginResult", // 316
        "macs", // 317
        "map", // 318
        "mat2x2", // 319
        "mat3x3", // 320
        "mat4x4", // 321
        "materialized", // 322
        "membership", // 323
        "merge", // 324
        "message", // 325
        "meta", // 326
        "metadata", // 327
        "mirror", // 328
        "move_slot_entry", // 329
        "mutate_overlay", // 330
        "mutation", // 331
        "mux", // 332
        "needs", // 333
        "node_command", // 334
        "node_slot", // 335
        "nonce", // 336
        "normalized_to_removal", // 337
        "notPermitted", // 338
        "number", // 339
        "offers", // 340
        "oomRetrySaves", // 341
        "op", // 342
        "open", // 343
        "option", // 344
        "options", // 345
        "output_channels", // 346
        "overlay", // 347
        "overlay_changed", // 348
        "overlay_revision", // 349
        "owner", // 350
        "panel", // 351
        "panel_clear", // 352
        "panel_show", // 353
        "panel_write", // 354
        "parse_error", // 355
        "payload", // 356
        "payloads", // 357
        "phase", // 358
        "phasors", // 359
        "playlist_activate_entry", // 360
        "playlist_entry", // 361
        "policy", // 362
        "posted", // 363
        "primary", // 364
        "primary_visual", // 365
        "priority", // 366
        "project_nodes", // 367
        "projection", // 368
        "providers", // 369
        "put", // 370
        "put_slot_edit", // 371
        "queueWaitMaxUs", // 372
        "read", // 373
        "read_error", // 374
        "read_overlay", // 375
        "readings", // 376
        "reason", // 377
        "record", // 378
        "recursive", // 379
        "ref", // 380
        "refs", // 381
        "refused", // 382
        "rejected", // 383
        "rejection", // 384
        "remove_node", // 385
        "remove_slot_edit", // 386
        "removed", // 387
        "render_product", // 388
        "replace_body", // 389
        "resources", // 390
        "result_begin", // 391
        "result_bytes", // 392
        "results", // 393
        "retryAfterMs", // 394
        "runtime_buffer", // 395
        "runtime_buffer_payload", // 396
        "runtime_buffer_payload_begin", // 397
        "runtime_buffer_payload_bytes", // 398
        "runtime_buffer_payload_end", // 399
        "salt", // 400
        "scope", // 401
        "seconds", // 402
        "semantics", // 403
        "sent", // 404
        "seq", // 405
        "setEncoding", // 406
        "setLogLevel", // 407
        "set_artifact_body", // 408
        "sidecar", // 409
        "sinceMs", // 410
        "site", // 411
        "slider", // 412
        "some", // 413
        "staged", // 414
        "staged_deletes", // 415
        "step", // 416
        "string", // 417
        "struct", // 418
        "summary", // 419
        "swept_pending_edits", // 420
        "tagged", // 421
        "texture", // 422
        "tier", // 423
        "timebase", // 424
        "to", // 425
        "torn", // 426
        "total", // 427
        "ttl_ms", // 428
        "u32", // 429
        "u_vec2", // 430
        "u_vec3", // 431
        "u_vec4", // 432
        "unit", // 433
        "unknown", // 434
        "unloadProject", // 435
        "unsupported", // 436
        "validation_error", // 437
        "variants", // 438
        "vec2", // 439
        "vec3", // 440
        "vec4", // 441
        "waved", // 442
        "wire", // 443
        "words", // 444
    ),
    offsets: &[
        0, 8, 12, 17, 22, 27, 31, 36, 42, 47, 57, 62, 69, 71, 74, 79,
        87, 92, 98, 104, 113, 124, 136, 140, 146, 150, 165, 178, 185, 195, 200, 217,
        224, 229, 242, 249, 258, 274, 280, 295, 304, 320, 326, 336, 345, 351, 355, 358,
        364, 372, 377, 382, 391, 398, 415, 429, 438, 452, 457, 469, 487, 505, 520, 527,
        547, 553, 571, 586, 590, 596, 603, 608, 614, 621, 625, 638, 652, 659, 674, 681,
        684, 693, 704, 709, 717, 720, 731, 740, 759, 776, 784, 793, 796, 800, 815, 818,
        821, 837, 848, 861, 866, 880, 888, 899, 909, 912, 920, 928, 932, 951, 956, 965,
        968, 974, 984, 991, 999, 1006, 1011, 1024, 1029, 1035, 1043, 1051, 1053, 1060, 1076, 1080,
        1086, 1091, 1103, 1113, 1121, 1133, 1140, 1153, 1165, 1171, 1177, 1187, 1192, 1198, 1203, 1213,
        1219, 1232, 1236, 1242, 1252, 1270, 1278, 1285, 1289, 1298, 1305, 1310, 1316, 1317, 1324, 1336,
        1342, 1354, 1363, 1372, 1377, 1391, 1396, 1404, 1411, 1412, 1420, 1424, 1435, 1440, 1446, 1454,
        1465, 1466, 1480, 1487, 1498, 1512, 1524, 1531, 1545, 1550, 1555, 1569, 1577, 1585, 1588, 1589,
        1602, 1607, 1621, 1622, 1630, 1636, 1643, 1655, 1662, 1668, 1672, 1678, 1684, 1689, 1693, 1703,
        1711, 1722, 1734, 1745, 1752, 1757, 1766, 1771, 1776, 1781, 1786, 1795, 1806, 1810, 1818, 1827,
        1837, 1849, 1866, 1871, 1878, 1883, 1899, 1908, 1920, 1926, 1938, 1944, 1950, 1956, 1968, 1979,
        1984, 1992, 2002, 2006, 2010, 2018, 2024, 2027, 2033, 2040, 2051, 2067, 2072, 2079, 2095, 2106,
        2120, 2125, 2133, 2147, 2156, 2166, 2177, 2183, 2188, 2204, 2216, 2226, 2239, 2250, 2260, 2269,
        2275, 2283, 2287, 2293, 2298, 2304, 2308, 2315, 2323, 2330, 2335, 2348, 2352, 2355, 2361, 2366,
        2371, 2375, 2378, 2392, 2396, 2401, 2407, 2411, 2415, 2427, 2433, 2436, 2442, 2448, 2454, 2457,
        2463, 2473, 2474, 2478, 2483, 2497, 2501, 2522, 2529, 2536, 2539, 2550, 2564, 2575, 2579, 2582,
        2588, 2594, 2600, 2612, 2622, 2627, 2634, 2638, 2646, 2652, 2667, 2681, 2689, 2692, 2697, 2709,
        2718, 2723, 2744, 2756, 2762, 2768, 2781, 2783, 2787, 2793, 2800, 2815, 2822, 2837, 2853, 2858,
        2863, 2874, 2884, 2895, 2906, 2913, 2921, 2926, 2933, 2956, 2970, 2976, 2982, 2989, 3003, 3011,
        3024, 3034, 3043, 3046, 3059, 3073, 3077, 3087, 3099, 3107, 3113, 3119, 3128, 3131, 3135, 3142,
        3150, 3159, 3170, 3186, 3193, 3207, 3219, 3228, 3240, 3252, 3259, 3271, 3285, 3307, 3335, 3363,
        3389, 3393, 3398, 3405, 3414, 3418, 3421, 3432, 3443, 3460, 3467, 3474, 3478, 3484, 3488, 3494,
        3508, 3512, 3518, 3524, 3531, 3550, 3556, 3563, 3567, 3575, 3577, 3581, 3586, 3592, 3595, 3601,
        3607, 3613, 3617, 3624, 3637, 3648, 3664, 3672, 3676, 3680, 3684, 3689, 3693, 3698,
    ],
};

const VALUES: PackStrings = PackStrings {
    text: concat!(
        "no_provider", // 0
        "value", // 1
        "detail", // 2
        "srgb8", // 3
        "end", // 4
        "option", // 5
        "record", // 6
        "time", // 7
        "all", // 8
        "rgb", // 9
        "green", // 10
        "map", // 11
        "enum", // 12
        "alive", // 13
        "show", // 14
        "Ok", // 15
        "f32", // 16
        "listLoadedProjects", // 17
        "unit", // 18
        "visual", // 19
        "committed", // 20
        "control", // 21
        "edit", // 22
        "gfx.lpvm", // 23
        "hello", // 24
        "node.button", // 25
        "node.clock", // 26
        "node.fixture", // 27
        "node.fluid", // 28
        "node.playlist", // 29
        "node.radio", // 30
        "node.shader", // 31
        "node.texture", // 32
        "stopAllProjects", // 33
        "svc.button", // 34
        "svc.radio-espnow", // 35
        "Clock", // 36
        "Created", // 37
        "Fixture", // 38
        "Module", // 39
        "Output", // 40
        "Shader", // 41
        "always", // 42
        "fixture_map2d", // 43
        "root", // 44
        "shader_source", // 45
        "Button", // 46
        "ComputeShader", // 47
        "ControlRadio", // 48
        "Debug", // 49
        "Error", // 50
        "Fluid", // 51
        "Info", // 52
        "Playlist", // 53
        "Texture", // 54
        "Trace", // 55
        "Warn", // 56
        "accepted", // 57
        "accessList", // 58
        "account", // 59
        "affine2d", // 60
        "amplitude", // 61
        "angle", // 62
        "angular", // 63
        "any", // 64
        "audio_level", // 65
        "authored", // 66
        "available", // 67
        "b_vec2", // 68
        "b_vec3", // 69
        "b_vec4", // 70
        "bgr", // 71
        "binary", // 72
        "bool", // 73
        "brg", // 74
        "browser", // 75
        "by_key", // 76
        "choice", // 77
        "clear", // 78
        "clearFaults", // 79
        "color", // 80
        "compute_shader_source", // 81
        "consumed", // 82
        "consumes", // 83
        "control_product", // 84
        "count", // 85
        "debug", // 86
        "declared", // 87
        "default", // 88
        "delete", // 89
        "deleted", // 90
        "diag.unwind", // 91
        "dimensions", // 92
        "duration", // 93
        "edit_failed", // 94
        "empty", // 95
        "ensure_present", // 96
        "error", // 97
        "external", // 98
        "extrude_x", // 99
        "extrude_y", // 100
        "fixed", // 101
        "fixture_colors", // 102
        "fixture_patch", // 103
        "forced", // 104
        "fragments", // 105
        "frequency", // 106
        "gbr", // 107
        "gfx.null", // 108
        "gfx.wgpu", // 109
        "gradient", // 110
        "grb", // 111
        "i32", // 112
        "i_vec2", // 113
        "i_vec3", // 114
        "i_vec4", // 115
        "ids", // 116
        "image", // 117
        "instant", // 118
        "invalid_body", // 119
        "invalid_path", // 120
        "json", // 121
        "latest", // 122
        "listAvailableProjects", // 123
        "local", // 124
        "loginBegin", // 125
        "mat2x2", // 126
        "mat3x3", // 127
        "mat4x4", // 128
        "node_ref", // 129
        "none", // 130
        "not_a_value_leaf", // 131
        "not_found", // 132
        "not_writable", // 133
        "omitted", // 134
        "one_d", // 135
        "output_channels", // 136
        "overlay_replace", // 137
        "packed", // 138
        "panel", // 139
        "panel_writer", // 140
        "password", // 141
        "path", // 142
        "pending", // 143
        "phase", // 144
        "plain", // 145
        "play", // 146
        "position2d", // 147
        "position3d", // 148
        "power", // 149
        "produced", // 150
        "publishes", // 151
        "radial", // 152
        "ratio", // 153
        "raw", // 154
        "rbg", // 155
        "reboot", // 156
        "red", // 157
        "remove", // 158
        "resource", // 159
        "result_end", // 160
        "rgb8", // 161
        "rgba16", // 162
        "runtime_buffer", // 163
        "runtime_buffer_resource", // 164
        "setLogLevel", // 165
        "setting", // 166
        "shader.f32", // 167
        "state", // 168
        "string", // 169
        "summary", // 170
        "target_occupied", // 171
        "text", // 172
        "texture", // 173
        "two_d", // 174
        "type_mismatch", // 175
        "u16", // 176
        "u32", // 177
        "u8", // 178
        "u_vec2", // 179
        "u_vec3", // 180
        "u_vec4", // 181
        "unknown_artifact", // 182
        "unknown_slot_path", // 183
        "unloadProject", // 184
        "unresolved", // 185
        "unset", // 186
        "unsupported", // 187
        "upsert", // 188
        "vec2", // 189
        "vec3", // 190
        "vec4", // 191
        "visual_product", // 192
        "xy", // 193
        "yellow", // 194
    ),
    offsets: &[
        0, 11, 16, 22, 27, 30, 36, 42, 46, 49, 52, 57, 60, 64, 69, 73,
        75, 78, 96, 100, 106, 115, 122, 126, 134, 139, 150, 160, 172, 182, 195, 205,
        216, 228, 243, 253, 269, 274, 281, 288, 294, 300, 306, 312, 325, 329, 342, 348,
        361, 373, 378, 383, 388, 392, 400, 407, 412, 416, 424, 434, 441, 449, 458, 463,
        470, 473, 484, 492, 501, 507, 513, 519, 522, 528, 532, 535, 542, 548, 554, 559,
        570, 575, 596, 604, 612, 627, 632, 637, 645, 652, 658, 665, 676, 686, 694, 705,
        710, 724, 729, 737, 746, 755, 760, 774, 787, 793, 802, 811, 814, 822, 830, 838,
        841, 844, 850, 856, 862, 865, 870, 877, 889, 901, 905, 911, 932, 937, 947, 953,
        959, 965, 973, 977, 993, 1002, 1014, 1021, 1026, 1041, 1056, 1062, 1067, 1079, 1087, 1091,
        1098, 1103, 1108, 1112, 1122, 1132, 1137, 1145, 1154, 1160, 1165, 1168, 1171, 1177, 1180, 1186,
        1194, 1204, 1208, 1214, 1228, 1251, 1262, 1269, 1279, 1284, 1290, 1297, 1312, 1316, 1323, 1328,
        1341, 1344, 1347, 1349, 1355, 1361, 1367, 1383, 1400, 1413, 1423, 1428, 1439, 1445, 1449, 1453,
        1457, 1471, 1473, 1479,
    ],
};

const KEY_HASH: &[u16] = &[
    0x011b, 0x0198, 0x017c, 0x019c, 0x0020, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0185, 0x00dc, 0x0015, 0xffff, 0xffff, 0xffff, 0xffff, 0x0056, 0xffff, 0x0070, 0xffff, 0xffff, 0xffff, 0x00eb, 0xffff, 0x00d7,
    0xffff, 0xffff, 0xffff, 0x0073, 0x01a9, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0062,
    0x018e, 0x00a1, 0xffff, 0xffff, 0x012f, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ba, 0x0017, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0x015a, 0xffff, 0x004c, 0x00e8, 0x015f, 0xffff, 0x017f, 0x0082, 0x018a, 0x0187, 0x0057, 0xffff, 0xffff, 0xffff, 0x0097,
    0xffff, 0xffff, 0x009c, 0x0181, 0xffff, 0x001b, 0xffff, 0xffff, 0xffff, 0x0037, 0x0008, 0xffff, 0x00f9, 0xffff, 0x00de, 0x00a2,
    0x0129, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0047, 0x0123, 0xffff, 0xffff, 0xffff, 0x004e, 0x004f, 0x006f, 0x0106, 0x010a,
    0x0152, 0x009b, 0x014f, 0x019d, 0xffff, 0x0030, 0x0126, 0x014e, 0x017b, 0xffff, 0xffff, 0x00f5, 0x0117, 0xffff, 0xffff, 0xffff,
    0xffff, 0x0135, 0xffff, 0xffff, 0x0124, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0019, 0xffff, 0xffff, 0xffff, 0x007a,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003d, 0x0188, 0xffff, 0x01af, 0x0059, 0x009d, 0xffff, 0xffff, 0x0002,
    0x0153, 0xffff, 0xffff, 0xffff, 0xffff, 0x012a, 0x0159, 0xffff, 0xffff, 0xffff, 0x007d, 0x00ac, 0x0156, 0xffff, 0xffff, 0x01b6,
    0xffff, 0x01ad, 0xffff, 0x00cf, 0xffff, 0xffff, 0xffff, 0x0095, 0xffff, 0xffff, 0xffff, 0x0085, 0x01b0, 0xffff, 0x0168, 0xffff,
    0x0096, 0xffff, 0x0142, 0x00f0, 0x0151, 0xffff, 0x016b, 0xffff, 0xffff, 0x00e1, 0x0071, 0x001a, 0x0157, 0x017a, 0xffff, 0x0012,
    0x0038, 0xffff, 0xffff, 0xffff, 0x015e, 0x00fd, 0xffff, 0x0104, 0xffff, 0x0143, 0x0115, 0xffff, 0xffff, 0xffff, 0x00bf, 0x006d,
    0xffff, 0xffff, 0x01b8, 0xffff, 0x0138, 0x0145, 0xffff, 0xffff, 0xffff, 0x0086, 0x0041, 0x0131, 0x001f, 0x0154, 0x019e, 0x010b,
    0xffff, 0x00d6, 0xffff, 0x0197, 0x01a4, 0x01a6, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x009f, 0x0078, 0xffff, 0x00ad,
    0x0088, 0x015c, 0xffff, 0x015b, 0x0050, 0x01b9, 0xffff, 0x00d8, 0xffff, 0x01a7, 0xffff, 0xffff, 0xffff, 0x0163, 0xffff, 0x0076,
    0xffff, 0x0174, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ca, 0x00e9, 0x00d1, 0x006b, 0x00ec, 0x0121, 0xffff, 0xffff, 0x0028, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0032, 0x00e4, 0x0180, 0xffff, 0xffff, 0x0022, 0x000b, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x005a, 0x010d, 0x0049, 0xffff, 0x00c4, 0x01a1, 0xffff, 0xffff, 0xffff, 0x00f3, 0xffff, 0x0035,
    0x00dd, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00a5, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x016f, 0x0139, 0x0125, 0xffff, 0x0114, 0xffff, 0xffff, 0x005f, 0x0176, 0xffff, 0xffff, 0x002b, 0x014a, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x012e, 0xffff, 0xffff, 0x00fa, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x0105, 0x008e, 0xffff, 0x00f2, 0xffff, 0xffff, 0xffff, 0x0044, 0xffff, 0x0068, 0x0025, 0x00c6, 0x0033, 0xffff,
    0x0170, 0xffff, 0x00be, 0xffff, 0x00b1, 0xffff, 0x007c, 0x0099, 0xffff, 0xffff, 0x0055, 0xffff, 0xffff, 0xffff, 0x0058, 0xffff,
    0xffff, 0x000f, 0x0111, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x01bb, 0xffff, 0x006e, 0xffff, 0x0069, 0x0046, 0x016d, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0031, 0x0079, 0xffff, 0xffff, 0x002e, 0x0003, 0x006c, 0xffff, 0x0029, 0x01b5,
    0xffff, 0x0010, 0x0045, 0x0196, 0xffff, 0x0100, 0xffff, 0x00fe, 0xffff, 0xffff, 0x014d, 0x0024, 0x00d5, 0xffff, 0xffff, 0x0060,
    0xffff, 0x0093, 0x0148, 0xffff, 0xffff, 0xffff, 0x0023, 0xffff, 0xffff, 0x0089, 0xffff, 0xffff, 0xffff, 0x01a5, 0x012c, 0x00ab,
    0x00db, 0x00d2, 0x0040, 0x0083, 0x0087, 0x00c3, 0x0101, 0x0155, 0x0092, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00bc, 0x0160,
    0x0067, 0xffff, 0x0165, 0x0006, 0x017d, 0x017e, 0x002d, 0x0141, 0x00cd, 0xffff, 0x0192, 0xffff, 0xffff, 0xffff, 0x0172, 0x00b7,
    0x0053, 0x00e6, 0xffff, 0xffff, 0x0052, 0x0021, 0xffff, 0x0081, 0x0150, 0x00a9, 0x00f6, 0x00d0, 0x00ee, 0x0127, 0x0166, 0x005d,
    0xffff, 0xffff, 0x00af, 0xffff, 0xffff, 0xffff, 0xffff, 0x01b1, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0005, 0x0094, 0x00c8,
    0x0137, 0x01a0, 0x01ba, 0xffff, 0xffff, 0xffff, 0x0177, 0x0193, 0x0000, 0x0091, 0x0179, 0x00da, 0x002a, 0xffff, 0xffff, 0x00d4,
    0x00bb, 0x00fb, 0x0132, 0x01a2, 0x0011, 0xffff, 0xffff, 0x0144, 0xffff, 0x00ae, 0x0162, 0xffff, 0xffff, 0x01ae, 0x007b, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c0, 0xffff, 0xffff, 0xffff, 0xffff, 0x0061, 0xffff, 0xffff, 0xffff, 0x00f8,
    0x0134, 0xffff, 0xffff, 0x0001, 0xffff, 0xffff, 0xffff, 0x0039, 0xffff, 0xffff, 0xffff, 0x006a, 0x00d9, 0xffff, 0x019b, 0x007f,
    0xffff, 0xffff, 0xffff, 0x00df, 0xffff, 0xffff, 0xffff, 0xffff, 0x00cc, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0140,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0149, 0x011f, 0xffff, 0x005c, 0xffff, 0x0182, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x001e, 0x01b7, 0xffff, 0xffff, 0x0112, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x000e, 0x00f4,
    0x016a, 0x01ac, 0xffff, 0xffff, 0xffff, 0x008b, 0xffff, 0x012d, 0x00e3, 0xffff, 0x00ea, 0x01bc, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00d3, 0x0098, 0xffff, 0xffff, 0x00a3, 0xffff, 0x014c, 0x009e, 0xffff,
    0x0199, 0xffff, 0xffff, 0x009a, 0x00c1, 0x0016, 0x00fc, 0xffff, 0x0054, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x011a, 0xffff, 0x00c7, 0xffff, 0x00b9, 0x00f7, 0x018b, 0xffff, 0xffff, 0x019a, 0xffff, 0x003a, 0x00b3, 0x0167, 0x0013, 0x003e,
    0xffff, 0xffff, 0xffff, 0xffff, 0x011c, 0x013a, 0x0113, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x003c, 0x01a8, 0x00bd, 0x0161, 0xffff, 0xffff, 0xffff, 0xffff, 0x0110, 0x0009, 0xffff, 0xffff, 0xffff, 0x0171, 0xffff, 0xffff,
    0x000c, 0x0036, 0xffff, 0x013b, 0xffff, 0x00e2, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x019f, 0x0184, 0x00b6, 0xffff,
    0xffff, 0xffff, 0x0128, 0x0074, 0x01b3, 0x0189, 0x0075, 0x013f, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x01ab, 0xffff, 0xffff,
    0xffff, 0x001c, 0x000d, 0xffff, 0x0007, 0x0064, 0x0065, 0xffff, 0xffff, 0x016e, 0xffff, 0xffff, 0x005b, 0xffff, 0xffff, 0x0122,
    0x0084, 0xffff, 0xffff, 0x01a3, 0xffff, 0x00e5, 0xffff, 0x00e0, 0x0178, 0x005e, 0xffff, 0xffff, 0x0066, 0xffff, 0xffff, 0xffff,
    0xffff, 0x018f, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0108, 0xffff, 0xffff,
    0x01b4, 0x018d, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c2, 0xffff, 0xffff, 0xffff, 0xffff, 0x018c, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0147, 0x013d, 0x00cb, 0x0120, 0x014b, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c5, 0xffff, 0xffff, 0xffff, 0x00b4, 0xffff,
    0xffff, 0x0077, 0xffff, 0xffff, 0xffff, 0xffff, 0x00e7, 0x0072, 0x00a8, 0x0042, 0x0146, 0xffff, 0x0080, 0xffff, 0x004b, 0xffff,
    0xffff, 0x012b, 0xffff, 0xffff, 0xffff, 0x004a, 0xffff, 0xffff, 0xffff, 0x010c, 0x010e, 0xffff, 0xffff, 0x00c9, 0x0027, 0x0130,
    0xffff, 0x007e, 0xffff, 0xffff, 0xffff, 0xffff, 0x0014, 0xffff, 0xffff, 0xffff, 0xffff, 0x008d, 0xffff, 0xffff, 0x0118, 0x011e,
    0x0194, 0x0190, 0xffff, 0xffff, 0x002f, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ce, 0xffff, 0x0090, 0x001d, 0x0026, 0xffff, 0x0102,
    0xffff, 0x008a, 0xffff, 0x0119, 0x0158, 0xffff, 0xffff, 0xffff, 0x0018, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0034, 0x0063,
    0x0116, 0xffff, 0xffff, 0xffff, 0xffff, 0x0164, 0xffff, 0xffff, 0x00a4, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0169, 0x00b8, 0x013e, 0xffff, 0x00a7, 0x011d, 0x0173, 0xffff, 0xffff, 0x015d, 0x003f, 0x01b2, 0x0048, 0x0195, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0175, 0x003b, 0xffff, 0xffff, 0x00ff, 0x0004, 0x008f, 0x00a6, 0x013c, 0x0103, 0xffff,
    0xffff, 0x00aa, 0xffff, 0x002c, 0xffff, 0x00ed, 0x0136, 0x0051, 0xffff, 0x016c, 0xffff, 0x0183, 0xffff, 0x000a, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0043, 0x01aa, 0xffff, 0x00f1, 0xffff, 0xffff, 0x004d, 0x00b5, 0x0191, 0xffff, 0xffff, 0x008c,
    0x00b0, 0x0107, 0x010f, 0x0186, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b2, 0x00ef, 0x0109, 0x0133, 0x00a0,
];

const VALUE_HASH: &[u16] = &[
    0x000c, 0x006a, 0xffff, 0xffff, 0xffff, 0xffff, 0x000d, 0x0012, 0x002d, 0xffff, 0x00b9, 0xffff, 0x00a1, 0x0094, 0x0011, 0xffff,
    0xffff, 0x0038, 0x00c0, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003e, 0xffff, 0xffff, 0xffff, 0x00b7, 0x0045, 0xffff, 0xffff,
    0xffff, 0xffff, 0x004e, 0xffff, 0xffff, 0x0034, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b3, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0053, 0xffff, 0xffff, 0xffff, 0x006b, 0xffff, 0x000e, 0xffff, 0x00ac, 0xffff,
    0xffff, 0x0088, 0xffff, 0x0079, 0xffff, 0x002c, 0x007a, 0x008b, 0xffff, 0x00c2, 0x0059, 0xffff, 0xffff, 0x0040, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00ae, 0x003a, 0xffff, 0xffff, 0x004d, 0xffff, 0x0050, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x007f,
    0x0085, 0xffff, 0xffff, 0x0092, 0xffff, 0xffff, 0xffff, 0xffff, 0x0020, 0xffff, 0x005a, 0xffff, 0xffff, 0x0022, 0x0077, 0x0098,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0030, 0x00bd, 0xffff, 0xffff, 0xffff, 0x0051, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0099, 0xffff, 0xffff, 0x0073, 0x0029, 0x00a4, 0x0044, 0x0062, 0x0089, 0xffff, 0x0021, 0xffff,
    0xffff, 0x002e, 0xffff, 0xffff, 0x0002, 0xffff, 0x004a, 0x0003, 0x0043, 0x0014, 0x00b4, 0x005e, 0x0087, 0xffff, 0xffff, 0x001c,
    0x0068, 0xffff, 0x003d, 0xffff, 0xffff, 0x006e, 0x0070, 0xffff, 0xffff, 0x001a, 0xffff, 0x0018, 0xffff, 0xffff, 0xffff, 0xffff,
    0x005c, 0x00b1, 0xffff, 0x0057, 0xffff, 0xffff, 0x009b, 0x00a3, 0xffff, 0xffff, 0xffff, 0x00b5, 0x000a, 0x0027, 0x0047, 0xffff,
    0xffff, 0xffff, 0xffff, 0x0060, 0x0010, 0xffff, 0xffff, 0xffff, 0x00b6, 0xffff, 0xffff, 0xffff, 0x0006, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x0026, 0xffff, 0xffff, 0xffff, 0xffff, 0x0042, 0xffff, 0xffff, 0xffff, 0xffff, 0x009d, 0xffff, 0xffff, 0x0023,
    0x001e, 0x008a, 0x00be, 0xffff, 0xffff, 0x005b, 0xffff, 0xffff, 0xffff, 0xffff, 0x0069, 0xffff, 0xffff, 0xffff, 0x005f, 0xffff,
    0xffff, 0x0032, 0x009a, 0x00a5, 0x00ad, 0x00b8, 0x00a8, 0x007e, 0x00b2, 0xffff, 0xffff, 0xffff, 0x0048, 0x0024, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0x00bf, 0xffff, 0xffff, 0x00a0, 0xffff, 0x007c, 0xffff, 0xffff, 0xffff, 0xffff, 0x005d, 0xffff, 0x0066,
    0xffff, 0xffff, 0xffff, 0x0033, 0x00aa, 0xffff, 0xffff, 0xffff, 0x0046, 0x004c, 0x008d, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b0,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0028, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x00bb, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x008e, 0x0081, 0x0031, 0x00a9, 0xffff, 0xffff, 0x008f, 0x0049, 0xffff, 0xffff,
    0x0039, 0x008c, 0xffff, 0xffff, 0xffff, 0xffff, 0x0095, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x001b, 0x0037,
    0xffff, 0x0061, 0xffff, 0x002f, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0086, 0xffff, 0x0025, 0x003b, 0xffff, 0xffff, 0xffff,
    0x0041, 0x002b, 0x0071, 0xffff, 0xffff, 0xffff, 0xffff, 0x0091, 0xffff, 0x0074, 0xffff, 0xffff, 0xffff, 0x0063, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x007d, 0xffff, 0x0013, 0x00ba, 0xffff, 0x0009, 0x00a2, 0x0078, 0x00a7,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003c, 0xffff, 0xffff, 0x0035, 0xffff, 0x0019, 0xffff, 0x0017,
    0x004b, 0x0016, 0xffff, 0x006c, 0x0005, 0x0036, 0xffff, 0xffff, 0x0056, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0015, 0xffff,
    0xffff, 0xffff, 0x00bc, 0xffff, 0x0093, 0xffff, 0xffff, 0x006d, 0xffff, 0xffff, 0x0004, 0x00a6, 0x00af, 0xffff, 0x0000, 0xffff,
    0xffff, 0x000b, 0x0076, 0xffff, 0xffff, 0xffff, 0xffff, 0x001d, 0x004f, 0x009c, 0x00ab, 0x0067, 0xffff, 0xffff, 0xffff, 0x0052,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0008, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0001, 0xffff, 0xffff, 0xffff, 0x0072, 0x000f,
    0xffff, 0x0084, 0x0096, 0xffff, 0xffff, 0xffff, 0x007b, 0xffff, 0xffff, 0xffff, 0x0064, 0x006f, 0x001f, 0x0082, 0x0058, 0x00c1,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0007, 0x002a, 0xffff, 0x0080, 0xffff, 0x003f, 0x0054, 0x0083, 0x0097, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0055, 0x009f, 0xffff, 0xffff, 0x0090, 0x0065, 0x0075, 0xffff, 0xffff, 0x009e, 0xffff, 0xffff,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_well_formed_and_match_their_fingerprint() {
        assert_eq!(WIRE_DICTIONARY.check(), Ok(()));
        assert_eq!(WIRE_DICTIONARY.fingerprint(), WIRE_DICTIONARY_FINGERPRINT);
    }
}
