//! The wire's JSON Pack dictionary: what a packed frame is coded against.
//!
//! GENERATED by `just wire-dict`
//! (`cargo run -p lpc-wire --features wire-dict-gen --bin wire-dict`). Do not
//! edit: `just wire-dict-check` (in `check-lint`) fails when this file is not
//! what the generator writes, and when the dictionary changed without a
//! `WIRE_PROTO_VERSION` bump.
//!
//! - Keys: every struct field name and every data-carrying enum variant name
//!   reachable from `WireServerMessage` and `ClientMessage`, found by tracing
//!   their `Deserialize` impls (`wire_dictionary_gen`).
//! - Values: every unit variant name.
//! - Both: the keys and string tags of the slot text codec
//!   (`lpc-model`'s `slot_sync_codec` / `slot_codec` writers), which writes
//!   `WireSlotData`'s pre-serialized JSON.
//! - Order: by frequency in the committed traffic sample
//!   (`lp-base/lp-json-pack/tests/fixtures/choker-lens-sample.txt`),
//!   then by name. The commonest get the one-byte codes.
//!
//! 437 keys (214 ranked by the sample), 191 values (46 ranked); 9407 bytes
//! of statics.

use lp_json_pack::{Dictionary, PackStrings};

/// The `WIRE_PROTO_VERSION` this dictionary was generated at.
pub const WIRE_DICTIONARY_PROTO: u32 = 26;

/// [`WIRE_DICTIONARY`]'s `fingerprint()`, as generated.
pub const WIRE_DICTIONARY_FINGERPRINT: u32 = 0x28ec2da6;

/// The wire's dictionary.
pub static WIRE_DICTIONARY: Dictionary = Dictionary {
    keys: KEYS,
    values: VALUES,
    key_hash: KEY_HASH,
    value_hash: VALUE_HASH,
};

const KEYS: PackStrings = PackStrings {
    text: concat!(
        "revision", // 0
        "kind", // 1
        "event", // 2
        "index", // 3
        "value", // 4
        "node", // 5
        "query", // 6
        "output", // 7
        "nodes", // 8
        "changed_at", // 9
        "level", // 10
        "product", // 11
        "id", // 12
        "msg", // 13
        "begin", // 14
        "geometry", // 15
        "probe", // 16
        "result", // 17
        "shapes", // 18
        "unchanged", // 19
        "projectRead", // 20
        "output_frame", // 21
        "data", // 22
        "values", // 23
        "rows", // 24
        "samples_per_row", // 25
        "sample_format", // 26
        "outputs", // 27
        "if_changed", // 28
        "known", // 29
        "presence_revision", // 30
        "present", // 31
        "bytes", // 32
        "binding_graph", // 33
        "runtime", // 34
        "structure", // 35
        "preferred_extent", // 36
        "fields", // 37
        "fields_revision", // 38
        "freeBytes", // 39
        "largestFreeBlock", // 40
        "memory", // 41
        "totalBytes", // 42
        "usedBytes", // 43
        "handle", // 44
        "name", // 45
        "end", // 46
        "events", // 47
        "channels", // 48
        "frame", // 49
        "shape", // 50
        "slot_root", // 51
        "control", // 52
        "demand_root_count", // 53
        "frame_delta_ms", // 54
        "frame_num", // 55
        "frame_total_ms", // 56
        "graph", // 57
        "ids_revision", // 58
        "last_frame_time_us", // 59
        "overlay_changed_at", // 60
        "panel_auto_save", // 61
        "project", // 62
        "runtime_buffer_count", // 63
        "server", // 64
        "structure_revision", // 65
        "theoretical_fps", // 66
        "time", // 67
        "visual", // 68
        "request", // 69
        "since", // 70
        "probes", // 71
        "samples", // 72
        "path", // 73
        "include_slots", // 74
        "include_values", // 75
        "queries", // 76
        "control_product", // 77
        "baseMac", // 78
        "avg", // 79
        "bootCount", // 80
        "color_order", // 81
        "count", // 82
        "encoding", // 83
        "fps", // 84
        "frame_count", // 85
        "heartbeat", // 86
        "hostDrainingAgainMs", // 87
        "hostNotDrainingMs", // 88
        "identity", // 89
        "lastCrash", // 90
        "len", // 91
        "link", // 92
        "loaded_projects", // 93
        "max", // 94
        "min", // 95
        "notDrainingCount", // 96
        "outputClamp", // 97
        "parseFailures", // 98
        "paths", // 99
        "queueFullDrops", // 100
        "recovery", // 101
        "resetReason", // 102
        "rgb_pixels", // 103
        "row", // 104
        "rxErrors", // 105
        "safeMode", // 106
        "sdev", // 107
        "stalePartialFlushes", // 108
        "start", // 109
        "uptime_ms", // 110
        "key", // 111
        "extent", // 112
        "filesystem", // 113
        "preview", // 114
        "artifact", // 115
        "entries", // 116
        "state", // 117
        "keys_revision", // 118
        "error", // 119
        "parent", // 120
        "location", // 121
        "segments", // 122
        "ty", // 123
        "variant", // 124
        "variant_revision", // 125
        "slot", // 126
        "origin", // 127
        "write", // 128
        "change_frame", // 129
        "child_kind", // 130
        "children", // 131
        "children_ver", // 132
        "created", // 133
        "created_frame", // 134
        "def_location", // 135
        "loaded", // 136
        "prefix", // 137
        "runtime_id", // 138
        "space", // 139
        "status", // 140
        "input", // 141
        "invocation", // 142
        "offset", // 143
        "project_child", // 144
        "role", // 145
        "source", // 146
        "writeChunk", // 147
        "listLoadedProjects", // 148
        "projects", // 149
        "written", // 150
        "auth", // 151
        "available", // 152
        "boardId", // 153
        "build", // 154
        "button", // 155
        "c", // 156
        "changed", // 157
        "chipRevision", // 158
        "commit", // 159
        "content_type", // 160
        "deleteDir", // 161
        "deviceUid", // 162
        "dirty", // 163
        "display_layout", // 164
        "eui64", // 165
        "features", // 166
        "granted", // 167
        "h", // 168
        "hardware", // 169
        "hash", // 170
        "hashPackage", // 171
        "hello", // 172
        "layout", // 173
        "layout2d", // 174
        "loadProject", // 175
        "p", // 176
        "packDictionary", // 177
        "package", // 178
        "packageHash", // 179
        "period_seconds", // 180
        "phase_offset", // 181
        "profile", // 182
        "projectCommand", // 183
        "proto", // 184
        "radio", // 185
        "read_inventory", // 186
        "required", // 187
        "response", // 188
        "rev", // 189
        "s", // 190
        "sample_layout", // 191
        "spans", // 192
        "totalLedBudget", // 193
        "w", // 194
        "waveform", // 195
        "assets", // 196
        "changes", // 197
        "changesSince", // 198
        "command", // 199
        "cursor", // 200
        "defs", // 201
        "deltas", // 202
        "height", // 203
        "lamps", // 204
        "next", // 205
        "placements", // 206
        "reversed", // 207
        "source_lamp", // 208
        "source_lamps", // 209
        "tree_deltas", // 210
        "version", // 211
        "width", // 212
        "wire_lamp", // 213
        "Error", // 214
        "Fault", // 215
        "Field", // 216
        "Index", // 217
        "InitError", // 218
        "Unsupported", // 219
        "Warn", // 220
        "accepted", // 221
        "added", // 222
        "array", // 223
        "artifact_changes", // 224
        "artifacts", // 225
        "assign_value", // 226
        "attach", // 227
        "availability", // 228
        "b_vec2", // 229
        "b_vec3", // 230
        "b_vec4", // 231
        "base_display", // 232
        "base_values", // 233
        "batch", // 234
        "bindings", // 235
        "body", // 236
        "bool", // 237
        "bootsAgo", // 238
        "buffer", // 239
        "bus", // 240
        "by_ids", // 241
        "by_refs", // 242
        "byte_length", // 243
        "byte_length_hint", // 244
        "cause", // 245
        "channel", // 246
        "children_changed", // 247
        "clearFaults", // 248
        "clear_artifact", // 249
        "codec", // 250
        "commands", // 251
        "commit_overlay", // 252
        "consumers", // 253
        "crashCount", // 254
        "create_node", // 255
        "custom", // 256
        "cycle", // 257
        "default_1d_to_2d", // 258
        "default_bind", // 259
        "deleteFile", // 260
        "delta_seconds", // 261
        "description", // 262
        "dictionary", // 263
        "direction", // 264
        "domain", // 265
        "dropdown", // 266
        "edit", // 267
        "editor", // 268
        "edits", // 269
        "effect", // 270
        "elem", // 271
        "enabled", // 272
        "endpoint", // 273
        "engaged", // 274
        "entry", // 275
        "entry_changed", // 276
        "enum", // 277
        "f32", // 278
        "failed", // 279
        "fault", // 280
        "field", // 281
        "file", // 282
        "fin", // 283
        "fixture_colors", // 284
        "flip", // 285
        "force", // 286
        "format", // 287
        "from", // 288
        "gpio", // 289
        "gpu_resident", // 290
        "header", // 291
        "i32", // 292
        "i_vec2", // 293
        "i_vec3", // 294
        "i_vec4", // 295
        "ids", // 296
        "inline", // 297
        "iterations", // 298
        "knob", // 299
        "label", // 300
        "ledger_cleared", // 301
        "list", // 302
        "listAvailableProjects", // 303
        "listDir", // 304
        "literal", // 305
        "log", // 306
        "loginAnswer", // 307
        "loginChallenge", // 308
        "loginResult", // 309
        "macs", // 310
        "map", // 311
        "mat2x2", // 312
        "mat3x3", // 313
        "mat4x4", // 314
        "materialized", // 315
        "membership", // 316
        "merge", // 317
        "message", // 318
        "meta", // 319
        "metadata", // 320
        "mirror", // 321
        "move_slot_entry", // 322
        "mutate_overlay", // 323
        "mutation", // 324
        "mux", // 325
        "needs", // 326
        "node_command", // 327
        "node_slot", // 328
        "nonce", // 329
        "normalized_to_removal", // 330
        "notPermitted", // 331
        "number", // 332
        "offers", // 333
        "oomRetrySaves", // 334
        "op", // 335
        "option", // 336
        "options", // 337
        "output_channels", // 338
        "overlay", // 339
        "overlay_changed", // 340
        "overlay_revision", // 341
        "owner", // 342
        "panel", // 343
        "panel_clear", // 344
        "panel_show", // 345
        "panel_write", // 346
        "parse_error", // 347
        "payload", // 348
        "payloads", // 349
        "phase", // 350
        "phasors", // 351
        "playlist_activate_entry", // 352
        "playlist_entry", // 353
        "policy", // 354
        "posted", // 355
        "primary", // 356
        "primary_visual", // 357
        "priority", // 358
        "project_nodes", // 359
        "projection", // 360
        "providers", // 361
        "put", // 362
        "put_slot_edit", // 363
        "queueWaitMaxUs", // 364
        "read", // 365
        "read_error", // 366
        "read_overlay", // 367
        "readings", // 368
        "reason", // 369
        "record", // 370
        "recursive", // 371
        "ref", // 372
        "refs", // 373
        "refused", // 374
        "rejected", // 375
        "rejection", // 376
        "remove_node", // 377
        "remove_slot_edit", // 378
        "removed", // 379
        "render_product", // 380
        "replace_body", // 381
        "resources", // 382
        "result_begin", // 383
        "result_bytes", // 384
        "results", // 385
        "retryAfterMs", // 386
        "runtime_buffer", // 387
        "runtime_buffer_payload", // 388
        "runtime_buffer_payload_begin", // 389
        "runtime_buffer_payload_bytes", // 390
        "runtime_buffer_payload_end", // 391
        "salt", // 392
        "scope", // 393
        "seconds", // 394
        "semantics", // 395
        "sent", // 396
        "seq", // 397
        "setEncoding", // 398
        "setLogLevel", // 399
        "set_artifact_body", // 400
        "sidecar", // 401
        "sinceMs", // 402
        "site", // 403
        "slider", // 404
        "some", // 405
        "staged", // 406
        "staged_deletes", // 407
        "step", // 408
        "string", // 409
        "struct", // 410
        "summary", // 411
        "swept_pending_edits", // 412
        "tagged", // 413
        "texture", // 414
        "tier", // 415
        "timebase", // 416
        "to", // 417
        "torn", // 418
        "total", // 419
        "ttl_ms", // 420
        "u32", // 421
        "u_vec2", // 422
        "u_vec3", // 423
        "u_vec4", // 424
        "unit", // 425
        "unknown", // 426
        "unloadProject", // 427
        "unsupported", // 428
        "validation_error", // 429
        "variants", // 430
        "vec2", // 431
        "vec3", // 432
        "vec4", // 433
        "waved", // 434
        "wire", // 435
        "words", // 436
    ),
    offsets: &[
        0, 8, 12, 17, 22, 27, 31, 36, 42, 47, 57, 62, 69, 71, 74, 79,
        87, 92, 98, 104, 113, 124, 136, 140, 146, 150, 165, 178, 185, 195, 200, 217,
        224, 229, 242, 249, 258, 274, 280, 295, 304, 320, 326, 336, 345, 351, 355, 358,
        364, 372, 377, 382, 391, 398, 415, 429, 438, 452, 457, 469, 487, 505, 520, 527,
        547, 553, 571, 586, 590, 596, 603, 608, 614, 621, 625, 638, 652, 659, 674, 681,
        684, 693, 704, 709, 717, 720, 731, 740, 759, 776, 784, 793, 796, 800, 815, 818,
        821, 837, 848, 861, 866, 880, 888, 899, 909, 912, 920, 928, 932, 951, 956, 965,
        968, 974, 984, 991, 999, 1006, 1011, 1024, 1029, 1035, 1043, 1051, 1053, 1060, 1076, 1080,
        1086, 1091, 1103, 1113, 1121, 1133, 1140, 1153, 1165, 1171, 1177, 1187, 1192, 1198, 1203, 1213,
        1219, 1232, 1236, 1242, 1252, 1270, 1278, 1285, 1289, 1298, 1305, 1310, 1316, 1317, 1324, 1336,
        1342, 1354, 1363, 1372, 1377, 1391, 1396, 1404, 1411, 1412, 1420, 1424, 1435, 1440, 1446, 1454,
        1465, 1466, 1480, 1487, 1498, 1512, 1524, 1531, 1545, 1550, 1555, 1569, 1577, 1585, 1588, 1589,
        1602, 1607, 1621, 1622, 1630, 1636, 1643, 1655, 1662, 1668, 1672, 1678, 1684, 1689, 1693, 1703,
        1711, 1722, 1734, 1745, 1752, 1757, 1766, 1771, 1776, 1781, 1786, 1795, 1806, 1810, 1818, 1823,
        1828, 1844, 1853, 1865, 1871, 1883, 1889, 1895, 1901, 1913, 1924, 1929, 1937, 1941, 1945, 1953,
        1959, 1962, 1968, 1975, 1986, 2002, 2007, 2014, 2030, 2041, 2055, 2060, 2068, 2082, 2091, 2101,
        2112, 2118, 2123, 2139, 2151, 2161, 2174, 2185, 2195, 2204, 2210, 2218, 2222, 2228, 2233, 2239,
        2243, 2250, 2258, 2265, 2270, 2283, 2287, 2290, 2296, 2301, 2306, 2310, 2313, 2327, 2331, 2336,
        2342, 2346, 2350, 2362, 2368, 2371, 2377, 2383, 2389, 2392, 2398, 2408, 2412, 2417, 2431, 2435,
        2456, 2463, 2470, 2473, 2484, 2498, 2509, 2513, 2516, 2522, 2528, 2534, 2546, 2556, 2561, 2568,
        2572, 2580, 2586, 2601, 2615, 2623, 2626, 2631, 2643, 2652, 2657, 2678, 2690, 2696, 2702, 2715,
        2717, 2723, 2730, 2745, 2752, 2767, 2783, 2788, 2793, 2804, 2814, 2825, 2836, 2843, 2851, 2856,
        2863, 2886, 2900, 2906, 2912, 2919, 2933, 2941, 2954, 2964, 2973, 2976, 2989, 3003, 3007, 3017,
        3029, 3037, 3043, 3049, 3058, 3061, 3065, 3072, 3080, 3089, 3100, 3116, 3123, 3137, 3149, 3158,
        3170, 3182, 3189, 3201, 3215, 3237, 3265, 3293, 3319, 3323, 3328, 3335, 3344, 3348, 3351, 3362,
        3373, 3390, 3397, 3404, 3408, 3414, 3418, 3424, 3438, 3442, 3448, 3454, 3461, 3480, 3486, 3493,
        3497, 3505, 3507, 3511, 3516, 3522, 3525, 3531, 3537, 3543, 3547, 3554, 3567, 3578, 3594, 3602,
        3606, 3610, 3614, 3619, 3623, 3628,
    ],
};

const VALUES: PackStrings = PackStrings {
    text: concat!(
        "no_provider", // 0
        "value", // 1
        "detail", // 2
        "srgb8", // 3
        "end", // 4
        "option", // 5
        "record", // 6
        "time", // 7
        "all", // 8
        "rgb", // 9
        "green", // 10
        "map", // 11
        "enum", // 12
        "alive", // 13
        "show", // 14
        "Ok", // 15
        "f32", // 16
        "listLoadedProjects", // 17
        "unit", // 18
        "visual", // 19
        "committed", // 20
        "control", // 21
        "edit", // 22
        "gfx.lpvm", // 23
        "hello", // 24
        "node.button", // 25
        "node.clock", // 26
        "node.fixture", // 27
        "node.fluid", // 28
        "node.playlist", // 29
        "node.radio", // 30
        "node.shader", // 31
        "node.texture", // 32
        "stopAllProjects", // 33
        "svc.button", // 34
        "svc.radio-espnow", // 35
        "Clock", // 36
        "Created", // 37
        "Fixture", // 38
        "Module", // 39
        "Output", // 40
        "Shader", // 41
        "always", // 42
        "fixture_map2d", // 43
        "root", // 44
        "shader_source", // 45
        "Button", // 46
        "ComputeShader", // 47
        "ControlRadio", // 48
        "Debug", // 49
        "Error", // 50
        "Fluid", // 51
        "Info", // 52
        "Playlist", // 53
        "Texture", // 54
        "Trace", // 55
        "Warn", // 56
        "accepted", // 57
        "affine2d", // 58
        "amplitude", // 59
        "angle", // 60
        "angular", // 61
        "any", // 62
        "audio_level", // 63
        "authored", // 64
        "available", // 65
        "b_vec2", // 66
        "b_vec3", // 67
        "b_vec4", // 68
        "bgr", // 69
        "binary", // 70
        "bool", // 71
        "brg", // 72
        "by_key", // 73
        "choice", // 74
        "clear", // 75
        "clearFaults", // 76
        "color", // 77
        "compute_shader_source", // 78
        "consumed", // 79
        "consumes", // 80
        "control_product", // 81
        "count", // 82
        "debug", // 83
        "declared", // 84
        "default", // 85
        "delete", // 86
        "deleted", // 87
        "diag.unwind", // 88
        "dimensions", // 89
        "duration", // 90
        "edit_failed", // 91
        "empty", // 92
        "ensure_present", // 93
        "error", // 94
        "external", // 95
        "extrude_x", // 96
        "extrude_y", // 97
        "fixed", // 98
        "fixture_colors", // 99
        "fixture_patch", // 100
        "forced", // 101
        "fragments", // 102
        "frequency", // 103
        "gbr", // 104
        "gfx.null", // 105
        "gfx.wgpu", // 106
        "gradient", // 107
        "grb", // 108
        "i32", // 109
        "i_vec2", // 110
        "i_vec3", // 111
        "i_vec4", // 112
        "ids", // 113
        "image", // 114
        "instant", // 115
        "invalid_body", // 116
        "invalid_path", // 117
        "json", // 118
        "latest", // 119
        "listAvailableProjects", // 120
        "local", // 121
        "loginBegin", // 122
        "mat2x2", // 123
        "mat3x3", // 124
        "mat4x4", // 125
        "node_ref", // 126
        "none", // 127
        "not_a_value_leaf", // 128
        "not_found", // 129
        "not_writable", // 130
        "omitted", // 131
        "one_d", // 132
        "output_channels", // 133
        "overlay_replace", // 134
        "packed", // 135
        "panel", // 136
        "panel_writer", // 137
        "path", // 138
        "pending", // 139
        "phase", // 140
        "plain", // 141
        "play", // 142
        "position2d", // 143
        "position3d", // 144
        "power", // 145
        "produced", // 146
        "publishes", // 147
        "radial", // 148
        "ratio", // 149
        "raw", // 150
        "rbg", // 151
        "reboot", // 152
        "red", // 153
        "remove", // 154
        "resource", // 155
        "result_end", // 156
        "rgb8", // 157
        "rgba16", // 158
        "runtime_buffer", // 159
        "runtime_buffer_resource", // 160
        "setLogLevel", // 161
        "setting", // 162
        "shader.f32", // 163
        "state", // 164
        "string", // 165
        "summary", // 166
        "target_occupied", // 167
        "text", // 168
        "texture", // 169
        "two_d", // 170
        "type_mismatch", // 171
        "u16", // 172
        "u32", // 173
        "u8", // 174
        "u_vec2", // 175
        "u_vec3", // 176
        "u_vec4", // 177
        "unknown_artifact", // 178
        "unknown_slot_path", // 179
        "unloadProject", // 180
        "unresolved", // 181
        "unset", // 182
        "unsupported", // 183
        "upsert", // 184
        "vec2", // 185
        "vec3", // 186
        "vec4", // 187
        "visual_product", // 188
        "xy", // 189
        "yellow", // 190
    ),
    offsets: &[
        0, 11, 16, 22, 27, 30, 36, 42, 46, 49, 52, 57, 60, 64, 69, 73,
        75, 78, 96, 100, 106, 115, 122, 126, 134, 139, 150, 160, 172, 182, 195, 205,
        216, 228, 243, 253, 269, 274, 281, 288, 294, 300, 306, 312, 325, 329, 342, 348,
        361, 373, 378, 383, 388, 392, 400, 407, 412, 416, 424, 432, 441, 446, 453, 456,
        467, 475, 484, 490, 496, 502, 505, 511, 515, 518, 524, 530, 535, 546, 551, 572,
        580, 588, 603, 608, 613, 621, 628, 634, 641, 652, 662, 670, 681, 686, 700, 705,
        713, 722, 731, 736, 750, 763, 769, 778, 787, 790, 798, 806, 814, 817, 820, 826,
        832, 838, 841, 846, 853, 865, 877, 881, 887, 908, 913, 923, 929, 935, 941, 949,
        953, 969, 978, 990, 997, 1002, 1017, 1032, 1038, 1043, 1055, 1059, 1066, 1071, 1076, 1080,
        1090, 1100, 1105, 1113, 1122, 1128, 1133, 1136, 1139, 1145, 1148, 1154, 1162, 1172, 1176, 1182,
        1196, 1219, 1230, 1237, 1247, 1252, 1258, 1265, 1280, 1284, 1291, 1296, 1309, 1312, 1315, 1317,
        1323, 1329, 1335, 1351, 1368, 1381, 1391, 1396, 1407, 1413, 1417, 1421, 1425, 1439, 1441, 1447,
    ],
};

const KEY_HASH: &[u16] = &[
    0x0115, 0x0190, 0x0174, 0x0194, 0x0020, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x017d, 0x00dc, 0x0015, 0xffff, 0xffff, 0xffff, 0xffff, 0x0056, 0xffff, 0x0070, 0xffff, 0xffff, 0xffff, 0x00e6, 0xffff, 0x00d7,
    0xffff, 0xffff, 0xffff, 0x0073, 0x01a1, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0062,
    0x0186, 0x00a1, 0xffff, 0xffff, 0x0129, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ba, 0x0017, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0x0152, 0xffff, 0x004c, 0x00e3, 0x0157, 0xffff, 0x0177, 0x0082, 0x0182, 0x017f, 0x0057, 0xffff, 0xffff, 0xffff, 0x0097,
    0xffff, 0xffff, 0x009c, 0x0179, 0xffff, 0x001b, 0xffff, 0xffff, 0xffff, 0x0037, 0x0008, 0xffff, 0x00f3, 0xffff, 0xffff, 0x00a2,
    0x0123, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0047, 0x011d, 0xffff, 0xffff, 0xffff, 0x004e, 0x004f, 0x006f, 0x0100, 0x0104,
    0x014b, 0x009b, 0x0148, 0x0195, 0xffff, 0x0030, 0x0120, 0x0147, 0x0173, 0xffff, 0xffff, 0x00ef, 0x0111, 0xffff, 0xffff, 0xffff,
    0xffff, 0x012e, 0xffff, 0xffff, 0x011e, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0019, 0xffff, 0xffff, 0xffff, 0x007a,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003d, 0x0180, 0xffff, 0x01a7, 0x0059, 0x009d, 0xffff, 0xffff, 0x0002,
    0x014c, 0xffff, 0xffff, 0xffff, 0xffff, 0x0124, 0x0151, 0xffff, 0xffff, 0xffff, 0x007d, 0x00ac, 0x014f, 0xffff, 0xffff, 0x01ae,
    0xffff, 0x01a5, 0xffff, 0x00cf, 0xffff, 0xffff, 0xffff, 0x0095, 0xffff, 0xffff, 0xffff, 0x0085, 0x01a8, 0xffff, 0x0160, 0xffff,
    0x0096, 0xffff, 0x013b, 0x00eb, 0x014a, 0xffff, 0x0163, 0xffff, 0xffff, 0xffff, 0x0071, 0x001a, 0x0172, 0xffff, 0xffff, 0x0012,
    0x0038, 0xffff, 0xffff, 0xffff, 0x0156, 0x00f7, 0xffff, 0x00fe, 0xffff, 0x013c, 0x010f, 0xffff, 0xffff, 0xffff, 0x00bf, 0x006d,
    0xffff, 0xffff, 0x01b0, 0xffff, 0x0131, 0x013e, 0xffff, 0xffff, 0xffff, 0x0086, 0x0041, 0x014d, 0x001f, 0x0196, 0xffff, 0x0105,
    0xffff, 0x00d6, 0xffff, 0x018f, 0x019c, 0x019e, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x009f, 0x0078, 0xffff, 0x00ad,
    0x0088, 0x0154, 0xffff, 0x0153, 0x0050, 0x01b1, 0xffff, 0x00d8, 0xffff, 0x019f, 0xffff, 0xffff, 0xffff, 0x015b, 0xffff, 0x0076,
    0xffff, 0x016c, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ca, 0x00e4, 0x00d1, 0x006b, 0x00e7, 0x011b, 0xffff, 0xffff, 0x0028, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0032, 0x00df, 0x0178, 0xffff, 0xffff, 0x0022, 0x000b, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x005a, 0x0107, 0x0049, 0xffff, 0x00c4, 0x0199, 0xffff, 0xffff, 0xffff, 0x00ed, 0xffff, 0x0035,
    0x00dd, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00a5, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0167, 0x0132, 0x011f, 0xffff, 0x010e, 0xffff, 0xffff, 0x005f, 0x016e, 0xffff, 0xffff, 0x002b, 0x0143, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0128, 0xffff, 0xffff, 0x00f4, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00ff, 0x008e, 0xffff, 0x00ec, 0xffff, 0xffff, 0xffff, 0x0044, 0xffff, 0x0068, 0x0025, 0x00c6, 0x0033, 0xffff,
    0x0168, 0xffff, 0x00be, 0xffff, 0x00b1, 0xffff, 0x007c, 0x0099, 0xffff, 0xffff, 0x0055, 0xffff, 0xffff, 0xffff, 0x0058, 0xffff,
    0xffff, 0x000f, 0x010b, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x01b3, 0xffff, 0x006e, 0xffff, 0x0069, 0x0046, 0x0165, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0031, 0x0079, 0xffff, 0xffff, 0x002e, 0x0003, 0x006c, 0xffff, 0x0029, 0x01ad,
    0xffff, 0x0010, 0x0045, 0x018e, 0xffff, 0x00fa, 0xffff, 0x00f8, 0xffff, 0xffff, 0x0146, 0x0024, 0x00d5, 0xffff, 0xffff, 0x0060,
    0xffff, 0x0093, 0x0141, 0xffff, 0xffff, 0xffff, 0x0023, 0xffff, 0xffff, 0x0089, 0xffff, 0xffff, 0xffff, 0x019d, 0x0126, 0x00ab,
    0x00db, 0x00d2, 0x0040, 0x0083, 0x0087, 0x00c3, 0x00fb, 0x014e, 0x0092, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00bc, 0x0158,
    0x0067, 0xffff, 0x015d, 0x0006, 0x0175, 0x0176, 0x002d, 0x013a, 0x00cd, 0xffff, 0x018a, 0xffff, 0xffff, 0xffff, 0x016a, 0x00b7,
    0x0053, 0x00e1, 0xffff, 0xffff, 0x0052, 0x0021, 0xffff, 0x0081, 0x0149, 0x00a9, 0x00f0, 0x00d0, 0x00e9, 0x0121, 0x015e, 0x005d,
    0xffff, 0xffff, 0x00af, 0xffff, 0xffff, 0xffff, 0xffff, 0x01a9, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0005, 0x0094, 0x00c8,
    0x0130, 0x0198, 0x01b2, 0xffff, 0xffff, 0xffff, 0x016f, 0x018b, 0x0000, 0x0091, 0x0171, 0x00da, 0x002a, 0xffff, 0xffff, 0x00d4,
    0x00bb, 0x00f5, 0x012b, 0x019a, 0x0011, 0xffff, 0xffff, 0x013d, 0xffff, 0x00ae, 0x015a, 0xffff, 0xffff, 0x01a6, 0x007b, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c0, 0xffff, 0xffff, 0xffff, 0xffff, 0x0061, 0xffff, 0xffff, 0xffff, 0x00f2,
    0x012d, 0xffff, 0xffff, 0x0001, 0xffff, 0xffff, 0xffff, 0x0039, 0xffff, 0xffff, 0xffff, 0x006a, 0x00d9, 0xffff, 0x0193, 0x007f,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00cc, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0139,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0142, 0x0119, 0xffff, 0x005c, 0xffff, 0x017a, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x001e, 0x01af, 0xffff, 0xffff, 0x010c, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x000e, 0x00ee,
    0x0162, 0x01a4, 0xffff, 0xffff, 0xffff, 0x008b, 0xffff, 0x0127, 0xffff, 0xffff, 0x00e5, 0x01b4, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00d3, 0x0098, 0xffff, 0xffff, 0x00a3, 0xffff, 0x0145, 0x009e, 0xffff,
    0x0191, 0xffff, 0xffff, 0x009a, 0x00c1, 0x0016, 0x00f6, 0xffff, 0x0054, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0114, 0xffff, 0x00c7, 0xffff, 0x00b9, 0x00f1, 0x0183, 0xffff, 0xffff, 0x0192, 0xffff, 0x003a, 0x00b3, 0x015f, 0x0013, 0x003e,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0116, 0x0133, 0x010d, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x003c, 0x01a0, 0x00bd, 0x0159, 0xffff, 0xffff, 0xffff, 0xffff, 0x010a, 0x0009, 0xffff, 0xffff, 0xffff, 0x0169, 0xffff, 0xffff,
    0x000c, 0x0036, 0xffff, 0x0134, 0xffff, 0x00de, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0197, 0x017c, 0x00b6, 0xffff,
    0xffff, 0xffff, 0x0122, 0x0074, 0x01ab, 0x0181, 0x0075, 0x0138, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x01a3, 0xffff, 0xffff,
    0xffff, 0x001c, 0x000d, 0xffff, 0x0007, 0x0064, 0x0065, 0xffff, 0xffff, 0x0166, 0xffff, 0xffff, 0x005b, 0xffff, 0xffff, 0x011c,
    0x0084, 0xffff, 0xffff, 0x019b, 0xffff, 0x00e0, 0xffff, 0xffff, 0x0170, 0x005e, 0xffff, 0xffff, 0x0066, 0xffff, 0xffff, 0xffff,
    0xffff, 0x0187, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0102, 0xffff, 0xffff,
    0x01ac, 0x0185, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c2, 0xffff, 0xffff, 0xffff, 0xffff, 0x0184, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0140, 0x0136, 0x00cb, 0x011a, 0x0144, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00c5, 0xffff, 0xffff, 0xffff, 0x00b4, 0xffff,
    0xffff, 0x0077, 0xffff, 0xffff, 0xffff, 0xffff, 0x00e2, 0x0072, 0x00a8, 0x0042, 0x013f, 0xffff, 0x0080, 0xffff, 0x004b, 0xffff,
    0xffff, 0x0125, 0xffff, 0xffff, 0xffff, 0x004a, 0xffff, 0xffff, 0xffff, 0x0106, 0x0108, 0xffff, 0xffff, 0x00c9, 0x0027, 0x012a,
    0xffff, 0x007e, 0xffff, 0xffff, 0xffff, 0xffff, 0x0014, 0xffff, 0xffff, 0xffff, 0xffff, 0x008d, 0xffff, 0xffff, 0x0112, 0x0118,
    0x018c, 0x0188, 0xffff, 0xffff, 0x002f, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ce, 0xffff, 0x0090, 0x001d, 0x0026, 0xffff, 0x00fc,
    0xffff, 0x008a, 0xffff, 0x0113, 0x0150, 0xffff, 0xffff, 0xffff, 0x0018, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0034, 0x0063,
    0x0110, 0xffff, 0xffff, 0xffff, 0xffff, 0x015c, 0xffff, 0xffff, 0x00a4, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0161, 0x00b8, 0x0137, 0xffff, 0x00a7, 0x0117, 0x016b, 0xffff, 0xffff, 0x0155, 0x003f, 0x01aa, 0x0048, 0x018d, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x016d, 0x003b, 0xffff, 0xffff, 0x00f9, 0x0004, 0x008f, 0x00a6, 0x0135, 0x00fd, 0xffff,
    0xffff, 0x00aa, 0xffff, 0x002c, 0xffff, 0x00e8, 0x012f, 0x0051, 0xffff, 0x0164, 0xffff, 0x017b, 0xffff, 0x000a, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0043, 0x01a2, 0xffff, 0xffff, 0xffff, 0xffff, 0x004d, 0x00b5, 0x0189, 0xffff, 0xffff, 0x008c,
    0x00b0, 0x0101, 0x0109, 0x017e, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00b2, 0x00ea, 0x0103, 0x012c, 0x00a0,
];

const VALUE_HASH: &[u16] = &[
    0x000c, 0x0067, 0xffff, 0xffff, 0xffff, 0xffff, 0x000d, 0x0012, 0x002d, 0xffff, 0x00b5, 0xffff, 0x009d, 0x0090, 0x0011, 0xffff,
    0xffff, 0x0038, 0x00bc, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003c, 0xffff, 0xffff, 0xffff, 0x00b3, 0x0043, 0xffff, 0xffff,
    0xffff, 0xffff, 0x004b, 0xffff, 0xffff, 0x0034, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00af, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0050, 0xffff, 0xffff, 0xffff, 0x0068, 0xffff, 0x000e, 0xffff, 0x00a8, 0xffff,
    0xffff, 0x0085, 0xffff, 0x0076, 0xffff, 0x002c, 0x0077, 0x0088, 0xffff, 0x00be, 0x0056, 0xffff, 0xffff, 0x003e, 0xffff, 0xffff,
    0xffff, 0xffff, 0x00aa, 0xffff, 0xffff, 0xffff, 0x004a, 0xffff, 0x004d, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x007c,
    0x0082, 0xffff, 0xffff, 0x008e, 0xffff, 0xffff, 0xffff, 0xffff, 0x0020, 0xffff, 0x0057, 0xffff, 0xffff, 0x0022, 0x0074, 0x0094,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0030, 0x00b9, 0xffff, 0xffff, 0xffff, 0x004e, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0095, 0xffff, 0xffff, 0x0070, 0x0029, 0x00a0, 0x0042, 0x005f, 0x0086, 0xffff, 0x0021, 0xffff,
    0xffff, 0x002e, 0xffff, 0xffff, 0x0002, 0xffff, 0x0048, 0x0003, 0x0041, 0x0014, 0x00b0, 0x005b, 0x0084, 0xffff, 0xffff, 0x001c,
    0x0065, 0xffff, 0x003b, 0xffff, 0xffff, 0x006b, 0x006d, 0xffff, 0xffff, 0x001a, 0xffff, 0x0018, 0xffff, 0xffff, 0xffff, 0xffff,
    0x0059, 0x00ad, 0xffff, 0x0054, 0xffff, 0xffff, 0x0097, 0x009f, 0xffff, 0xffff, 0xffff, 0x00b1, 0x000a, 0x0027, 0x0045, 0xffff,
    0xffff, 0xffff, 0xffff, 0x005d, 0x0010, 0xffff, 0xffff, 0xffff, 0x00b2, 0xffff, 0xffff, 0xffff, 0x0006, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0x0026, 0xffff, 0xffff, 0xffff, 0xffff, 0x0040, 0xffff, 0xffff, 0xffff, 0xffff, 0x0099, 0xffff, 0xffff, 0x0023,
    0x001e, 0x0087, 0x00ba, 0xffff, 0xffff, 0x0058, 0xffff, 0xffff, 0xffff, 0xffff, 0x0066, 0xffff, 0xffff, 0xffff, 0x005c, 0xffff,
    0xffff, 0x0032, 0x0096, 0x00a1, 0x00a9, 0x00b4, 0x00a4, 0x007b, 0x00ae, 0xffff, 0xffff, 0xffff, 0x0046, 0x0024, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0x00bb, 0xffff, 0xffff, 0x009c, 0xffff, 0x0079, 0xffff, 0xffff, 0xffff, 0xffff, 0x005a, 0xffff, 0x0063,
    0xffff, 0xffff, 0xffff, 0x0033, 0x00a6, 0xffff, 0xffff, 0xffff, 0x0044, 0x0049, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x00ac,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0028, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff,
    0x00b7, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x008a, 0x007e, 0x0031, 0x00a5, 0xffff, 0xffff, 0x008b, 0x0047, 0xffff, 0xffff,
    0x0039, 0x0089, 0xffff, 0xffff, 0xffff, 0xffff, 0x0091, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x001b, 0x0037,
    0xffff, 0x005e, 0xffff, 0x002f, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0083, 0xffff, 0x0025, 0xffff, 0xffff, 0xffff, 0xffff,
    0x003f, 0x002b, 0x006e, 0xffff, 0xffff, 0xffff, 0xffff, 0x008d, 0xffff, 0x0071, 0xffff, 0xffff, 0xffff, 0x0060, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x007a, 0xffff, 0x0013, 0x00b6, 0xffff, 0x0009, 0x009e, 0x0075, 0x00a3,
    0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x003a, 0xffff, 0xffff, 0x0035, 0xffff, 0x0019, 0xffff, 0x0017,
    0xffff, 0x0016, 0xffff, 0x0069, 0x0005, 0x0036, 0xffff, 0xffff, 0x0053, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0015, 0xffff,
    0xffff, 0xffff, 0x00b8, 0xffff, 0x008f, 0xffff, 0xffff, 0x006a, 0xffff, 0xffff, 0x0004, 0x00a2, 0x00ab, 0xffff, 0x0000, 0xffff,
    0xffff, 0x000b, 0x0073, 0xffff, 0xffff, 0xffff, 0xffff, 0x001d, 0x004c, 0x0098, 0x00a7, 0x0064, 0xffff, 0xffff, 0xffff, 0x004f,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0008, 0xffff, 0xffff, 0xffff, 0xffff, 0xffff, 0x0001, 0xffff, 0xffff, 0xffff, 0x006f, 0x000f,
    0xffff, 0x0081, 0x0092, 0xffff, 0xffff, 0xffff, 0x0078, 0xffff, 0xffff, 0xffff, 0x0061, 0x006c, 0x001f, 0x007f, 0x0055, 0x00bd,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0007, 0x002a, 0xffff, 0x007d, 0xffff, 0x003d, 0x0051, 0x0080, 0x0093, 0xffff, 0xffff, 0xffff,
    0xffff, 0xffff, 0xffff, 0xffff, 0x0052, 0x009b, 0xffff, 0xffff, 0x008c, 0x0062, 0x0072, 0xffff, 0xffff, 0x009a, 0xffff, 0xffff,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_well_formed_and_match_their_fingerprint() {
        assert_eq!(WIRE_DICTIONARY.check(), Ok(()));
        assert_eq!(WIRE_DICTIONARY.fingerprint(), WIRE_DICTIONARY_FINGERPRINT);
    }
}
