[package]
name = "lp-riscv-emu-guest"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
linked_list_allocator = { version = "0.10", default-features = false, features = ["use_spin"] }
lp-emu-abi = { path = "../../lp-emu/lp-emu-abi" }
lp-recovery = { workspace = true }
critical-section = { workspace = true }
lpc-shared = { path = "../../lp-core/lpc-shared", default-features = false }
log = { workspace = true, default-features = false }

[features]
profile = []

[build-dependencies]
