// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32s3/src/apb_saradc.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::{Access, RegNames};

/// Register names for the `apb_saradc` block (28 registers, 9 with a non-zero reset, 7 not plain read-write).
pub static APB_SARADC: RegNames = RegNames {
    block: "apb_saradc",
    entries: &[
        (0x000, "ctrl"),
        (0x004, "ctrl2"),
        (0x008, "filter_ctrl1"),
        (0x00c, "fsm_wait"),
        (0x010, "sar1_status"),
        (0x014, "sar2_status"),
        (0x018, "sar1_patt_tab1"),
        (0x01c, "sar1_patt_tab2"),
        (0x020, "sar1_patt_tab3"),
        (0x024, "sar1_patt_tab4"),
        (0x028, "sar2_patt_tab1"),
        (0x02c, "sar2_patt_tab2"),
        (0x030, "sar2_patt_tab3"),
        (0x034, "sar2_patt_tab4"),
        (0x038, "arb_ctrl"),
        (0x03c, "filter_ctrl0"),
        (0x040, "apb_saradc1_data_status"),
        (0x044, "thres0_ctrl"),
        (0x048, "thres1_ctrl"),
        (0x058, "thres_ctrl"),
        (0x05c, "int_ena"),
        (0x060, "int_raw"),
        (0x064, "int_st"),
        (0x068, "int_clr"),
        (0x06c, "dma_conf"),
        (0x070, "clkm_conf"),
        (0x078, "apb_saradc2_data_status"),
        (0x3fc, "ctrl_date"),
    ],
    resets: &[
        (0x000, 0x407f8240),
        (0x004, 0x0000a1fe),
        (0x00c, 0x00ff0808),
        (0x038, 0x00000900),
        (0x03c, 0x006b4000),
        (0x044, 0x0003ffed),
        (0x048, 0x0003ffed),
        (0x06c, 0x000000ff),
        (0x070, 0x00000004),
    ],
    access: &[
        (0x010, Access::ReadOnly),
        (0x014, Access::ReadOnly),
        (0x040, Access::ReadOnly),
        (0x060, Access::ReadOnly),
        (0x064, Access::ReadOnly),
        (0x068, Access::WriteOnly),
        (0x078, Access::ReadOnly),
    ],
};
