// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32s3/src/i2c_ana_mst.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `i2c_ana_mst` block (3 registers, 0 with a non-zero reset, 0 not plain read-write).
pub static I2C_ANA_MST: RegNames = RegNames {
    block: "i2c_ana_mst",
    entries: &[
        (0x000, "ana_conf0"),
        (0x004, "ana_config"),
        (0x008, "ana_config2"),
    ],
    resets: &[],
    access: &[],
};
