// Peripheral interrupt source numbers derived from esp-rs/esp-pacs:
//   esp32s3/src/lib.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

/// Every peripheral interrupt source, `(number, name)`, sorted (94 sources).
///
/// The number is the index into `INTERRUPT_CORE0.core_0_intr_map`.
pub static INTERRUPT_SOURCES: &[(u16, &str)] = &[
    (0, "WIFI_MAC"),
    (1, "WIFI_NMI"),
    (2, "WIFI_PWR"),
    (3, "WIFI_BB"),
    (4, "BT_MAC"),
    (5, "BT_BB"),
    (6, "BT_BB_NMI"),
    (7, "RWBT"),
    (8, "RWBLE"),
    (9, "RWBT_NMI"),
    (10, "RWBLE_NMI"),
    (11, "I2C_MASTER"),
    (12, "SLC0"),
    (13, "SLC1"),
    (14, "UHCI0"),
    (16, "GPIO"),
    (17, "GPIO_NMI"),
    (18, "GPIO_INTR_2"),
    (19, "GPIO_NMI_2"),
    (20, "SPI1"),
    (21, "SPI2"),
    (22, "SPI3"),
    (24, "LCD_CAM"),
    (25, "I2S0"),
    (26, "I2S1"),
    (27, "UART0"),
    (28, "UART1"),
    (29, "UART2"),
    (30, "SDIO_HOST"),
    (31, "MCPWM0"),
    (32, "MCPWM1"),
    (35, "LEDC"),
    (36, "EFUSE"),
    (37, "TWAI0"),
    (38, "USB"),
    (39, "RTC_CORE"),
    (40, "RMT"),
    (41, "PCNT"),
    (42, "I2C_EXT0"),
    (43, "I2C_EXT1"),
    (44, "SPI2_DMA"),
    (45, "SPI3_DMA"),
    (47, "WDT"),
    (48, "TIMER1"),
    (49, "TIMER2"),
    (50, "TG0_T0_LEVEL"),
    (51, "TG0_T1_LEVEL"),
    (52, "TG0_WDT_LEVEL"),
    (53, "TG1_T0_LEVEL"),
    (54, "TG1_T1_LEVEL"),
    (55, "TG1_WDT_LEVEL"),
    (56, "CACHE_IA"),
    (57, "SYSTIMER_TARGET0"),
    (58, "SYSTIMER_TARGET1"),
    (59, "SYSTIMER_TARGET2"),
    (60, "SPI_MEM_REJECT_CACHE"),
    (61, "DCACHE_PRELOAD0"),
    (62, "ICACHE_PRELOAD0"),
    (63, "DCACHE_SYNC0"),
    (64, "ICACHE_SYNC0"),
    (65, "APB_ADC"),
    (66, "DMA_IN_CH0"),
    (67, "DMA_IN_CH1"),
    (68, "DMA_IN_CH2"),
    (69, "DMA_IN_CH3"),
    (70, "DMA_IN_CH4"),
    (71, "DMA_OUT_CH0"),
    (72, "DMA_OUT_CH1"),
    (73, "DMA_OUT_CH2"),
    (74, "DMA_OUT_CH3"),
    (75, "DMA_OUT_CH4"),
    (76, "RSA"),
    (77, "AES"),
    (78, "SHA"),
    (79, "FROM_CPU_INTR0"),
    (80, "FROM_CPU_INTR1"),
    (81, "FROM_CPU_INTR2"),
    (82, "FROM_CPU_INTR3"),
    (83, "ASSIST_DEBUG"),
    (84, "DMA_APBPERI_PMS"),
    (85, "CORE0_IRAM0_PMS"),
    (86, "CORE0_DRAM0_PMS"),
    (87, "CORE0_PIF_PMS"),
    (88, "CORE0_PIF_PMS_SIZE"),
    (89, "CORE1_IRAM0_PMS"),
    (90, "CORE1_DRAM0_PMS"),
    (91, "CORE1_PIF_PMS"),
    (92, "CORE1_PIF_PMS_SIZE"),
    (93, "BACKUP_PMS_VIOLATE"),
    (94, "CACHE_CORE0_ACS"),
    (95, "CACHE_CORE1_ACS"),
    (96, "USB_DEVICE"),
    (97, "PERI_BACKUP"),
    (98, "DMA_EXTMEM_REJECT"),
];

/// The same numbers as named constants.
#[allow(dead_code, reason = "generated: every source, used or not")]
pub mod source {
    pub const WIFI_MAC: u16 = 0;
    pub const WIFI_NMI: u16 = 1;
    pub const WIFI_PWR: u16 = 2;
    pub const WIFI_BB: u16 = 3;
    pub const BT_MAC: u16 = 4;
    pub const BT_BB: u16 = 5;
    pub const BT_BB_NMI: u16 = 6;
    pub const RWBT: u16 = 7;
    pub const RWBLE: u16 = 8;
    pub const RWBT_NMI: u16 = 9;
    pub const RWBLE_NMI: u16 = 10;
    pub const I2C_MASTER: u16 = 11;
    pub const SLC0: u16 = 12;
    pub const SLC1: u16 = 13;
    pub const UHCI0: u16 = 14;
    pub const GPIO: u16 = 16;
    pub const GPIO_NMI: u16 = 17;
    pub const GPIO_INTR_2: u16 = 18;
    pub const GPIO_NMI_2: u16 = 19;
    pub const SPI1: u16 = 20;
    pub const SPI2: u16 = 21;
    pub const SPI3: u16 = 22;
    pub const LCD_CAM: u16 = 24;
    pub const I2S0: u16 = 25;
    pub const I2S1: u16 = 26;
    pub const UART0: u16 = 27;
    pub const UART1: u16 = 28;
    pub const UART2: u16 = 29;
    pub const SDIO_HOST: u16 = 30;
    pub const MCPWM0: u16 = 31;
    pub const MCPWM1: u16 = 32;
    pub const LEDC: u16 = 35;
    pub const EFUSE: u16 = 36;
    pub const TWAI0: u16 = 37;
    pub const USB: u16 = 38;
    pub const RTC_CORE: u16 = 39;
    pub const RMT: u16 = 40;
    pub const PCNT: u16 = 41;
    pub const I2C_EXT0: u16 = 42;
    pub const I2C_EXT1: u16 = 43;
    pub const SPI2_DMA: u16 = 44;
    pub const SPI3_DMA: u16 = 45;
    pub const WDT: u16 = 47;
    pub const TIMER1: u16 = 48;
    pub const TIMER2: u16 = 49;
    pub const TG0_T0_LEVEL: u16 = 50;
    pub const TG0_T1_LEVEL: u16 = 51;
    pub const TG0_WDT_LEVEL: u16 = 52;
    pub const TG1_T0_LEVEL: u16 = 53;
    pub const TG1_T1_LEVEL: u16 = 54;
    pub const TG1_WDT_LEVEL: u16 = 55;
    pub const CACHE_IA: u16 = 56;
    pub const SYSTIMER_TARGET0: u16 = 57;
    pub const SYSTIMER_TARGET1: u16 = 58;
    pub const SYSTIMER_TARGET2: u16 = 59;
    pub const SPI_MEM_REJECT_CACHE: u16 = 60;
    pub const DCACHE_PRELOAD0: u16 = 61;
    pub const ICACHE_PRELOAD0: u16 = 62;
    pub const DCACHE_SYNC0: u16 = 63;
    pub const ICACHE_SYNC0: u16 = 64;
    pub const APB_ADC: u16 = 65;
    pub const DMA_IN_CH0: u16 = 66;
    pub const DMA_IN_CH1: u16 = 67;
    pub const DMA_IN_CH2: u16 = 68;
    pub const DMA_IN_CH3: u16 = 69;
    pub const DMA_IN_CH4: u16 = 70;
    pub const DMA_OUT_CH0: u16 = 71;
    pub const DMA_OUT_CH1: u16 = 72;
    pub const DMA_OUT_CH2: u16 = 73;
    pub const DMA_OUT_CH3: u16 = 74;
    pub const DMA_OUT_CH4: u16 = 75;
    pub const RSA: u16 = 76;
    pub const AES: u16 = 77;
    pub const SHA: u16 = 78;
    pub const FROM_CPU_INTR0: u16 = 79;
    pub const FROM_CPU_INTR1: u16 = 80;
    pub const FROM_CPU_INTR2: u16 = 81;
    pub const FROM_CPU_INTR3: u16 = 82;
    pub const ASSIST_DEBUG: u16 = 83;
    pub const DMA_APBPERI_PMS: u16 = 84;
    pub const CORE0_IRAM0_PMS: u16 = 85;
    pub const CORE0_DRAM0_PMS: u16 = 86;
    pub const CORE0_PIF_PMS: u16 = 87;
    pub const CORE0_PIF_PMS_SIZE: u16 = 88;
    pub const CORE1_IRAM0_PMS: u16 = 89;
    pub const CORE1_DRAM0_PMS: u16 = 90;
    pub const CORE1_PIF_PMS: u16 = 91;
    pub const CORE1_PIF_PMS_SIZE: u16 = 92;
    pub const BACKUP_PMS_VIOLATE: u16 = 93;
    pub const CACHE_CORE0_ACS: u16 = 94;
    pub const CACHE_CORE1_ACS: u16 = 95;
    pub const USB_DEVICE: u16 = 96;
    pub const PERI_BACKUP: u16 = 97;
    pub const DMA_EXTMEM_REJECT: u16 = 98;
}
