// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32s3/src/rng.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::{Access, RegNames};

/// Register names for the `rng` block (1 registers, 0 with a non-zero reset, 1 not plain read-write).
pub static RNG: RegNames = RegNames {
    block: "rng",
    entries: &[(0x110, "data")],
    resets: &[],
    access: &[(0x110, Access::ReadOnly)],
};
