// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32s3/src/spi0.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::{Access, RegNames};

/// Register names for the `spi0` block (38 registers, 13 with a non-zero reset, 5 not plain read-write).
pub static SPI0: RegNames = RegNames {
    block: "spi0",
    entries: &[
        (0x008, "ctrl"),
        (0x00c, "ctrl1"),
        (0x010, "ctrl2"),
        (0x014, "clock"),
        (0x018, "user"),
        (0x01c, "user1"),
        (0x020, "user2"),
        (0x02c, "rd_status"),
        (0x030, "ext_addr"),
        (0x034, "misc"),
        (0x03c, "cache_fctrl"),
        (0x040, "cache_sctrl"),
        (0x044, "sram_cmd"),
        (0x048, "sram_drd_cmd"),
        (0x04c, "sram_dwr_cmd"),
        (0x050, "sram_clk"),
        (0x054, "fsm"),
        (0x0a8, "timing_cali"),
        (0x0ac, "din_mode"),
        (0x0b0, "din_num"),
        (0x0b4, "dout_mode"),
        (0x0bc, "spi_smem_timing_cali"),
        (0x0c0, "spi_smem_din_mode"),
        (0x0c4, "spi_smem_din_num"),
        (0x0c8, "spi_smem_dout_mode"),
        (0x0cc, "ecc_ctrl"),
        (0x0d0, "ecc_err_addr"),
        (0x0d4, "ecc_err_bit"),
        (0x0dc, "spi_smem_ac"),
        (0x0e0, "ddr"),
        (0x0e4, "spi_smem_ddr"),
        (0x0e8, "clock_gate"),
        (0x0ec, "core_clk_sel"),
        (0x0f0, "int_ena"),
        (0x0f4, "int_clr"),
        (0x0f8, "int_raw"),
        (0x0fc, "int_st"),
        (0x3fc, "date"),
    ],
    resets: &[
        (0x008, 0x002c2000),
        (0x010, 0x00002c21),
        (0x014, 0x00030103),
        (0x01c, 0x5c000007),
        (0x020, 0x70000000),
        (0x040, 0x0055c070),
        (0x050, 0x00030103),
        (0x0cc, 0x0000000a),
        (0x0dc, 0x0000b084),
        (0x0e0, 0x00003020),
        (0x0e4, 0x00003020),
        (0x0e8, 0x00000001),
        (0x3fc, 0x02101040),
    ],
    access: &[
        (0x054, Access::ReadOnly),
        (0x0d0, Access::ReadOnly),
        (0x0d4, Access::ReadOnly),
        (0x0f4, Access::WriteOnly),
        (0x0fc, Access::ReadOnly),
    ],
};
