// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32s3/src/usb_device.rs  (crate esp32s3 0.35.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::{Access, RegNames};

/// Register names for the `usb_device` block (20 registers, 9 with a non-zero reset, 10 not plain read-write).
pub static USB_DEVICE: RegNames = RegNames {
    block: "usb_device",
    entries: &[
        (0x000, "ep1"),
        (0x004, "ep1_conf"),
        (0x008, "int_raw"),
        (0x00c, "int_st"),
        (0x010, "int_ena"),
        (0x014, "int_clr"),
        (0x018, "conf0"),
        (0x01c, "test"),
        (0x020, "jfifo_st"),
        (0x024, "fram_num"),
        (0x028, "in_ep0_st"),
        (0x02c, "in_ep1_st"),
        (0x030, "in_ep2_st"),
        (0x034, "in_ep3_st"),
        (0x038, "out_ep0_st"),
        (0x03c, "out_ep1_st"),
        (0x040, "out_ep2_st"),
        (0x044, "misc_conf"),
        (0x048, "mem_conf"),
        (0x080, "date"),
    ],
    resets: &[
        (0x004, 0x00000002),
        (0x008, 0x00000008),
        (0x018, 0x00004200),
        (0x020, 0x00000044),
        (0x028, 0x00000001),
        (0x02c, 0x00000001),
        (0x030, 0x00000001),
        (0x034, 0x00000001),
        (0x048, 0x00000002),
    ],
    access: &[
        (0x00c, Access::ReadOnly),
        (0x014, Access::WriteOnly),
        (0x024, Access::ReadOnly),
        (0x028, Access::ReadOnly),
        (0x02c, Access::ReadOnly),
        (0x030, Access::ReadOnly),
        (0x034, Access::ReadOnly),
        (0x038, Access::ReadOnly),
        (0x03c, Access::ReadOnly),
        (0x040, Access::ReadOnly),
    ],
};
