#!/usr/bin/env bash
# Extract each FP capability probe from probe.S into its own raw payload blob,
# and print the table the desk session pastes into the experiment repo's runner
# test. Run ./build.sh first.
#
# Payload bytes are assembler-derived, never hand-written (AGENTS.md).
set -euo pipefail
cd "$(dirname "$0")"

BIN_DIR="$(echo "$HOME"/.rustup/toolchains/esp/xtensa-esp-elf/esp-*/xtensa-esp-elf/bin | tr ' ' '\n' | tail -1)"
OBJCOPY="$BIN_DIR/xtensa-esp32s3-elf-objcopy"
OBJDUMP="$BIN_DIR/xtensa-esp32s3-elf-objdump"
if [[ ! -f obj/probe.o ]]; then
  echo "error: obj/probe.o missing — run ./build.sh first" >&2
  exit 1
fi

mkdir -p obj/probes
sections="$("$OBJDUMP" -h obj/probe.o | awk '$2 ~ /^\.probe\./ { print $2 }')"

echo "// Generated by lp-xt/fixtures/fp/probes.sh — assembler-derived payloads."
echo "// Each entry is (name, payload bytes) for the experiment repo's runner."
echo "pub const FP_PROBES: &[(&str, &[u8])] = &["
for sec in $sections; do
  name="${sec#.probe.}"
  "$OBJCOPY" -O binary -j "$sec" obj/probe.o "obj/probes/$name.bin"
  hex="$(xxd -p "obj/probes/$name.bin" | tr -d '\n' | sed 's/../0x&, /g')"
  printf '    ("%s", &[%s]),\n' "$name" "${hex% }"
done
echo "];"
echo
echo "// probe.S disassembly, for review:" >&2
"$OBJDUMP" -d obj/probe.o >&2
