// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32/src/apb_ctrl.rs  (crate esp32 0.40.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `apb_ctrl` block (17 registers, 16 with a non-zero reset, 0 not plain read-write).
pub static APB_CTRL: RegNames = RegNames {
    block: "apb_ctrl",
    entries: &[
        (0x000, "sysclk_conf"),
        (0x004, "xtal_tick_conf"),
        (0x008, "pll_tick_conf"),
        (0x00c, "ck8m_tick_conf"),
        (0x010, "apb_saradc_ctrl"),
        (0x014, "apb_saradc_ctrl2"),
        (0x018, "apb_saradc_fsm"),
        (0x01c, "apb_saradc_sar1_patt_tab1"),
        (0x020, "apb_saradc_sar1_patt_tab2"),
        (0x024, "apb_saradc_sar1_patt_tab3"),
        (0x028, "apb_saradc_sar1_patt_tab4"),
        (0x02c, "apb_saradc_sar2_patt_tab1"),
        (0x030, "apb_saradc_sar2_patt_tab2"),
        (0x034, "apb_saradc_sar2_patt_tab3"),
        (0x038, "apb_saradc_sar2_patt_tab4"),
        (0x03c, "apll_tick_conf"),
        (0x07c, "date"),
    ],
    resets: &[
        (0x000, 0x00002000),
        (0x004, 0x00000027),
        (0x008, 0x0000004f),
        (0x00c, 0x0000000b),
        (0x010, 0x007f8240),
        (0x014, 0x000001fe),
        (0x018, 0x0208ff08),
        (0x01c, 0x0f0f0f0f),
        (0x020, 0x0f0f0f0f),
        (0x024, 0x0f0f0f0f),
        (0x028, 0x0f0f0f0f),
        (0x02c, 0x0f0f0f0f),
        (0x030, 0x0f0f0f0f),
        (0x034, 0x0f0f0f0f),
        (0x038, 0x0f0f0f0f),
        (0x03c, 0x00000063),
    ],
    access: &[],
};
