// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32/src/frc_timer.rs  (crate esp32 0.40.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `frc_timer` block (5 registers, 0 with a non-zero reset, 0 not plain read-write).
pub static FRC_TIMER: RegNames = RegNames {
    block: "frc_timer",
    entries: &[
        (0x000, "timer_load"),
        (0x004, "timer_count"),
        (0x008, "timer_ctrl"),
        (0x00c, "timer_int"),
        (0x010, "timer_alarm"),
    ],
    resets: &[],
    access: &[],
};
