// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32/src/io_mux.rs  (crate esp32 0.40.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `io_mux` block (37 registers, 0 with a non-zero reset, 0 not plain read-write).
pub static IO_MUX: RegNames = RegNames {
    block: "io_mux",
    entries: &[
        (0x000, "pin_ctrl"),
        (0x004, "gpio36"),
        (0x008, "gpio37"),
        (0x00c, "gpio38"),
        (0x010, "gpio39"),
        (0x014, "gpio34"),
        (0x018, "gpio35"),
        (0x01c, "gpio32"),
        (0x020, "gpio33"),
        (0x024, "gpio25"),
        (0x028, "gpio26"),
        (0x02c, "gpio27"),
        (0x030, "gpio14"),
        (0x034, "gpio12"),
        (0x038, "gpio13"),
        (0x03c, "gpio15"),
        (0x040, "gpio2"),
        (0x044, "gpio0"),
        (0x048, "gpio4"),
        (0x04c, "gpio16"),
        (0x050, "gpio17"),
        (0x054, "gpio9"),
        (0x058, "gpio10"),
        (0x05c, "gpio11"),
        (0x060, "gpio6"),
        (0x064, "gpio7"),
        (0x068, "gpio8"),
        (0x06c, "gpio5"),
        (0x070, "gpio18"),
        (0x074, "gpio19"),
        (0x078, "gpio20"),
        (0x07c, "gpio21"),
        (0x080, "gpio22"),
        (0x084, "gpio3"),
        (0x088, "gpio1"),
        (0x08c, "gpio23"),
        (0x090, "gpio24"),
    ],
    resets: &[],
    access: &[],
};
