// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32/src/rtc_i2c.rs  (crate esp32 0.40.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `rtc_i2c` block (15 registers, 0 with a non-zero reset, 0 not plain read-write).
pub static RTC_I2C: RegNames = RegNames {
    block: "rtc_i2c",
    entries: &[
        (0x000, "scl_low_period"),
        (0x004, "ctrl"),
        (0x008, "debug_status"),
        (0x00c, "timeout"),
        (0x010, "slave_addr"),
        (0x01c, "data"),
        (0x020, "int_raw"),
        (0x024, "int_clr"),
        (0x028, "int_ena"),
        (0x02c, "int_st"),
        (0x030, "sda_duty"),
        (0x038, "scl_high_period"),
        (0x040, "scl_start_period"),
        (0x044, "scl_stop_period"),
        (0x048, "cmd"),
    ],
    resets: &[],
    access: &[],
};
