// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32/src/uart0.rs  (crate esp32 0.40.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::{Access, RegNames};

/// Register names for the `uart0` block (30 registers, 17 with a non-zero reset, 12 not plain read-write).
pub static UART0: RegNames = RegNames {
    block: "uart0",
    entries: &[
        (0x000, "fifo"),
        (0x004, "int_raw"),
        (0x008, "int_st"),
        (0x00c, "int_ena"),
        (0x010, "int_clr"),
        (0x014, "clkdiv"),
        (0x018, "autobaud"),
        (0x01c, "status"),
        (0x020, "conf0"),
        (0x024, "conf1"),
        (0x028, "lowpulse"),
        (0x02c, "highpulse"),
        (0x030, "rxd_cnt"),
        (0x034, "flow_conf"),
        (0x038, "sleep_conf"),
        (0x03c, "swfc_conf"),
        (0x040, "idle_conf"),
        (0x044, "rs485_conf"),
        (0x048, "at_cmd_precnt"),
        (0x04c, "at_cmd_postcnt"),
        (0x050, "at_cmd_gaptout"),
        (0x054, "at_cmd_char"),
        (0x058, "mem_conf"),
        (0x05c, "mem_tx_status"),
        (0x060, "mem_rx_status"),
        (0x064, "mem_cnt_status"),
        (0x068, "pospulse"),
        (0x06c, "negpulse"),
        (0x078, "date"),
        (0x07c, "id"),
    ],
    resets: &[
        (0x014, 0x000002b6),
        (0x018, 0x00001000),
        (0x020, 0x0800001c),
        (0x024, 0x00006060),
        (0x028, 0x000fffff),
        (0x02c, 0x000fffff),
        (0x038, 0x000000f0),
        (0x03c, 0x1311e000),
        (0x040, 0x00a40100),
        (0x048, 0x00186a00),
        (0x04c, 0x00186a00),
        (0x050, 0x00001e00),
        (0x054, 0x0000032b),
        (0x058, 0x00000088),
        (0x068, 0x000fffff),
        (0x06c, 0x000fffff),
        (0x07c, 0x00000500),
    ],
    access: &[
        (0x004, Access::ReadOnly),
        (0x008, Access::ReadOnly),
        (0x010, Access::WriteOnly),
        (0x01c, Access::ReadOnly),
        (0x028, Access::ReadOnly),
        (0x02c, Access::ReadOnly),
        (0x030, Access::ReadOnly),
        (0x05c, Access::ReadOnly),
        (0x060, Access::ReadOnly),
        (0x064, Access::ReadOnly),
        (0x068, Access::ReadOnly),
        (0x06c, Access::ReadOnly),
    ],
};
