//! GLSL / LPIR / LPFX name → `BuiltinId`, per float mode.
//!
//! AUTO-GENERATED by lps-builtins-gen-app. Do not edit manually.
//!
//! Each family has a `_q32_` and an `_f32_` resolver plus a mode-taking facade:
//!
//! - `glsl_{q32,f32}_math_builtin_id` / `glsl_math_builtin_id`: `@glsl::*` scalar imports.
//! - `lpir_{q32,f32}_builtin_id` / `lpir_builtin_id`: `@lpir::*` library ops (e.g. `sqrt`).
//! - `glsl_lpfn_{q32,f32}_builtin_id` / `glsl_lpfn_builtin_id`: `lpfn_*` overloads keyed by parameter types.
//! - `texture_{q32,f32}_builtin_id` / `texture_builtin_id`: `@texture::*` sampler builtins (logical vec4 return via out-pointer).
//! - `vm_{q32,f32}_builtin_id` / `vm_builtin_id`: `@vm::*` context builtins.
//!
//! **A resolver never crosses modes.** In f32 mode only f32 (and
//! mode-independent) ids resolve, and there is no fallback to the Q32 id.
//! That fallback is precisely the failure the wasm f32 bring-up found: a
//! builtin taking a vector receives an `IrType::Pointer`, both sides are
//! `i32`, so a Q32 builtin handed an f32 module's memory reinterprets f32 bit
//! patterns as Q16.16 — wrong answers, no validation error, nothing to catch
//! it. See `docs/design/float.md` §6.
//!
//! Regenerate: `cargo run -p lps-builtins-gen-app` or `scripts/build-builtins.sh`

use super::BuiltinId;
use super::Mode;

/// Parameter types for LPFX overload resolution (matches GLSL, not flattened WASM).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum GlslParamKind {
    Bool,
    Int,
    UInt,
    Float,
    Vec2,
    Vec3,
    Vec4,
    IVec2,
    IVec3,
    IVec4,
    UVec2,
    UVec3,
    UVec4,
    BVec2,
    BVec3,
    BVec4,
}
/// Map `@glsl::*` import name + **AST argument count** to a q32 scalar builtin.
/// Returns `None` for builtins implemented inline in WASM (e.g. `clamp`) or unknown names.
pub fn glsl_q32_math_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("acos", 1) => Some(BuiltinId::LpGlslAcosQ32),
        ("acosh", 1) => Some(BuiltinId::LpGlslAcoshQ32),
        ("asin", 1) => Some(BuiltinId::LpGlslAsinQ32),
        ("asinh", 1) => Some(BuiltinId::LpGlslAsinhQ32),
        ("atan", 2) => Some(BuiltinId::LpGlslAtan2Q32),
        ("atan2", 2) => Some(BuiltinId::LpGlslAtan2Q32),
        ("atan", 1) => Some(BuiltinId::LpGlslAtanQ32),
        ("atanh", 1) => Some(BuiltinId::LpGlslAtanhQ32),
        ("cos", 1) => Some(BuiltinId::LpGlslCosQ32),
        ("cosh", 1) => Some(BuiltinId::LpGlslCoshQ32),
        ("exp2", 1) => Some(BuiltinId::LpGlslExp2Q32),
        ("exp", 1) => Some(BuiltinId::LpGlslExpQ32),
        ("fma", 3) => Some(BuiltinId::LpGlslFmaQ32),
        ("inversesqrt", 1) => Some(BuiltinId::LpGlslInversesqrtQ32),
        ("ldexp", 2) => Some(BuiltinId::LpGlslLdexpQ32),
        ("log2", 1) => Some(BuiltinId::LpGlslLog2Q32),
        ("log", 1) => Some(BuiltinId::LpGlslLogQ32),
        ("mod", 2) => Some(BuiltinId::LpGlslModQ32),
        ("pow", 2) => Some(BuiltinId::LpGlslPowQ32),
        ("round", 1) => Some(BuiltinId::LpGlslRoundQ32),
        ("sin", 1) => Some(BuiltinId::LpGlslSinQ32),
        ("sincos", 3) => Some(BuiltinId::LpGlslSincosQ32),
        ("sinh", 1) => Some(BuiltinId::LpGlslSinhQ32),
        ("tan", 1) => Some(BuiltinId::LpGlslTanQ32),
        ("tanh", 1) => Some(BuiltinId::LpGlslTanhQ32),
        _ => None,
    }
}

/// Map `@lpir::*` import name + argument count to a q32 builtin.
pub fn lpir_q32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("fabs", 1) => Some(BuiltinId::LpLpirFabsQ32),
        ("fadd", 2) => Some(BuiltinId::LpLpirFaddQ32),
        ("fceil", 1) => Some(BuiltinId::LpLpirFceilQ32),
        ("fdiv", 2) => Some(BuiltinId::LpLpirFdivQ32),
        ("fdiv_recip", 2) => Some(BuiltinId::LpLpirFdivRecipQ32),
        ("ffloor", 1) => Some(BuiltinId::LpLpirFfloorQ32),
        ("fmax", 2) => Some(BuiltinId::LpLpirFmaxQ32),
        ("fmin", 2) => Some(BuiltinId::LpLpirFminQ32),
        ("fmul", 2) => Some(BuiltinId::LpLpirFmulQ32),
        ("fnearest", 1) => Some(BuiltinId::LpLpirFnearestQ32),
        ("sqrt", 1) => Some(BuiltinId::LpLpirFsqrtQ32),
        ("fsub", 2) => Some(BuiltinId::LpLpirFsubQ32),
        ("fto_unorm16", 1) => Some(BuiltinId::LpLpirFtoUnorm16Q32),
        ("fto_unorm8", 1) => Some(BuiltinId::LpLpirFtoUnorm8Q32),
        ("ftoi_sat_s", 1) => Some(BuiltinId::LpLpirFtoiSatSQ32),
        ("ftoi_sat_u", 1) => Some(BuiltinId::LpLpirFtoiSatUQ32),
        ("ftrunc", 1) => Some(BuiltinId::LpLpirFtruncQ32),
        ("itof_s", 1) => Some(BuiltinId::LpLpirItofSQ32),
        ("itof_u", 1) => Some(BuiltinId::LpLpirItofUQ32),
        ("unorm16_to_f", 1) => Some(BuiltinId::LpLpirUnorm16ToFQ32),
        ("unorm8_to_f", 1) => Some(BuiltinId::LpLpirUnorm8ToFQ32),
        _ => None,
    }
}

/// Map `@vm::*` import name + user-visible argument count to a q32 builtin.
pub fn vm_q32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("__lp_get_fuel", 0) => Some(BuiltinId::LpVmGetFuel),
        _ => None,
    }
}

/// Map `@texture::*` import base name + user-visible argument count to a q32 builtin.
/// Frontend may suffix the name with `_<naga id>` — strip that suffix before lookup.
pub fn texture_q32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("texture1d_r16_unorm", 7) => Some(BuiltinId::LpTexTexture1dR16UnormQ32),
        ("texture1d_rgba16_unorm", 7) => Some(BuiltinId::LpTexTexture1dRgba16UnormQ32),
        ("texture2d_r16_unorm", 10) => Some(BuiltinId::LpTexTexture2dR16UnormQ32),
        ("texture2d_rgba16_unorm", 10) => Some(BuiltinId::LpTexTexture2dRgba16UnormQ32),
        _ => None,
    }
}

/// Map `lpfn_*` name + parameter type list to the q32 `BuiltinId`.
pub fn glsl_lpfn_q32_builtin_id(name: &str, params: &[GlslParamKind]) -> Option<BuiltinId> {
    match (name, params) {
        ("lpfn_fbm", &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnFbm2Q32)
        }
        (
            "lpfn_fbm",
            &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::Int, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnFbm3TileQ32),
        ("lpfn_fbm", &[GlslParamKind::Vec3, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnFbm3Q32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise1Q32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise2Q32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise3TileQ32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise3Q32)
        }
        ("lpfn_hash", &[GlslParamKind::UInt, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash1),
        ("lpfn_hash", &[GlslParamKind::UVec2, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash2),
        ("lpfn_hash", &[GlslParamKind::UVec3, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash3),
        ("lpfn_hsv2rgb", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnHsv2rgbQ32),
        ("lpfn_hsv2rgb", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnHsv2rgbVec4Q32),
        ("lpfn_hue2rgb", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfnHue2rgbQ32),
        (
            "lpfn_psrdnoise",
            &[GlslParamKind::Vec2, GlslParamKind::Vec2, GlslParamKind::Float, GlslParamKind::Vec2, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnPsrdnoise2Q32),
        (
            "lpfn_psrdnoise",
            &[GlslParamKind::Vec3, GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::Vec3, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnPsrdnoise3Q32),
        ("lpfn_random", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom1Q32)
        }
        ("lpfn_random", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom2Q32)
        }
        ("lpfn_random", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom3Q32)
        }
        ("lpfn_rgb2hsv", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnRgb2hsvQ32),
        ("lpfn_rgb2hsv", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnRgb2hsvVec4Q32),
        ("lpfn_saturate", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfnSaturateQ32),
        ("lpfn_saturate", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnSaturateVec3Q32),
        ("lpfn_saturate", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnSaturateVec4Q32),
        ("lpfn_snoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise1Q32)
        }
        ("lpfn_snoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise2Q32)
        }
        ("lpfn_snoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise3Q32)
        }
        ("lpfn_srandom", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom1Q32)
        }
        ("lpfn_srandom", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom2Q32)
        }
        ("lpfn_srandom", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom3Q32)
        }
        (
            "lpfn_srandom3_tile",
            &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnSrandom3TileQ32),
        ("lpfn_srandom3_vec", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom3VecQ32)
        }
        ("lpfn_worley", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley2Q32)
        }
        ("lpfn_worley", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley3Q32)
        }
        ("lpfn_worley_value", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley2ValueQ32)
        }
        ("lpfn_worley_value", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley3ValueQ32)
        }
        _ => None,
    }
}

/// Map `@glsl::*` import name + **AST argument count** to a f32 scalar builtin.
/// Returns `None` for builtins implemented inline in WASM (e.g. `clamp`) or unknown names.
pub fn glsl_f32_math_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("acos", 1) => Some(BuiltinId::LpGlslAcosF32),
        ("acosh", 1) => Some(BuiltinId::LpGlslAcoshF32),
        ("asin", 1) => Some(BuiltinId::LpGlslAsinF32),
        ("asinh", 1) => Some(BuiltinId::LpGlslAsinhF32),
        ("atan", 2) => Some(BuiltinId::LpGlslAtan2F32),
        ("atan2", 2) => Some(BuiltinId::LpGlslAtan2F32),
        ("atan", 1) => Some(BuiltinId::LpGlslAtanF32),
        ("atanh", 1) => Some(BuiltinId::LpGlslAtanhF32),
        ("cos", 1) => Some(BuiltinId::LpGlslCosF32),
        ("cosh", 1) => Some(BuiltinId::LpGlslCoshF32),
        ("exp2", 1) => Some(BuiltinId::LpGlslExp2F32),
        ("exp", 1) => Some(BuiltinId::LpGlslExpF32),
        ("fma", 3) => Some(BuiltinId::LpGlslFmaF32),
        ("inversesqrt", 1) => Some(BuiltinId::LpGlslInversesqrtF32),
        ("ldexp", 2) => Some(BuiltinId::LpGlslLdexpF32),
        ("log2", 1) => Some(BuiltinId::LpGlslLog2F32),
        ("log", 1) => Some(BuiltinId::LpGlslLogF32),
        ("mod", 2) => Some(BuiltinId::LpGlslModF32),
        ("pow", 2) => Some(BuiltinId::LpGlslPowF32),
        ("round", 1) => Some(BuiltinId::LpGlslRoundF32),
        ("sin", 1) => Some(BuiltinId::LpGlslSinF32),
        ("sincos", 3) => Some(BuiltinId::LpGlslSincosF32),
        ("sinh", 1) => Some(BuiltinId::LpGlslSinhF32),
        ("tan", 1) => Some(BuiltinId::LpGlslTanF32),
        ("tanh", 1) => Some(BuiltinId::LpGlslTanhF32),
        _ => None,
    }
}

/// Map `@lpir::*` import name + argument count to a f32 builtin.
pub fn lpir_f32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("fabs", 1) => Some(BuiltinId::LpLpirFabsF32),
        ("fadd", 2) => Some(BuiltinId::LpLpirFaddF32),
        ("fceil", 1) => Some(BuiltinId::LpLpirFceilF32),
        ("fdiv", 2) => Some(BuiltinId::LpLpirFdivF32),
        ("fdiv_recip", 2) => Some(BuiltinId::LpLpirFdivRecipF32),
        ("ffloor", 1) => Some(BuiltinId::LpLpirFfloorF32),
        ("fmax", 2) => Some(BuiltinId::LpLpirFmaxF32),
        ("fmin", 2) => Some(BuiltinId::LpLpirFminF32),
        ("fmul", 2) => Some(BuiltinId::LpLpirFmulF32),
        ("fnearest", 1) => Some(BuiltinId::LpLpirFnearestF32),
        ("sqrt", 1) => Some(BuiltinId::LpLpirFsqrtF32),
        ("fsub", 2) => Some(BuiltinId::LpLpirFsubF32),
        ("fto_unorm16", 1) => Some(BuiltinId::LpLpirFtoUnorm16F32),
        ("fto_unorm8", 1) => Some(BuiltinId::LpLpirFtoUnorm8F32),
        ("ftoi_sat_s", 1) => Some(BuiltinId::LpLpirFtoiSatSF32),
        ("ftoi_sat_u", 1) => Some(BuiltinId::LpLpirFtoiSatUF32),
        ("ftrunc", 1) => Some(BuiltinId::LpLpirFtruncF32),
        ("itof_s", 1) => Some(BuiltinId::LpLpirItofSF32),
        ("itof_u", 1) => Some(BuiltinId::LpLpirItofUF32),
        ("unorm16_to_f", 1) => Some(BuiltinId::LpLpirUnorm16ToFF32),
        ("unorm8_to_f", 1) => Some(BuiltinId::LpLpirUnorm8ToFF32),
        _ => None,
    }
}

/// Map `@vm::*` import name + user-visible argument count to a f32 builtin.
pub fn vm_f32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("__lp_get_fuel", 0) => Some(BuiltinId::LpVmGetFuel),
        _ => None,
    }
}

/// Map `@texture::*` import base name + user-visible argument count to a f32 builtin.
/// Frontend may suffix the name with `_<naga id>` — strip that suffix before lookup.
pub fn texture_f32_builtin_id(name: &str, arg_count: usize) -> Option<BuiltinId> {
    match (name, arg_count) {
        ("texture1d_r16_unorm", 7) => Some(BuiltinId::LpTexTexture1dR16UnormF32),
        ("texture1d_rgba16_unorm", 7) => Some(BuiltinId::LpTexTexture1dRgba16UnormF32),
        ("texture2d_r16_unorm", 10) => Some(BuiltinId::LpTexTexture2dR16UnormF32),
        ("texture2d_rgba16_unorm", 10) => Some(BuiltinId::LpTexTexture2dRgba16UnormF32),
        _ => None,
    }
}

/// Map `lpfn_*` name + parameter type list to the f32 `BuiltinId`.
pub fn glsl_lpfn_f32_builtin_id(name: &str, params: &[GlslParamKind]) -> Option<BuiltinId> {
    match (name, params) {
        ("lpfn_fbm", &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnFbm2F32)
        }
        (
            "lpfn_fbm",
            &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::Int, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnFbm3TileF32),
        ("lpfn_fbm", &[GlslParamKind::Vec3, GlslParamKind::Int, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnFbm3F32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise1F32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise2F32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise3TileF32)
        }
        ("lpfn_gnoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnGnoise3F32)
        }
        ("lpfn_hash", &[GlslParamKind::UInt, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash1),
        ("lpfn_hash", &[GlslParamKind::UVec2, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash2),
        ("lpfn_hash", &[GlslParamKind::UVec3, GlslParamKind::UInt]) => Some(BuiltinId::LpLpfnHash3),
        ("lpfn_hsv2rgb", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnHsv2rgbF32),
        ("lpfn_hsv2rgb", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnHsv2rgbVec4F32),
        ("lpfn_hue2rgb", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfnHue2rgbF32),
        (
            "lpfn_psrdnoise",
            &[GlslParamKind::Vec2, GlslParamKind::Vec2, GlslParamKind::Float, GlslParamKind::Vec2, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnPsrdnoise2F32),
        (
            "lpfn_psrdnoise",
            &[GlslParamKind::Vec3, GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::Vec3, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnPsrdnoise3F32),
        ("lpfn_random", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom1F32)
        }
        ("lpfn_random", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom2F32)
        }
        ("lpfn_random", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnRandom3F32)
        }
        ("lpfn_rgb2hsv", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnRgb2hsvF32),
        ("lpfn_rgb2hsv", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnRgb2hsvVec4F32),
        ("lpfn_saturate", &[GlslParamKind::Float]) => Some(BuiltinId::LpLpfnSaturateF32),
        ("lpfn_saturate", &[GlslParamKind::Vec3]) => Some(BuiltinId::LpLpfnSaturateVec3F32),
        ("lpfn_saturate", &[GlslParamKind::Vec4]) => Some(BuiltinId::LpLpfnSaturateVec4F32),
        ("lpfn_snoise", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise1F32)
        }
        ("lpfn_snoise", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise2F32)
        }
        ("lpfn_snoise", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSnoise3F32)
        }
        ("lpfn_srandom", &[GlslParamKind::Float, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom1F32)
        }
        ("lpfn_srandom", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom2F32)
        }
        ("lpfn_srandom", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom3F32)
        }
        (
            "lpfn_srandom3_tile",
            &[GlslParamKind::Vec3, GlslParamKind::Float, GlslParamKind::UInt],
        ) => Some(BuiltinId::LpLpfnSrandom3TileF32),
        ("lpfn_srandom3_vec", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnSrandom3VecF32)
        }
        ("lpfn_worley", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley2F32)
        }
        ("lpfn_worley", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley3F32)
        }
        ("lpfn_worley_value", &[GlslParamKind::Vec2, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley2ValueF32)
        }
        ("lpfn_worley_value", &[GlslParamKind::Vec3, GlslParamKind::UInt]) => {
            Some(BuiltinId::LpLpfnWorley3ValueF32)
        }
        _ => None,
    }
}

/// Resolve for `mode`. Never falls back across modes — see the module docs.
pub fn glsl_math_builtin_id(name: &str, arg_count: usize, mode: Mode) -> Option<BuiltinId> {
    match mode {
        Mode::Q32 => glsl_q32_math_builtin_id(name, arg_count),
        Mode::F32 => glsl_f32_math_builtin_id(name, arg_count),
    }
}

/// Resolve for `mode`. Never falls back across modes — see the module docs.
pub fn lpir_builtin_id(name: &str, arg_count: usize, mode: Mode) -> Option<BuiltinId> {
    match mode {
        Mode::Q32 => lpir_q32_builtin_id(name, arg_count),
        Mode::F32 => lpir_f32_builtin_id(name, arg_count),
    }
}

/// Resolve for `mode`. Never falls back across modes — see the module docs.
pub fn vm_builtin_id(name: &str, arg_count: usize, mode: Mode) -> Option<BuiltinId> {
    match mode {
        Mode::Q32 => vm_q32_builtin_id(name, arg_count),
        Mode::F32 => vm_f32_builtin_id(name, arg_count),
    }
}

/// Resolve for `mode`. Never falls back across modes — see the module docs.
pub fn texture_builtin_id(name: &str, arg_count: usize, mode: Mode) -> Option<BuiltinId> {
    match mode {
        Mode::Q32 => texture_q32_builtin_id(name, arg_count),
        Mode::F32 => texture_f32_builtin_id(name, arg_count),
    }
}

/// Resolve for `mode`. Never falls back across modes — see the module docs.
pub fn glsl_lpfn_builtin_id(name: &str, params: &[GlslParamKind], mode: Mode) -> Option<BuiltinId> {
    match mode {
        Mode::Q32 => glsl_lpfn_q32_builtin_id(name, params),
        Mode::F32 => glsl_lpfn_f32_builtin_id(name, params),
    }
}

#[cfg(test)]
mod glsl_builtin_mapping_tests {
    use super::*;
    use crate::{BuiltinId, Mode};

    #[test]
    fn q32_sin() {
        assert_eq!(
            glsl_q32_math_builtin_id("sin", 1),
            Some(BuiltinId::LpGlslSinQ32)
        );
    }

    #[test]
    fn q32_atan_two_args_is_atan2_import() {
        assert_eq!(
            glsl_q32_math_builtin_id("atan", 2),
            Some(BuiltinId::LpGlslAtan2Q32)
        );
    }

    #[test]
    fn lpir_sqrt() {
        assert_eq!(
            lpir_q32_builtin_id("sqrt", 1),
            Some(BuiltinId::LpLpirFsqrtQ32)
        );
    }

    #[test]
    fn vm_get_fuel() {
        assert_eq!(
            vm_q32_builtin_id("__lp_get_fuel", 0),
            Some(BuiltinId::LpVmGetFuel)
        );
    }

    #[test]
    fn texture_sampler_builtin_id_generation() {
        assert_eq!(
            texture_q32_builtin_id("texture2d_rgba16_unorm", 10),
            Some(BuiltinId::LpTexTexture2dRgba16UnormQ32)
        );
    }

    #[test]
    fn lpfn_fbm_vec2() {
        assert_eq!(
            glsl_lpfn_q32_builtin_id(
                "lpfn_fbm",
                &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt],
            ),
            Some(BuiltinId::LpLpfnFbm2Q32)
        );
    }

    #[test]
    fn f32_resolvers_exist_for_every_family() {
        assert_eq!(
            lpir_f32_builtin_id("sqrt", 1),
            Some(BuiltinId::LpLpirFsqrtF32)
        );
        assert_eq!(
            glsl_lpfn_f32_builtin_id(
                "lpfn_fbm",
                &[GlslParamKind::Vec2, GlslParamKind::Int, GlslParamKind::UInt],
            ),
            Some(BuiltinId::LpLpfnFbm2F32)
        );
    }

    #[test]
    fn mode_independent_builtins_resolve_in_both_modes() {
        // `lpfn_hash` is integer-in/integer-out and carries no mode suffix.
        // Dropping it from the f32 map would make every hash call in a Float
        // shader unresolvable.
        let params = &[GlslParamKind::UInt, GlslParamKind::UInt];
        assert_eq!(
            glsl_lpfn_q32_builtin_id("lpfn_hash", params),
            Some(BuiltinId::LpLpfnHash1)
        );
        assert_eq!(
            glsl_lpfn_f32_builtin_id("lpfn_hash", params),
            Some(BuiltinId::LpLpfnHash1)
        );
    }

    /// The load-bearing invariant: a resolver never answers with the other
    /// mode's builtin. In f32 mode a Q32 id would reinterpret f32 bit patterns
    /// as Q16.16 through a pointer parameter, which nothing downstream can
    /// detect.
    #[test]
    fn no_resolver_ever_crosses_modes() {
        for id in BuiltinId::all() {
            let name = id.fn_name();
            for argc in 0..=10 {
                for (mode, wrong) in [(Mode::F32, Mode::Q32), (Mode::Q32, Mode::F32)] {
                    for got in [
                        glsl_math_builtin_id(name, argc, mode),
                        lpir_builtin_id(name, argc, mode),
                        vm_builtin_id(name, argc, mode),
                        texture_builtin_id(name, argc, mode),
                    ]
                    .into_iter()
                    .flatten()
                    {
                        assert_ne!(
                            got.mode(),
                            Some(wrong),
                            "{name}/{argc} resolved to {got:?} in the wrong mode"
                        );
                    }
                }
            }
        }
    }
}
