//! The LED performance seam: the render thread's wait between two polls of
//! the WS281x RMT driver's completion flag.
//!
//! On silicon it is one call, one no-op hint and one `ret` per spin
//! iteration. The spin only ever waits, so this changes how often it polls,
//! not what it waits for. Under an emulator that engaged it (`led=fast`) the
//! call returns and the hart parks until an interrupt it would wake for; the
//! RMT model, its refill interrupts and the done interrupt still run, so the
//! wire time is billed by emulated time passing.
//!
//! The seam function and its call shim are generated by `lp_seam::seam_fn!`
//! (the LTO rule): never hand-write either.

lp_seam::seam_fn! {
    ws281x_wait_step => fn() {}
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
