//! Parsing and diffing an FP conformance capture from the desk ESP32-S3.
//!
//! Sans-IO on purpose (the `lp-xt/*` convention): everything here takes `&str`
//! and returns a value. The command that reads files and prints the report is
//! `tests/fp_capture.rs`, driven by `just fp-diff <capture>`.
//!
//! # The two aborts
//!
//! Most of a diff tool is bookkeeping. Two conditions are not, and both stop the
//! comparison instead of colouring a row:
//!
//! - **Fingerprint mismatch.** The device regenerates its own inputs from
//!   `lp-xt-fp-vectors` rather than receiving them (M6 D3). If its fingerprint
//!   and the corpus file's disagree, the two sides ran *different vectors* and
//!   every row that follows compares unrelated things. Reporting 5 630
//!   divergences would be worse than useless; it would look like a discovery.
//! - **A missing end sentinel.** A serial capture that stops early is
//!   indistinguishable from one that finished, unless something at the end says
//!   how much there was meant to be. A truncated capture that reads as a pass is
//!   the specific failure this rig is arranged against, so the sentinel is
//!   required and its counts are checked against the rows actually seen.
//!
//! Both are asserted by the unit tests at the bottom of this file, against
//! deliberately damaged fixtures. A rig that cannot fail is not evidence.
//!
//! # The four classifications
//!
//! | Verdict | Prediction | Silicon |
//! |---|---|---|
//! | `Agree` | concrete | the same |
//! | `Diverge` | concrete | different — a finding for P6 |
//! | `Resolved` | `UNKNOWN:<field>` | a value, which is the campaign's product |
//! | `Skipped` | either | the harness deliberately did not run it |
//!
//! `Resolved` is not a pass and not a failure: it is the answer to a question,
//! and P6 turns a consistent set of them into a policy field with a citation.

use std::collections::BTreeMap;
use std::fmt;

/// What the emulator predicted for one vector, as it appears in a corpus file.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Prediction {
    /// A concrete answer: IEEE-fixed, resolved policy, or a manual citation.
    Bits(u32),
    /// The instruction faulted; the value is the EXCCAUSE.
    Trap(u32),
    /// The prediction needs a policy field nothing has measured yet.
    Unknown(String),
}

impl Prediction {
    pub fn render(&self) -> String {
        match self {
            Prediction::Bits(b) => format!("{b:#010x}"),
            Prediction::Trap(c) => format!("TRAP:{c}"),
            Prediction::Unknown(f) => format!("UNKNOWN:{f}"),
        }
    }

    /// Parse the `result` column of a corpus row.
    pub fn parse(s: &str) -> Result<Prediction, CaptureError> {
        if let Some(f) = s.strip_prefix("UNKNOWN:") {
            Ok(Prediction::Unknown(f.to_string()))
        } else if let Some(c) = s.strip_prefix("TRAP:") {
            c.parse()
                .map(Prediction::Trap)
                .map_err(|_| CaptureError::Malformed(format!("bad trap cause {c:?}")))
        } else {
            u32::from_str_radix(s.trim_start_matches("0x"), 16)
                .map(Prediction::Bits)
                .map_err(|_| CaptureError::Malformed(format!("bad result bits {s:?}")))
        }
    }
}

/// Anything that makes a capture or a corpus file unusable.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum CaptureError {
    /// The device and the corpus were generated by different `lp-xt-fp-vectors`.
    FingerprintMismatch {
        device: u32,
        host: u32,
    },
    /// The capture never reached its end sentinel.
    Truncated {
        family: Option<String>,
    },
    /// The sentinel disagrees with the number of rows actually captured.
    CountMismatch {
        family: String,
        declared: u32,
        seen: u32,
    },
    /// No fingerprint line at all — usually a capture of the wrong firmware.
    NoFingerprint,
    Malformed(String),
}

impl fmt::Display for CaptureError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CaptureError::FingerprintMismatch { device, host } => write!(
                f,
                "fingerprint mismatch: device {device:#010x}, host {host:#010x}. The two \
                 sides generated DIFFERENT vectors, so every comparison below would be \
                 meaningless. Reflash from this commit."
            ),
            CaptureError::Truncated { family } => match family {
                Some(fam) => write!(
                    f,
                    "capture is truncated: family {fam} started but never reached its \
                     END sentinel"
                ),
                None => write!(
                    f,
                    "capture is truncated: no END-ALL sentinel. A short capture is an \
                     error, not a partial pass."
                ),
            },
            CaptureError::CountMismatch {
                family,
                declared,
                seen,
            } => write!(
                f,
                "{family}: the sentinel declares {declared} rows but {seen} were \
                 captured — lines were lost in transit"
            ),
            CaptureError::NoFingerprint => {
                write!(f, "no `fingerprint=` line: is this an FPCONF capture?")
            }
            CaptureError::Malformed(m) => write!(f, "malformed: {m}"),
        }
    }
}

impl std::error::Error for CaptureError {}

/// One vector's answer from silicon.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum DeviceResult {
    Value {
        bits: u32,
        fsr: u32,
    },
    /// The harness deliberately did not run this one (the divide and square-root
    /// pseudo-ops, whose helper semantics no document states).
    Skipped,
}

/// One estimate-table sweep: every distinct output over one `(sign, exponent)`
/// plane of the significand space, run-length encoded on the device.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct TableSweep {
    /// `recip0.s`, `rsqrt0.s`, `sqrt0.s`, or `div0.s`.
    pub op: String,
    /// The biased exponent of every input in the sweep.
    pub exp: u32,
    /// The sign bit of every input in the sweep.
    pub sign: u32,
    /// `(first significand, length, result bits)` — contiguous, covering the
    /// full 2²³ space unless [`TableSweep::aborted`].
    pub runs: Vec<(u32, u32, u32)>,
    /// The device hit its run cap: the output was not a step function over
    /// this plane, and `runs` is only its prefix. An aborted sweep must never
    /// be encoded as a table.
    pub aborted: bool,
}

/// A parsed capture: the header facts P6 copies into a provenance block, plus
/// every row, keyed by family and index.
#[derive(Clone, Debug)]
pub struct Capture {
    pub fingerprint: u32,
    /// The helper-grid fingerprint, printed by `helpers`-mode captures.
    pub helpers_fingerprint: Option<u32>,
    /// The **second-round** helper-grid fingerprint, printed alongside the
    /// first by `helpers`-mode captures. Separate rather than overloading
    /// `helpers_fingerprint`: the two grids are different generators, a
    /// capture can legitimately carry one, the other, or both, and silently
    /// checking the wrong one would defeat the whole point of printing them
    /// (M6 D3 — device and host must prove they used the same generator).
    pub helpers2_fingerprint: Option<u32>,
    pub commit: Option<String>,
    pub cpenable_before: Option<u32>,
    pub cpenable_after: Option<u32>,
    pub fcr_reset: Option<u32>,
    pub fsr_reset: Option<u32>,
    pub mode: Option<String>,
    /// `family -> index -> result`, in index order. Helper grids (`h_maddn`,
    /// …) parse into the same map — the row shape is identical, and which keys
    /// mean "conformance family" vs "characterization grid" is the caller's
    /// business.
    pub rows: BTreeMap<String, BTreeMap<u32, DeviceResult>>,
    /// Per-family digest the device computed, for a cheap "did anything move".
    pub digests: BTreeMap<String, u32>,
    /// The sixteen `const.s` outputs, from a `helpers`-mode capture.
    pub const_s: Vec<(u8, u32)>,
    /// Estimate-table sweeps, from a `tables`-mode capture.
    pub tables: Vec<TableSweep>,
}

impl Capture {
    pub fn family_names(&self) -> impl Iterator<Item = &str> {
        self.rows.keys().map(String::as_str)
    }
}

/// Parse a serial capture.
///
/// Tolerant of everything that is not an `[FPCONF]` line — a real capture is
/// preceded by espflash's own chatter and the boot ROM's — and strict about
/// everything that is.
pub fn parse_capture(text: &str) -> Result<Capture, CaptureError> {
    let mut cap = Capture {
        fingerprint: 0,
        helpers_fingerprint: None,
        helpers2_fingerprint: None,
        commit: None,
        cpenable_before: None,
        cpenable_after: None,
        fcr_reset: None,
        fsr_reset: None,
        mode: None,
        rows: BTreeMap::new(),
        digests: BTreeMap::new(),
        const_s: Vec::new(),
        tables: Vec::new(),
    };
    let mut have_fingerprint = false;
    let mut open_family: Option<String> = None;
    let mut open_table: Option<TableSweep> = None;
    let mut ended = false;
    // Declared counts from each family's END sentinel.
    let mut declared: Vec<(String, u32)> = Vec::new();

    for line in text.lines() {
        let Some(rest) = line.split_once("[FPCONF]").map(|(_, r)| r.trim()) else {
            continue;
        };
        let mut words = rest.split_whitespace();
        let Some(head) = words.next() else { continue };

        // Header facts. Keyed on the prefix rather than a whole-word match
        // because several of them are `key=value` in the first position.
        if head == "build" {
            cap.commit = kv(rest, "commit=").map(str::to_string);
        } else if head == "cpenable" {
            cap.cpenable_before = kv(rest, "before=").and_then(parse_hex);
            cap.cpenable_after = kv(rest, "after=").and_then(parse_hex);
        } else if head.starts_with("fcr-reset=") {
            cap.fcr_reset = kv(rest, "fcr-reset=").and_then(parse_hex);
            cap.fsr_reset = kv(rest, "fsr-reset=").and_then(parse_hex);
        } else if head.starts_with("fingerprint=") {
            cap.fingerprint = kv(rest, "fingerprint=")
                .and_then(parse_hex)
                .ok_or_else(|| CaptureError::Malformed(format!("bad fingerprint {rest:?}")))?;
            have_fingerprint = true;
        } else if head.starts_with("helpers2-fingerprint=") {
            cap.helpers2_fingerprint = kv(rest, "helpers2-fingerprint=").and_then(parse_hex);
        } else if head.starts_with("helpers-fingerprint=") {
            cap.helpers_fingerprint = kv(rest, "helpers-fingerprint=").and_then(parse_hex);
        } else if head.starts_with("mode=") {
            cap.mode = kv(rest, "mode=").map(str::to_string);
        }

        if head == "CONST" {
            let idx: u8 = words
                .next()
                .and_then(|w| w.parse().ok())
                .ok_or_else(|| CaptureError::Malformed(format!("CONST has no index: {rest:?}")))?;
            let bits = words
                .next()
                .and_then(parse_hex)
                .ok_or_else(|| CaptureError::Malformed(format!("CONST has no value: {rest:?}")))?;
            cap.const_s.push((idx, bits));
        } else if head == "TABLE" {
            // A TABLE opening while another is open means the previous sweep
            // never reached its END line — a truncation, not a formatting
            // nicety.
            if let Some(t) = open_table.take() {
                return Err(CaptureError::Truncated {
                    family: Some(format!("table {} exp={} sign={}", t.op, t.exp, t.sign)),
                });
            }
            open_table = Some(TableSweep {
                op: kv(rest, "op=")
                    .ok_or_else(|| CaptureError::Malformed(format!("TABLE has no op: {rest:?}")))?
                    .to_string(),
                exp: kv(rest, "exp=")
                    .and_then(|v| v.parse().ok())
                    .ok_or_else(|| {
                        CaptureError::Malformed(format!("TABLE has no exp: {rest:?}"))
                    })?,
                // Older captures predate the sign sweeps; absent means 0.
                sign: kv(rest, "sign=").and_then(|v| v.parse().ok()).unwrap_or(0),
                runs: Vec::new(),
                aborted: false,
            });
        } else if head == "T" {
            let Some(table) = open_table.as_mut() else {
                return Err(CaptureError::Malformed(format!(
                    "T line outside a TABLE: {rest:?}"
                )));
            };
            // `T <op> <exp>` prefix, then `start:len:value` cells.
            let cells = words.skip(2);
            for cell in cells {
                let mut parts = cell.split(':');
                let (Some(start), Some(len), Some(value)) = (
                    parts.next().and_then(parse_hex),
                    parts.next().and_then(parse_hex),
                    parts.next().and_then(parse_hex),
                ) else {
                    return Err(CaptureError::Malformed(format!("bad run cell {cell:?}")));
                };
                table.runs.push((start, len, value));
            }
        } else if head == "FAMILY" {
            open_family = words.next().map(str::to_string);
        } else if head == "D" {
            let family = words.next().ok_or_else(|| {
                CaptureError::Malformed(format!("D line has no family: {rest:?}"))
            })?;
            let first: u32 = words
                .next()
                .and_then(|w| w.parse().ok())
                .ok_or_else(|| CaptureError::Malformed(format!("D line has no index: {rest:?}")))?;
            let slot = cap.rows.entry(family.to_string()).or_default();
            for (n, cell) in words.enumerate() {
                let index = first + n as u32;
                slot.insert(index, parse_cell(cell)?);
            }
        } else if head == "DIGEST" {
            let family = words.next().unwrap_or_default().to_string();
            if let Some(d) = words.next().and_then(parse_hex) {
                cap.digests.insert(family, d);
            }
        } else if head == "END" {
            if let Some(table_op) = kv(rest, "table=") {
                let Some(mut t) = open_table.take() else {
                    return Err(CaptureError::Malformed(format!(
                        "END table without a TABLE: {rest:?}"
                    )));
                };
                if t.op != table_op {
                    return Err(CaptureError::Malformed(format!(
                        "END table={table_op} closes TABLE op={}",
                        t.op
                    )));
                }
                let runs: u32 =
                    kv(rest, "runs=")
                        .and_then(|v| v.parse().ok())
                        .ok_or_else(|| {
                            CaptureError::Malformed(format!("END table has no runs: {rest:?}"))
                        })?;
                if t.runs.len() as u32 != runs {
                    return Err(CaptureError::CountMismatch {
                        family: format!("table {} exp={} sign={}", t.op, t.exp, t.sign),
                        declared: runs,
                        seen: t.runs.len() as u32,
                    });
                }
                t.aborted = kv(rest, "aborted=") == Some("1");
                cap.tables.push(t);
            } else if let (Some(family), Some(count)) = (
                kv(rest, "family="),
                kv(rest, "count=").and_then(|c| c.parse().ok()),
            ) {
                declared.push((family.to_string(), count));
                open_family = None;
            }
        } else if head == "END-ALL" {
            ended = true;
        }
    }

    if !have_fingerprint {
        return Err(CaptureError::NoFingerprint);
    }
    if let Some(t) = open_table {
        return Err(CaptureError::Truncated {
            family: Some(format!("table {} exp={} sign={}", t.op, t.exp, t.sign)),
        });
    }
    if !ended {
        return Err(CaptureError::Truncated {
            family: open_family,
        });
    }
    for (family, count) in declared {
        let seen = cap.rows.get(&family).map_or(0, BTreeMap::len) as u32;
        if seen != count {
            return Err(CaptureError::CountMismatch {
                family,
                declared: count,
                seen,
            });
        }
    }
    Ok(cap)
}

fn parse_cell(cell: &str) -> Result<DeviceResult, CaptureError> {
    if cell == "skip" {
        return Ok(DeviceResult::Skipped);
    }
    let (bits, fsr) = cell
        .split_once(':')
        .ok_or_else(|| CaptureError::Malformed(format!("result cell {cell:?} has no `:`")))?;
    let bits = u32::from_str_radix(bits, 16)
        .map_err(|_| CaptureError::Malformed(format!("bad result {bits:?}")))?;
    let fsr = u32::from_str_radix(fsr, 16)
        .map_err(|_| CaptureError::Malformed(format!("bad fsr {fsr:?}")))?;
    Ok(DeviceResult::Value { bits, fsr })
}

fn kv<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let at = line.find(key)? + key.len();
    Some(line[at..].split_whitespace().next().unwrap_or(""))
}

fn parse_hex(s: &str) -> Option<u32> {
    u32::from_str_radix(s.trim_start_matches("0x"), 16).ok()
}

/// One family's committed predictions.
#[derive(Clone, Debug)]
pub struct Predictions {
    pub family: String,
    pub fingerprint: u32,
    /// `index -> (rendered operands, result prediction, FSR prediction)`.
    pub rows: Vec<(u32, String, Prediction, Prediction)>,
}

/// Parse a corpus file from `lp-xt-emu/tests/fixtures/fp/`.
pub fn parse_predictions(family: &str, text: &str) -> Result<Predictions, CaptureError> {
    let mut fingerprint = None;
    let mut rows = Vec::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# generator:") {
            fingerprint = rest.split_whitespace().find_map(parse_hex_token);
        }
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let (lhs, rhs) = line
            .split_once("->")
            .ok_or_else(|| CaptureError::Malformed(format!("corpus row has no arrow: {line:?}")))?;
        let index: u32 = lhs
            .split_whitespace()
            .next()
            .and_then(|w| w.parse().ok())
            .ok_or_else(|| CaptureError::Malformed(format!("corpus row has no index: {line:?}")))?;
        let mut cols = rhs.split_whitespace();
        let result = cols.next().ok_or_else(|| {
            CaptureError::Malformed(format!("corpus row has no result: {line:?}"))
        })?;
        let fsr = cols.next().ok_or_else(|| {
            CaptureError::Malformed(format!("corpus row has no fsr column: {line:?}"))
        })?;
        rows.push((
            index,
            lhs.trim().to_string(),
            Prediction::parse(result)?,
            Prediction::parse(fsr)?,
        ));
    }
    Ok(Predictions {
        family: family.to_string(),
        fingerprint: fingerprint.ok_or(CaptureError::NoFingerprint)?,
        rows,
    })
}

fn parse_hex_token(t: &str) -> Option<u32> {
    let t = t.trim_end_matches(',');
    t.starts_with("0x").then(|| parse_hex(t)).flatten()
}

/// What one row's comparison came to.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Verdict {
    Agree,
    Diverge,
    Resolved,
    Skipped,
}

/// One row worth writing down: a divergence, or an answer to an open question.
#[derive(Clone, Debug)]
pub struct Row {
    pub index: u32,
    pub verdict: Verdict,
    pub operands: String,
    pub predicted: Prediction,
    /// The predicted FSR column.
    pub predicted_fsr: Prediction,
    pub silicon: DeviceResult,
}

/// One family's comparison.
#[derive(Clone, Debug)]
pub struct FamilyReport {
    pub family: String,
    pub compared: usize,
    pub agree: usize,
    pub diverge: usize,
    pub resolved: usize,
    pub skipped: usize,
    /// Every divergence, in index order. Never sampled — a divergence the report
    /// mentions but does not show is a divergence nobody will look at.
    pub divergences: Vec<Row>,
    /// Which policy field each resolved row was waiting on, and how many.
    pub resolved_by_field: BTreeMap<String, usize>,
}

/// Compare one family's predictions against the capture.
///
/// Rows the capture does not contain are simply not compared — a subset run is a
/// legitimate mode ([`crate::fp_capture`] is used for smoke runs as well as the
/// full campaign) and the sentinel check in [`parse_capture`] is what catches an
/// *unintended* short capture.
pub fn diff(predictions: &Predictions, capture: &Capture) -> Result<FamilyReport, CaptureError> {
    if capture.fingerprint != predictions.fingerprint {
        return Err(CaptureError::FingerprintMismatch {
            device: capture.fingerprint,
            host: predictions.fingerprint,
        });
    }
    let empty = BTreeMap::new();
    let device = capture.rows.get(&predictions.family).unwrap_or(&empty);
    let mut report = FamilyReport {
        family: predictions.family.clone(),
        compared: 0,
        agree: 0,
        diverge: 0,
        resolved: 0,
        skipped: 0,
        divergences: Vec::new(),
        resolved_by_field: BTreeMap::new(),
    };

    for (index, operands, predicted, predicted_fsr) in &predictions.rows {
        let Some(silicon) = device.get(index).copied() else {
            continue;
        };
        report.compared += 1;
        let verdict = match (predicted, silicon) {
            (_, DeviceResult::Skipped) => {
                report.skipped += 1;
                Verdict::Skipped
            }
            (Prediction::Unknown(field), DeviceResult::Value { .. }) => {
                report.resolved += 1;
                *report.resolved_by_field.entry(field.clone()).or_insert(0) += 1;
                Verdict::Resolved
            }
            (Prediction::Bits(want), DeviceResult::Value { bits, fsr }) if *want == bits => {
                // The result matches; the FSR column decides the rest. An
                // UNKNOWN FSR prediction (pre-campaign corpora) does not
                // count against the row.
                match predicted_fsr {
                    Prediction::Bits(want_fsr) if *want_fsr != fsr => {
                        report.diverge += 1;
                        Verdict::Diverge
                    }
                    _ => {
                        report.agree += 1;
                        Verdict::Agree
                    }
                }
            }
            _ => {
                report.diverge += 1;
                Verdict::Diverge
            }
        };
        if verdict == Verdict::Diverge {
            report.divergences.push(Row {
                index: *index,
                verdict,
                operands: operands.clone(),
                predicted: predicted.clone(),
                predicted_fsr: predicted_fsr.clone(),
                silicon,
            });
        }
    }
    Ok(report)
}

impl fmt::Display for FamilyReport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "{:<12} compared={:<6} AGREE={:<6} DIVERGE={:<5} RESOLVED={:<6} SKIPPED={}",
            self.family, self.compared, self.agree, self.diverge, self.resolved, self.skipped
        )?;
        for (field, n) in &self.resolved_by_field {
            writeln!(f, "               resolved {n:>6}  {field}")?;
        }
        for row in &self.divergences {
            let silicon = match row.silicon {
                DeviceResult::Value { bits, fsr } => format!("{bits:#010x} fsr={fsr:#010x}"),
                DeviceResult::Skipped => "skip".to_string(),
            };
            writeln!(
                f,
                "  DIVERGE {}  predicted={} fsr={}  silicon={}",
                row.operands,
                row.predicted.render(),
                row.predicted_fsr.render(),
                silicon
            )?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal but structurally complete capture: two families, one skip.
    const GOOD: &str = "\
espflash noise that must be ignored
[FPCONF] BEGIN
[FPCONF] build commit=abcdef123456 dirty=false profile=release-esp32s3
[FPCONF] cpenable before=0x00000001 after=0x00000001
[FPCONF] fcr-reset=0x00000000 fsr-reset=0x00000000
[FPCONF] fingerprint=0xa0a36dc3 total=5630
[FPCONF] mode=families family=all limit=0
[FPCONF] FAMILY signed_zero label=F4 count=4 of=206
[FPCONF] D signed_zero 00000 80000000:00000000 00000000:00000000 00000000:00000000 deadbeef:00000400
[FPCONF] DIGEST signed_zero 0x12345678 rows=4
[FPCONF] END family=signed_zero count=4
[FPCONF] FAMILY div_sqrt label=F5 count=2 of=1296
[FPCONF] D div_sqrt 00000 3f800000:00000000 skip
[FPCONF] DIGEST div_sqrt 0x87654321 rows=2
[FPCONF] END family=div_sqrt count=2
[FPCONF] END-ALL families=2 vectors=6
[FPCONF] done
";

    const CORPUS: &str = "\
# M6 Xtensa FP conformance corpus — F4 signed_zero
# generator:  lp-xt-fp-vectors, fingerprint 0xa0a36dc3, 206 vectors
# columns: index op a b c imm fcr -> result fsr
00000 neg.s      0x00000000 0x00000000 0x00000000  0 0 -> 0x80000000 UNKNOWN:fsr_flag_bits
00001 abs.s      0x00000000 0x00000000 0x00000000  0 0 -> 0x00000000 UNKNOWN:fsr_flag_bits
00002 mov.s      0x00000000 0x00000000 0x00000000  0 0 -> 0x11111111 UNKNOWN:fsr_flag_bits
00003 add.s      0x00000000 0x00000000 0x00000000  0 0 -> UNKNOWN:nan_propagation UNKNOWN:fsr_flag_bits
";

    #[test]
    fn a_complete_capture_parses_with_its_header_facts() {
        let c = parse_capture(GOOD).expect("parses");
        assert_eq!(c.fingerprint, 0xA0A3_6DC3);
        assert_eq!(c.commit.as_deref(), Some("abcdef123456"));
        assert_eq!(c.cpenable_before, Some(1));
        assert_eq!(c.cpenable_after, Some(1));
        assert_eq!(c.fcr_reset, Some(0));
        assert_eq!(c.fsr_reset, Some(0));
        assert_eq!(c.mode.as_deref(), Some("families"));
        assert_eq!(c.rows["signed_zero"].len(), 4);
        assert_eq!(
            c.rows["signed_zero"][&0],
            DeviceResult::Value {
                bits: 0x8000_0000,
                fsr: 0
            }
        );
        assert_eq!(c.rows["div_sqrt"][&1], DeviceResult::Skipped);
        assert_eq!(c.digests["signed_zero"], 0x1234_5678);
    }

    #[test]
    fn the_four_verdicts_land_where_they_should() {
        let cap = parse_capture(GOOD).unwrap();
        let pred = parse_predictions("signed_zero", CORPUS).unwrap();
        let r = diff(&pred, &cap).unwrap();
        assert_eq!(r.compared, 4);
        assert_eq!(r.agree, 2, "rows 0 and 1 match");
        assert_eq!(r.diverge, 1, "row 2 predicted 0x11111111");
        assert_eq!(r.resolved, 1, "row 3 was UNKNOWN and silicon answered");
        assert_eq!(r.divergences.len(), 1);
        assert_eq!(r.divergences[0].index, 2);
        assert_eq!(r.resolved_by_field["nan_propagation"], 1);
    }

    /// The load-bearing handshake. Both sides regenerate their own vectors, so a
    /// fingerprint disagreement means they ran different inputs and the whole
    /// comparison is void — it must abort, not produce a wall of divergences
    /// that looks like a discovery.
    #[test]
    fn a_fingerprint_mismatch_aborts_rather_than_diverging() {
        let cap = parse_capture(&GOOD.replace("0xa0a36dc3", "0xdeadbeef")).unwrap();
        let pred = parse_predictions("signed_zero", CORPUS).unwrap();
        let err = diff(&pred, &cap).expect_err("must abort");
        assert_eq!(
            err,
            CaptureError::FingerprintMismatch {
                device: 0xDEAD_BEEF,
                host: 0xA0A3_6DC3,
            }
        );
    }

    /// The other one. Test the teardown: a rig that cannot fail is not evidence.
    #[test]
    fn a_truncated_capture_is_rejected_not_read_as_a_partial_pass() {
        // Cut the transcript mid-family, exactly as a lost serial connection or
        // an over-eager monitor kill would.
        let cut = GOOD.split("[FPCONF] DIGEST div_sqrt").next().unwrap();
        let err = parse_capture(cut).expect_err("must reject");
        assert_eq!(
            err,
            CaptureError::Truncated {
                family: Some("div_sqrt".to_string())
            }
        );

        // And the subtler one: the sentinel arrives but rows were dropped on the
        // way. Deleting a whole `D` line loses four rows against a count that
        // still says four.
        let holed: String = GOOD
            .lines()
            .filter(|l| !l.contains("D signed_zero"))
            .collect::<Vec<_>>()
            .join("\n");
        let err = parse_capture(&holed).expect_err("must reject");
        assert_eq!(
            err,
            CaptureError::CountMismatch {
                family: "signed_zero".to_string(),
                declared: 4,
                seen: 0,
            }
        );
    }

    #[test]
    fn a_capture_of_the_wrong_firmware_says_so() {
        let err = parse_capture("[INIT] fw-esp32s3 boot\n[INIT] ready\n").expect_err("must reject");
        assert_eq!(err, CaptureError::NoFingerprint);
    }

    /// A structurally complete tables-mode capture: two sweeps, one aborted.
    const TABLES: &str = "\
[FPCONF] BEGIN
[FPCONF] fingerprint=0xa0a36dc3 total=5630
[FPCONF] mode=tables family=all limit=0
[FPCONF] TABLE op=recip0.s exp=127 sign=0 significand-bits=23
[FPCONF] T recip0.s 00127 00000000:00010000:3f800000 00010000:00010000:3f7e0000
[FPCONF] T recip0.s 00127 00020000:007e0000:3f7c0000
[FPCONF] END table=recip0.s exp=127 sign=0 runs=3 aborted=0
[FPCONF] TABLE op=rsqrt0.s exp=255 sign=0 significand-bits=23
[FPCONF] T rsqrt0.s 00255 00000000:00000001:7fc00000 00000001:00000001:7fc00001
[FPCONF] END table=rsqrt0.s exp=255 sign=0 runs=2 aborted=1
[FPCONF] END-ALL tables=2 sweeps=2
[FPCONF] done
";

    #[test]
    fn a_tables_capture_parses_into_sweeps_with_their_runs() {
        let c = parse_capture(TABLES).expect("parses");
        assert_eq!(c.tables.len(), 2);
        let t = &c.tables[0];
        assert_eq!(
            (t.op.as_str(), t.exp, t.sign, t.aborted),
            ("recip0.s", 127, 0, false)
        );
        assert_eq!(
            t.runs,
            vec![
                (0x0000_0000, 0x0001_0000, 0x3F80_0000),
                (0x0001_0000, 0x0001_0000, 0x3F7E_0000),
                (0x0002_0000, 0x007E_0000, 0x3F7C_0000),
            ]
        );
        // An aborted sweep carries its flag, so an extraction that consumed it
        // as a complete table would be caught by the caller's own check.
        assert!(c.tables[1].aborted);
    }

    /// The same teardown discipline as the family rows: a sweep whose END never
    /// arrived, or whose declared run count disagrees, is an error — not a
    /// smaller table.
    #[test]
    fn a_damaged_tables_capture_is_rejected() {
        let cut = TABLES.replace(
            "[FPCONF] END table=recip0.s exp=127 sign=0 runs=3 aborted=0\n",
            "",
        );
        let err = parse_capture(&cut).expect_err("must reject");
        assert!(
            matches!(err, CaptureError::Truncated { family: Some(f) } if f.contains("recip0.s")),
            "a TABLE without an END is a truncation"
        );

        let holed = TABLES.replace("[FPCONF] T recip0.s 00127 00020000:007e0000:3f7c0000\n", "");
        let err = parse_capture(&holed).expect_err("must reject");
        assert_eq!(
            err,
            CaptureError::CountMismatch {
                family: "table recip0.s exp=127 sign=0".to_string(),
                declared: 3,
                seen: 2,
            }
        );
    }

    /// A helpers-mode capture reuses the family row shape, plus CONST lines and
    /// its own fingerprint.
    #[test]
    fn a_helpers_capture_parses_const_rows_and_grids() {
        let text = "\
[FPCONF] BEGIN
[FPCONF] fingerprint=0xa0a36dc3 total=5630
[FPCONF] mode=helpers family=all limit=0
[FPCONF] helpers-fingerprint=0x9715768f total=5328
[FPCONF] CONST 00 00000000
[FPCONF] CONST 01 3f800000
[FPCONF] FAMILY h_nexp01 label=H count=2 of=144
[FPCONF] D h_nexp01 00000 3f800000:00000000 40000000:00000000
[FPCONF] DIGEST h_nexp01 0xcafef00d rows=2
[FPCONF] END family=h_nexp01 count=2
[FPCONF] END-ALL helpers=1 vectors=2
";
        let c = parse_capture(text).expect("parses");
        assert_eq!(c.helpers_fingerprint, Some(0x9715_768F));
        assert_eq!(c.const_s, vec![(0, 0x0000_0000), (1, 0x3F80_0000)]);
        assert_eq!(c.rows["h_nexp01"].len(), 2);
    }

    /// A subset run is legitimate — the smoke run is one — so rows the capture
    /// does not contain are skipped rather than counted as divergences.
    #[test]
    fn a_partial_capture_compares_only_what_it_contains() {
        let cap = parse_capture(GOOD).unwrap();
        let mut corpus = CORPUS.to_string();
        corpus.push_str(
            "00004 sub.s      0x00000000 0x00000000 0x00000000  0 0 -> 0x00000000 UNKNOWN:fsr_flag_bits\n",
        );
        let pred = parse_predictions("signed_zero", &corpus).unwrap();
        let r = diff(&pred, &cap).unwrap();
        assert_eq!(r.compared, 4, "the fifth row was never captured");
    }
}
