//! Generates the catalog file tables: every file of every entry under
//! `../../catalog/<bucket>/<slug>/`, as `include_bytes!` entries the
//! registry (`app/home/embedded_example.rs`) types at runtime through the
//! manifest parser. Adding content is dropping a folder under a bucket —
//! no Rust edit, no hand-maintained list.
//!
//! Precedent: `lp-app/lpa-palettes/build.rs` (the palette catalog), whose
//! "a missing directory is an empty table" contract this keeps per bucket
//! (`templates/` does not exist yet; the table simply has no rows for it).
//!
//! Emitted shape (`$OUT_DIR/catalog_files.generated.rs`):
//!
//! ```text
//! pub static CATALOG_FILES: &[(&str, &str, &[(&str, &[u8])])] = &[
//!     ("projects", "fiber-headband", &[
//!         ("project.json", include_bytes!("/abs/.../project.json")),
//!         ("module.json", include_bytes!(...)),
//!         // remaining files sorted by relative path
//!     ]),
//!     // buckets in BUCKET_ORDER, slugs sorted within a bucket
//! ];
//! ```
//!
//! Rules: buckets are emitted in [`BUCKET_ORDER`] (the home page's display
//! order); slugs sort within a bucket; within an entry `project.json` comes
//! first and `module.json` second (deploy order — the registry and the
//! `every_example_ships_the_two_container_files` test rely on it), the rest
//! sorted by relative path. Every regular file under the entry is included
//! (entries nest: small-dome has `dome/` and `doors/`; a per-entry README
//! travels with a remix, which is fine). Dotfiles are skipped. A directory
//! under a bucket with no `project.json` is a build error naming the
//! directory — an entry is a project or it is a mistake.

use std::fs;
use std::path::{Path, PathBuf};

/// Bucket directories in display order: real pieces first, then patterns,
/// then templates (reserved; absent today).
const BUCKET_ORDER: &[&str] = &["projects", "patterns", "templates"];

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let catalog_root = manifest_dir.join("../../catalog");
    println!("cargo:rerun-if-changed={}", catalog_root.display());

    let mut code = String::from(
        "// Generated by lpa-studio-core/build.rs from the catalog/ tree — do not edit.\n\
         pub static CATALOG_FILES: &[(&str, &str, &[(&str, &[u8])])] = &[\n",
    );
    for bucket in BUCKET_ORDER {
        let bucket_dir = catalog_root.join(bucket);
        println!("cargo:rerun-if-changed={}", bucket_dir.display());
        if !bucket_dir.is_dir() {
            continue;
        }
        for entry_dir in sorted_dirs(&bucket_dir) {
            println!("cargo:rerun-if-changed={}", entry_dir.display());
            let slug = entry_dir
                .file_name()
                .expect("entry dir has a name")
                .to_string_lossy()
                .into_owned();
            if !entry_dir.join("project.json").is_file() {
                panic!(
                    "catalog entry {} has no project.json — every directory under \
                     catalog/{bucket}/ must be a project (test rigs belong under projects/test/)",
                    entry_dir.display()
                );
            }
            let mut files = Vec::new();
            collect_files(&entry_dir, &entry_dir, &mut files);
            files.sort_by(|a, b| {
                deploy_rank(&a.0)
                    .cmp(&deploy_rank(&b.0))
                    .then(a.0.cmp(&b.0))
            });

            code.push_str(&format!("    ({bucket:?}, {slug:?}, &[\n"));
            for (relative, absolute) in &files {
                code.push_str(&format!(
                    "        ({relative:?}, include_bytes!({absolute:?})),\n"
                ));
            }
            code.push_str("    ]),\n");
        }
    }
    code.push_str("];\n");

    let out_file = out_dir.join("catalog_files.generated.rs");
    fs::write(&out_file, code)
        .unwrap_or_else(|error| panic!("write {}: {error}", out_file.display()));
}

/// The two container files deploy first, in this order; everything else
/// follows sorted by path.
fn deploy_rank(relative: &str) -> u8 {
    match relative {
        "project.json" => 0,
        "module.json" => 1,
        _ => 2,
    }
}

/// Immediate subdirectories of `dir`, sorted by name, dotfiles skipped.
fn sorted_dirs(dir: &Path) -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("read {}: {error}", dir.display()))
        .map(|entry| entry.expect("dir entry").path())
        .filter(|path| path.is_dir() && !is_hidden(path))
        .collect();
    dirs.sort();
    dirs
}

/// Every regular file under `dir`, recursively, as `(path relative to
/// root with `/` separators, absolute path)`. Dotfiles are skipped.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    for entry in fs::read_dir(dir).unwrap_or_else(|error| panic!("read {}: {error}", dir.display()))
    {
        let path = entry.expect("dir entry").path();
        if is_hidden(&path) {
            continue;
        }
        if path.is_dir() {
            collect_files(root, &path, out);
            continue;
        }
        if !path.is_file() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let relative = path
            .strip_prefix(root)
            .expect("walked path is under its entry")
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");
        // Absolute paths sidestep include_bytes!'s relative-path resolution
        // for a file brought in via `include!(concat!(OUT_DIR, ..))`.
        let absolute = fs::canonicalize(&path).unwrap_or(path.clone());
        out.push((relative, absolute.to_string_lossy().into_owned()));
    }
}

fn is_hidden(path: &Path) -> bool {
    path.file_name()
        .is_some_and(|name| name.to_string_lossy().starts_with('.'))
}
