//! Preset-dictionary round trips: streams `inflate` must decode with
//! `buf[..start]` already holding history the compressor was allowed to
//! reference. The vectors are generated by `tests/fixtures/gen_preset_dict_vectors.py`
//! against Python's own `zlib` (an independent implementation, not
//! `miniz_oxide`) using `zdict=`, and committed — see that script's doc
//! comment for how to regenerate them.

const FIRMWARE: &[u8] =
    include_bytes!("../../../lp-fw/bootloaders/esp32c6-bootloader-idf-v5.5.1.bin");

/// `name.dict` + `name.deflate` decode to `name.expect`, with the dict
/// bytes preloaded into `buf[..dict.len()]`.
fn check_case(name: &str, dict: &[u8], deflate: &[u8], expect: &[u8]) {
    let mut buf = vec![0u8; dict.len() + expect.len()];
    buf[..dict.len()].copy_from_slice(dict);
    let n = lp_deflate::inflate(deflate, &mut buf, dict.len())
        .unwrap_or_else(|e| panic!("{name}: inflate failed: {e:?}"));
    assert_eq!(n, expect.len(), "{name}: wrong output length");
    assert_eq!(
        &buf[dict.len()..dict.len() + n],
        expect,
        "{name}: output mismatch"
    );
}

macro_rules! fixture_case {
    ($test_name:ident, $fixture_name:literal) => {
        #[test]
        fn $test_name() {
            check_case(
                $fixture_name,
                include_bytes!(concat!("fixtures/", $fixture_name, ".dict")),
                include_bytes!(concat!("fixtures/", $fixture_name, ".deflate")),
                include_bytes!(concat!("fixtures/", $fixture_name, ".expect")),
            );
        }
    };
}

fixture_case!(text_small, "text-small");
fixture_case!(empty_payload, "empty-payload");
fixture_case!(no_dictionary, "no-dictionary");

// The dictionary is a full 32 KiB window and the only place the payload's
// leading bytes appear is at the dictionary's very first byte — i.e. the
// compressor had to use the largest distance RFC 1951 can express (32768)
// for this to decode at all.
fixture_case!(max_distance, "max-distance");

/// The real bootloader image, sliced into 4 KiB OTA-shaped sectors: sector
/// `i`'s dictionary is everything before it (up to the last 32 KiB, moot
/// here since the whole image is under 32 KiB). Only the compressed bytes
/// are fixtures; the dictionary and expected plaintext are re-sliced from
/// the firmware file already committed for `oracle_firmware.rs`, exactly as
/// `gen_preset_dict_vectors.py` did when producing them.
#[test]
fn firmware_sectors_with_growing_dictionary() {
    const CHUNK: usize = 4096;
    const SECTOR_FIXTURES: &[&[u8]] = &[
        include_bytes!("fixtures/firmware-sector-00.deflate"),
        include_bytes!("fixtures/firmware-sector-01.deflate"),
        include_bytes!("fixtures/firmware-sector-02.deflate"),
        include_bytes!("fixtures/firmware-sector-03.deflate"),
        include_bytes!("fixtures/firmware-sector-04.deflate"),
        include_bytes!("fixtures/firmware-sector-05.deflate"),
    ];
    for (i, deflate) in SECTOR_FIXTURES.iter().enumerate() {
        let offset = i * CHUNK;
        let dict_start = offset.saturating_sub(32_768);
        let dict = &FIRMWARE[dict_start..offset];
        let expect = &FIRMWARE[offset..(offset + CHUNK).min(FIRMWARE.len())];
        check_case(&format!("firmware-sector-{i:02}"), dict, deflate, expect);
    }
}
