[package]
name = "lp-perf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
syscall = ["dep:lp-emu-abi"]
log     = ["dep:log"]

[dependencies]
lp-emu-abi = { path = "../../lp-emu/lp-emu-abi", optional = true }
log = { workspace = true, default-features = false, optional = true }

[lints]
workspace = true
