//! The network seam's calls (`net=lan`; `lp_seam::net`), one per module.
//!
//! A capability seam in the switch shape: [`net_mac`]'s engaged byte, read
//! once at network bring-up, decides whether the radio or the seam-backed
//! station and frame device (`crate::net::seam_station`,
//! `crate::net::seam_frame_device`) run under the IP stack. Every call here
//! is generated by `lp_seam::seam_fn!` (the LTO rule); on silicon each one
//! returns 0 and writes nothing, and none of them is ever made.
//!
//! A chip's [`crate::seam_table!`] lists all nine entries, so an emulator
//! that engages the seam finds every call it must arm (`lp_seam::net::CALLS`).

pub mod net_connect;
pub mod net_disconnect;
pub mod net_event_take;
pub mod net_give_frame;
pub mod net_link;
pub mod net_mac;
pub mod net_scan_start;
pub mod net_scan_take;
pub mod net_take_frame;
