//! `net_take_frame`: take one received Ethernet II frame into `buf`; its length, 0 when none
//! is waiting.
//!
//! A network seam call (`lp_seam::net_take_frame`, generated by `lp_seam::seam_fn!`).
//! On silicon it returns 0 and writes nothing, and nothing calls it unless
//! [`super::net_mac`]'s engaged byte reads 1.

lp_seam::seam_fn! {
    net_take_frame => fn(buf: *mut u8, cap: u32) -> u32 {
        let _ = (buf, cap);
        0
    }
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
