//! `net_scan_start`: start listening for networks; 1 when started, and a `scan done`
//! event follows.
//!
//! A network seam call (`lp_seam::net_scan_start`, generated by `lp_seam::seam_fn!`).
//! On silicon it returns 0 and writes nothing, and nothing calls it unless
//! [`super::net_mac`]'s engaged byte reads 1.

lp_seam::seam_fn! {
    net_scan_start => fn() -> u32 {
        0
    }
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
