//! `net_link`: whether the station's link is up (1) or down (0).
//!
//! A network seam call (`lp_seam::net_link`, generated by `lp_seam::seam_fn!`).
//! On silicon it returns 0 and writes nothing, and nothing calls it unless
//! [`super::net_mac`]'s engaged byte reads 1.

lp_seam::seam_fn! {
    net_link => fn() -> u32 {
        0
    }
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
