//! `net_connect`: start joining a network; 1 when started, and its outcome comes as an
//! event. The password goes only into the call's buffer.
//!
//! A network seam call (`lp_seam::net_connect`, generated by `lp_seam::seam_fn!`).
//! On silicon it returns 0 and writes nothing, and nothing calls it unless
//! [`super::net_mac`]'s engaged byte reads 1.

lp_seam::seam_fn! {
    net_connect => fn(ssid: *const u8, ssid_len: u32, password: *const u8, password_len: u32) -> u32 {
        let _ = (ssid, ssid_len, password, password_len);
        0
    }
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
