//! `net_give_frame`: hand one Ethernet II frame to the LAN; 1 when taken, 0 when refused.
//!
//! A network seam call (`lp_seam::net_give_frame`, generated by `lp_seam::seam_fn!`).
//! On silicon it returns 0 and writes nothing, and nothing calls it unless
//! [`super::net_mac`]'s engaged byte reads 1.

lp_seam::seam_fn! {
    net_give_frame => fn(buf: *const u8, len: u32) -> u32 {
        let _ = (buf, len);
        0
    }
}

/// This seam's entry in the chip's [`crate::seam_table!`].
#[cfg(target_arch = "riscv32")]
pub const ENTRY: lp_seam::table::SeamEntry =
    lp_seam::table::SeamEntry::new(&DECL, ADDRESS, lp_seam::table::Addr::NONE);
