// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/apb_saradc.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `apb_saradc` block (28 registers).
pub static APB_SARADC: RegNames = RegNames {
    block: "apb_saradc",
    entries: &[
        (0x000, "ctrl"),
        (0x004, "ctrl2"),
        (0x008, "filter_ctrl1"),
        (0x00c, "fsm_wait"),
        (0x010, "sar1_status"),
        (0x014, "sar2_status"),
        (0x018, "sar_patt_tab1"),
        (0x01c, "sar_patt_tab2"),
        (0x020, "onetime_sample"),
        (0x024, "arb_ctrl"),
        (0x028, "filter_ctrl0"),
        (0x02c, "sar1data_status"),
        (0x030, "sar2data_status"),
        (0x034, "thres0_ctrl"),
        (0x038, "thres1_ctrl"),
        (0x03c, "thres_ctrl"),
        (0x040, "int_ena"),
        (0x044, "int_raw"),
        (0x048, "int_st"),
        (0x04c, "int_clr"),
        (0x050, "dma_conf"),
        (0x054, "clkm_conf"),
        (0x058, "tsens_ctrl"),
        (0x05c, "tsens_ctrl2"),
        (0x060, "cali"),
        (0x064, "tsens_wake"),
        (0x068, "tsens_sample"),
        (0x3fc, "ctrl_date"),
    ],
};
