// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/assist_debug.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `assist_debug` block (30 registers, 6 with a non-zero reset).
pub static ASSIST_DEBUG: RegNames = RegNames {
    block: "assist_debug",
    entries: &[
        (0x000, "cpu0.montr_ena"),
        (0x004, "cpu0.intr_raw"),
        (0x008, "cpu0.intr_ena"),
        (0x00c, "cpu0.intr_clr"),
        (0x010, "cpu0.area_dram0_0_min"),
        (0x014, "cpu0.area_dram0_0_max"),
        (0x018, "cpu0.area_dram0_1_min"),
        (0x01c, "cpu0.area_dram0_1_max"),
        (0x020, "cpu0.area_pif_0_min"),
        (0x024, "cpu0.area_pif_0_max"),
        (0x028, "cpu0.area_pif_1_min"),
        (0x02c, "cpu0.area_pif_1_max"),
        (0x030, "cpu0.area_pc"),
        (0x034, "cpu0.area_sp"),
        (0x038, "cpu0.sp_min"),
        (0x03c, "cpu0.sp_max"),
        (0x040, "cpu0.sp_pc"),
        (0x044, "cpu0.rcd_en"),
        (0x048, "cpu0.rcd_pdebugpc"),
        (0x04c, "cpu0.rcd_pdebugsp"),
        (0x050, "cpu0.iram0_exception_monitor_0"),
        (0x054, "cpu0.iram0_exception_monitor_1"),
        (0x058, "cpu0.dram0_exception_monitor_0"),
        (0x05c, "cpu0.dram0_exception_monitor_1"),
        (0x060, "cpu0.dram0_exception_monitor_2"),
        (0x064, "cpu0.dram0_exception_monitor_3"),
        (0x070, "cpu0.lastpc_before_exception"),
        (0x074, "cpu0.debug_mode"),
        (0x078, "clock_gate"),
        (0x3fc, "date"),
    ],
    resets: &[
        (0x010, 0xffffffff),
        (0x018, 0xffffffff),
        (0x020, 0xffffffff),
        (0x028, 0xffffffff),
        (0x03c, 0xffffffff),
        (0x078, 0x00000001),
    ],
};
