// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/hinf.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `hinf` block (21 registers, 15 with a non-zero reset).
pub static HINF: RegNames = RegNames {
    block: "hinf",
    entries: &[
        (0x000, "cfg_data0"),
        (0x004, "cfg_data1"),
        (0x008, "cfg_timing"),
        (0x00c, "cfg_update"),
        (0x01c, "cfg_data7"),
        (0x020, "cis_conf_w0"),
        (0x024, "cis_conf_w1"),
        (0x028, "cis_conf_w2"),
        (0x02c, "cis_conf_w3"),
        (0x030, "cis_conf_w4"),
        (0x034, "cis_conf_w5"),
        (0x038, "cis_conf_w6"),
        (0x03c, "cis_conf_w7"),
        (0x040, "cfg_data16"),
        (0x044, "cfg_uhs1_int_mode"),
        (0x054, "conf_status"),
        (0x0a4, "sdio_slave_eco_low"),
        (0x0a8, "sdio_slave_eco_high"),
        (0x0ac, "sdio_slave_eco_conf"),
        (0x0b0, "sdio_slave_ldo_conf"),
        (0x0fc, "sdio_date"),
    ],
    resets: &[
        (0x000, 0x00926666),
        (0x004, 0x00232011),
        (0x008, 0x15780812),
        (0x01c, 0x23820000),
        (0x020, 0xffffffff),
        (0x024, 0xffffffff),
        (0x028, 0xffffffff),
        (0x02c, 0xffffffff),
        (0x030, 0xffffffff),
        (0x034, 0xffffffff),
        (0x038, 0xffffffff),
        (0x03c, 0xffffffff),
        (0x040, 0x00927777),
        (0x0a8, 0xffffffff),
        (0x0b0, 0x00000014),
    ],
};
