// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/hp_sys.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `hp_sys` block (22 registers).
pub static HP_SYS: RegNames = RegNames {
    block: "hp_sys",
    entries: &[
        (0x004, "sram_usage_conf"),
        (0x008, "sec_dpa_conf"),
        (0x00c, "cpu_peri_timeout_conf"),
        (0x010, "cpu_peri_timeout_addr"),
        (0x014, "cpu_peri_timeout_uid"),
        (0x018, "hp_peri_timeout_conf"),
        (0x01c, "hp_peri_timeout_addr"),
        (0x020, "hp_peri_timeout_uid"),
        (0x024, "modem_peri_timeout_conf"),
        (0x028, "modem_peri_timeout_addr"),
        (0x02c, "modem_peri_timeout_uid"),
        (0x030, "sdio_ctrl"),
        (0x034, "retention_conf"),
        (0x038, "rom_table_lock"),
        (0x03c, "rom_table"),
        (0x040, "core_debug_runstall_conf"),
        (0x044, "mem_test_conf"),
        (0x3e0, "rnd_eco"),
        (0x3e4, "rnd_eco_low"),
        (0x3e8, "rnd_eco_high"),
        (0x3f8, "clock_gate"),
        (0x3fc, "date"),
    ],
};
