// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/i2c_ana_mst.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `i2c_ana_mst` block (12 registers, 2 with a non-zero reset).
pub static I2C_ANA_MST: RegNames = RegNames {
    block: "i2c_ana_mst",
    entries: &[
        (0x000, "i2c0_ctrl"),
        (0x004, "i2c1_ctrl"),
        (0x008, "i2c0_conf"),
        (0x00c, "i2c1_conf"),
        (0x010, "burst_conf"),
        (0x014, "burst_status"),
        (0x018, "ana_conf0"),
        (0x01c, "ana_conf1"),
        (0x020, "ana_conf2"),
        (0x024, "i2c0_ctrl1"),
        (0x028, "i2c1_ctrl1"),
        (0x034, "date"),
    ],
    resets: &[
        (0x024, 0x00000042),
        (0x028, 0x00000042),
    ],
};
