// Peripheral interrupt source numbers derived from esp-rs/esp-pacs:
//   esp32c6/src/interrupt.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

/// Every peripheral interrupt source, `(number, name)`, sorted (77 sources).
///
/// The number is the index into `INTERRUPT_CORE0.core_0_intr_map`.
pub static INTERRUPT_SOURCES: &[(u16, &str)] = &[
    (0, "WIFI_MAC"),
    (1, "WIFI_MAC_NMI"),
    (2, "WIFI_PWR"),
    (3, "WIFI_BB"),
    (4, "BT_MAC"),
    (5, "BT_BB"),
    (6, "BT_BB_NMI"),
    (7, "LP_TIMER"),
    (8, "COEX"),
    (9, "BLE_TIMER"),
    (10, "BLE_SEC"),
    (11, "I2C_MASTER"),
    (12, "ZB_MAC"),
    (13, "PMU"),
    (14, "EFUSE"),
    (15, "LP_RTC_TIMER"),
    (16, "LP_UART"),
    (17, "LP_I2C"),
    (18, "LP_WDT"),
    (19, "LP_PERI_TIMEOUT"),
    (20, "LP_APM_M0"),
    (21, "LP_APM_M1"),
    (22, "FROM_CPU_INTR0"),
    (23, "FROM_CPU_INTR1"),
    (24, "FROM_CPU_INTR2"),
    (25, "FROM_CPU_INTR3"),
    (26, "ASSIST_DEBUG"),
    (27, "TRACE"),
    (28, "CACHE"),
    (29, "CPU_PERI_TIMEOUT"),
    (30, "GPIO"),
    (31, "GPIO_NMI"),
    (32, "PAU"),
    (33, "HP_PERI_TIMEOUT"),
    (34, "MODEM_PERI_TIMEOUT"),
    (35, "HP_APM_M0"),
    (36, "HP_APM_M1"),
    (37, "HP_APM_M2"),
    (38, "HP_APM_M3"),
    (39, "LP_APM0"),
    (40, "MSPI"),
    (41, "I2S0"),
    (42, "UHCI0"),
    (43, "UART0"),
    (44, "UART1"),
    (45, "LEDC"),
    (46, "TWAI0"),
    (47, "TWAI1"),
    (48, "USB_DEVICE"),
    (49, "RMT"),
    (50, "I2C_EXT0"),
    (51, "TG0_T0_LEVEL"),
    (52, "TG0_T1_LEVEL"),
    (53, "TG0_WDT_LEVEL"),
    (54, "TG1_T0_LEVEL"),
    (55, "TG1_T1_LEVEL"),
    (56, "TG1_WDT_LEVEL"),
    (57, "SYSTIMER_TARGET0"),
    (58, "SYSTIMER_TARGET1"),
    (59, "SYSTIMER_TARGET2"),
    (60, "APB_SARADC"),
    (61, "MCPWM0"),
    (62, "PCNT"),
    (63, "PARL_IO"),
    (64, "SLC0"),
    (65, "SLC1"),
    (66, "DMA_IN_CH0"),
    (67, "DMA_IN_CH1"),
    (68, "DMA_IN_CH2"),
    (69, "DMA_OUT_CH0"),
    (70, "DMA_OUT_CH1"),
    (71, "DMA_OUT_CH2"),
    (72, "SPI2"),
    (73, "AES"),
    (74, "SHA"),
    (75, "RSA"),
    (76, "ECC"),
];

/// The same numbers as named constants.
#[allow(dead_code, reason = "generated: every source, used or not")]
pub mod source {
    pub const WIFI_MAC: u16 = 0;
    pub const WIFI_MAC_NMI: u16 = 1;
    pub const WIFI_PWR: u16 = 2;
    pub const WIFI_BB: u16 = 3;
    pub const BT_MAC: u16 = 4;
    pub const BT_BB: u16 = 5;
    pub const BT_BB_NMI: u16 = 6;
    pub const LP_TIMER: u16 = 7;
    pub const COEX: u16 = 8;
    pub const BLE_TIMER: u16 = 9;
    pub const BLE_SEC: u16 = 10;
    pub const I2C_MASTER: u16 = 11;
    pub const ZB_MAC: u16 = 12;
    pub const PMU: u16 = 13;
    pub const EFUSE: u16 = 14;
    pub const LP_RTC_TIMER: u16 = 15;
    pub const LP_UART: u16 = 16;
    pub const LP_I2C: u16 = 17;
    pub const LP_WDT: u16 = 18;
    pub const LP_PERI_TIMEOUT: u16 = 19;
    pub const LP_APM_M0: u16 = 20;
    pub const LP_APM_M1: u16 = 21;
    pub const FROM_CPU_INTR0: u16 = 22;
    pub const FROM_CPU_INTR1: u16 = 23;
    pub const FROM_CPU_INTR2: u16 = 24;
    pub const FROM_CPU_INTR3: u16 = 25;
    pub const ASSIST_DEBUG: u16 = 26;
    pub const TRACE: u16 = 27;
    pub const CACHE: u16 = 28;
    pub const CPU_PERI_TIMEOUT: u16 = 29;
    pub const GPIO: u16 = 30;
    pub const GPIO_NMI: u16 = 31;
    pub const PAU: u16 = 32;
    pub const HP_PERI_TIMEOUT: u16 = 33;
    pub const MODEM_PERI_TIMEOUT: u16 = 34;
    pub const HP_APM_M0: u16 = 35;
    pub const HP_APM_M1: u16 = 36;
    pub const HP_APM_M2: u16 = 37;
    pub const HP_APM_M3: u16 = 38;
    pub const LP_APM0: u16 = 39;
    pub const MSPI: u16 = 40;
    pub const I2S0: u16 = 41;
    pub const UHCI0: u16 = 42;
    pub const UART0: u16 = 43;
    pub const UART1: u16 = 44;
    pub const LEDC: u16 = 45;
    pub const TWAI0: u16 = 46;
    pub const TWAI1: u16 = 47;
    pub const USB_DEVICE: u16 = 48;
    pub const RMT: u16 = 49;
    pub const I2C_EXT0: u16 = 50;
    pub const TG0_T0_LEVEL: u16 = 51;
    pub const TG0_T1_LEVEL: u16 = 52;
    pub const TG0_WDT_LEVEL: u16 = 53;
    pub const TG1_T0_LEVEL: u16 = 54;
    pub const TG1_T1_LEVEL: u16 = 55;
    pub const TG1_WDT_LEVEL: u16 = 56;
    pub const SYSTIMER_TARGET0: u16 = 57;
    pub const SYSTIMER_TARGET1: u16 = 58;
    pub const SYSTIMER_TARGET2: u16 = 59;
    pub const APB_SARADC: u16 = 60;
    pub const MCPWM0: u16 = 61;
    pub const PCNT: u16 = 62;
    pub const PARL_IO: u16 = 63;
    pub const SLC0: u16 = 64;
    pub const SLC1: u16 = 65;
    pub const DMA_IN_CH0: u16 = 66;
    pub const DMA_IN_CH1: u16 = 67;
    pub const DMA_IN_CH2: u16 = 68;
    pub const DMA_OUT_CH0: u16 = 69;
    pub const DMA_OUT_CH1: u16 = 70;
    pub const DMA_OUT_CH2: u16 = 71;
    pub const SPI2: u16 = 72;
    pub const AES: u16 = 73;
    pub const SHA: u16 = 74;
    pub const RSA: u16 = 75;
    pub const ECC: u16 = 76;
}
