// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/intpri.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `intpri` block (46 registers, 2 with a non-zero reset).
pub static INTPRI: RegNames = RegNames {
    block: "intpri",
    entries: &[
        (0x000, "cpu_int_enable"),
        (0x004, "cpu_int_type"),
        (0x008, "cpu_int_eip_status"),
        (0x00c, "cpu_int_pri0"),
        (0x010, "cpu_int_pri1"),
        (0x014, "cpu_int_pri2"),
        (0x018, "cpu_int_pri3"),
        (0x01c, "cpu_int_pri4"),
        (0x020, "cpu_int_pri5"),
        (0x024, "cpu_int_pri6"),
        (0x028, "cpu_int_pri7"),
        (0x02c, "cpu_int_pri8"),
        (0x030, "cpu_int_pri9"),
        (0x034, "cpu_int_pri10"),
        (0x038, "cpu_int_pri11"),
        (0x03c, "cpu_int_pri12"),
        (0x040, "cpu_int_pri13"),
        (0x044, "cpu_int_pri14"),
        (0x048, "cpu_int_pri15"),
        (0x04c, "cpu_int_pri16"),
        (0x050, "cpu_int_pri17"),
        (0x054, "cpu_int_pri18"),
        (0x058, "cpu_int_pri19"),
        (0x05c, "cpu_int_pri20"),
        (0x060, "cpu_int_pri21"),
        (0x064, "cpu_int_pri22"),
        (0x068, "cpu_int_pri23"),
        (0x06c, "cpu_int_pri24"),
        (0x070, "cpu_int_pri25"),
        (0x074, "cpu_int_pri26"),
        (0x078, "cpu_int_pri27"),
        (0x07c, "cpu_int_pri28"),
        (0x080, "cpu_int_pri29"),
        (0x084, "cpu_int_pri30"),
        (0x088, "cpu_int_pri31"),
        (0x08c, "cpu_int_thresh"),
        (0x090, "cpu_intr_from_cpu0"),
        (0x094, "cpu_intr_from_cpu1"),
        (0x098, "cpu_intr_from_cpu2"),
        (0x09c, "cpu_intr_from_cpu3"),
        (0x0a0, "date"),
        (0x0a4, "clock_gate"),
        (0x0a8, "cpu_int_clear"),
        (0x0ac, "rnd_eco"),
        (0x0b0, "rnd_eco_low"),
        (0x3fc, "rnd_eco_high"),
    ],
    resets: &[(0x0a4, 0x00000001), (0x3fc, 0xffffffff)],
};
