// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/io_mux.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `io_mux` block (34 registers).
pub static IO_MUX: RegNames = RegNames {
    block: "io_mux",
    entries: &[
        (0x000, "pin_ctrl"),
        (0x004, "gpio0"),
        (0x008, "gpio1"),
        (0x00c, "gpio2"),
        (0x010, "gpio3"),
        (0x014, "gpio4"),
        (0x018, "gpio5"),
        (0x01c, "gpio6"),
        (0x020, "gpio7"),
        (0x024, "gpio8"),
        (0x028, "gpio9"),
        (0x02c, "gpio10"),
        (0x030, "gpio11"),
        (0x034, "gpio12"),
        (0x038, "gpio13"),
        (0x03c, "gpio14"),
        (0x040, "gpio15"),
        (0x044, "gpio16"),
        (0x048, "gpio17"),
        (0x04c, "gpio18"),
        (0x050, "gpio19"),
        (0x054, "gpio20"),
        (0x058, "gpio21"),
        (0x05c, "gpio22"),
        (0x060, "gpio23"),
        (0x064, "gpio24"),
        (0x068, "gpio25"),
        (0x06c, "gpio26"),
        (0x070, "gpio27"),
        (0x074, "gpio28"),
        (0x078, "gpio29"),
        (0x07c, "gpio30"),
        (0x0bc, "modem_diag_en"),
        (0x0fc, "date"),
    ],
};
