// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_apm.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_apm` block (25 registers).
pub static LP_APM: RegNames = RegNames {
    block: "lp_apm",
    entries: &[
        (0x000, "region_filter_en"),
        (0x004, "region0.addr_start"),
        (0x008, "region0.addr_end"),
        (0x00c, "region0.pms_attr"),
        (0x010, "region1.addr_start"),
        (0x014, "region1.addr_end"),
        (0x018, "region1.pms_attr"),
        (0x01c, "region2.addr_start"),
        (0x020, "region2.addr_end"),
        (0x024, "region2.pms_attr"),
        (0x028, "region3.addr_start"),
        (0x02c, "region3.addr_end"),
        (0x030, "region3.pms_attr"),
        (0x0c4, "func_ctrl"),
        (0x0c8, "m0.status"),
        (0x0cc, "m0.status_clr"),
        (0x0d0, "m0.exception_info0"),
        (0x0d4, "m0.exception_info1"),
        (0x0d8, "m1.status"),
        (0x0dc, "m1.status_clr"),
        (0x0e0, "m1.exception_info0"),
        (0x0e4, "m1.exception_info1"),
        (0x0e8, "int_en"),
        (0x0ec, "clock_gate"),
        (0x0fc, "date"),
    ],
};
