// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_ana.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_ana` block (13 registers, 2 with a non-zero reset).
pub static LP_ANA: RegNames = RegNames {
    block: "lp_ana",
    entries: &[
        (0x000, "bod_mode0_cntl"),
        (0x004, "bod_mode1_cntl"),
        (0x008, "ck_glitch_cntl"),
        (0x00c, "fib_enable"),
        (0x010, "int_raw"),
        (0x014, "int_st"),
        (0x018, "int_ena"),
        (0x01c, "int_clr"),
        (0x020, "lp_int_raw"),
        (0x024, "lp_int_st"),
        (0x028, "lp_int_ena"),
        (0x02c, "lp_int_clr"),
        (0x3fc, "date"),
    ],
    resets: &[(0x000, 0x0ffc0100), (0x00c, 0xffffffff)],
};
