// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_aon.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_aon` block (23 registers).
pub static LP_AON: RegNames = RegNames {
    block: "lp_aon",
    entries: &[
        (0x000, "store0"),
        (0x004, "store1"),
        (0x008, "store2"),
        (0x00c, "store3"),
        (0x010, "store4"),
        (0x014, "store5"),
        (0x018, "store6"),
        (0x01c, "store7"),
        (0x020, "store8"),
        (0x024, "store9"),
        (0x028, "gpio_mux"),
        (0x02c, "gpio_hold0"),
        (0x030, "gpio_hold1"),
        (0x034, "sys_cfg"),
        (0x038, "cpucore0_cfg"),
        (0x03c, "io_mux"),
        (0x040, "ext_wakeup_cntl"),
        (0x044, "usb"),
        (0x048, "lpbus"),
        (0x04c, "sdio_active"),
        (0x050, "lpcore"),
        (0x054, "sar_cct"),
        (0x3fc, "date"),
    ],
};
