// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_clkrst.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_clkrst` block (13 registers).
pub static LP_CLKRST: RegNames = RegNames {
    block: "lp_clkrst",
    entries: &[
        (0x000, "lp_clk_conf"),
        (0x004, "lp_clk_po_en"),
        (0x008, "lp_clk_en"),
        (0x00c, "lp_rst_en"),
        (0x010, "reset_cause"),
        (0x014, "cpu_reset"),
        (0x018, "fosc_cntl"),
        (0x01c, "rc32k_cntl"),
        (0x020, "clk_to_hp"),
        (0x024, "lpmem_force"),
        (0x028, "lpperi"),
        (0x02c, "xtal32k"),
        (0x3fc, "date"),
    ],
};
