// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_io.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_io` block (31 registers, 1 with a non-zero reset).
pub static LP_IO: RegNames = RegNames {
    block: "lp_io",
    entries: &[
        (0x000, "out_data"),
        (0x004, "out_data_w1ts"),
        (0x008, "out_data_w1tc"),
        (0x00c, "out_enable"),
        (0x010, "out_enable_w1ts"),
        (0x014, "out_enable_w1tc"),
        (0x018, "status"),
        (0x01c, "status_w1ts"),
        (0x020, "status_w1tc"),
        (0x024, "in_"),
        (0x028, "pin0"),
        (0x02c, "pin1"),
        (0x030, "pin2"),
        (0x034, "pin3"),
        (0x038, "pin4"),
        (0x03c, "pin5"),
        (0x040, "pin6"),
        (0x044, "pin7"),
        (0x048, "gpio0"),
        (0x04c, "gpio1"),
        (0x050, "gpio2"),
        (0x054, "gpio3"),
        (0x058, "gpio4"),
        (0x05c, "gpio5"),
        (0x060, "gpio6"),
        (0x064, "gpio7"),
        (0x068, "status_interrupt"),
        (0x06c, "debug_sel0"),
        (0x070, "debug_sel1"),
        (0x074, "lpi2c"),
        (0x3fc, "date"),
    ],
    resets: &[(0x074, 0xc0000000)],
};
