// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_i2c_ana_mst.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_i2c_ana_mst` block (7 registers, 2 with a non-zero reset).
pub static LP_I2C_ANA_MST: RegNames = RegNames {
    block: "lp_i2c_ana_mst",
    entries: &[
        (0x000, "i2c0_ctrl"),
        (0x004, "i2c0_conf"),
        (0x008, "i2c0_data"),
        (0x00c, "ana_conf1"),
        (0x010, "nouse"),
        (0x014, "device_en"),
        (0x3fc, "date"),
    ],
    resets: &[(0x004, 0x07000000), (0x008, 0x00000900)],
};
