// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_peri.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_peri` block (10 registers).
pub static LP_PERI: RegNames = RegNames {
    block: "lp_peri",
    entries: &[
        (0x000, "clk_en"),
        (0x004, "reset_en"),
        (0x008, "rng_data"),
        (0x00c, "cpu"),
        (0x010, "bus_timeout"),
        (0x014, "bus_timeout_addr"),
        (0x018, "bus_timeout_uid"),
        (0x01c, "mem_ctrl"),
        (0x020, "interrupt_source"),
        (0x3fc, "date"),
    ],
};
