// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_tee.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_tee` block (4 registers, 2 with a non-zero reset).
pub static LP_TEE: RegNames = RegNames {
    block: "lp_tee",
    entries: &[
        (0x000, "m0_mode_ctrl"),
        (0x004, "clock_gate"),
        (0x090, "force_acc_hp"),
        (0x0fc, "date"),
    ],
    resets: &[(0x000, 0x00000003), (0x004, 0x00000001)],
};
