// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_timer.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_timer` block (19 registers, 0 with a non-zero reset).
pub static LP_TIMER: RegNames = RegNames {
    block: "lp_timer",
    entries: &[
        (0x000, "tar0_low"),
        (0x004, "tar0_high"),
        (0x008, "tar1_low"),
        (0x00c, "tar1_high"),
        (0x010, "update"),
        (0x014, "main_buf0_low"),
        (0x018, "main_buf0_high"),
        (0x01c, "main_buf1_low"),
        (0x020, "main_buf1_high"),
        (0x024, "main_overflow"),
        (0x028, "int_raw"),
        (0x02c, "int_st"),
        (0x030, "int_ena"),
        (0x034, "int_clr"),
        (0x038, "lp_int_raw"),
        (0x03c, "lp_int_st"),
        (0x040, "lp_int_ena"),
        (0x044, "lp_int_clr"),
        (0x3fc, "date"),
    ],
    resets: &[
    ],
};
