// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/lp_wdt.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `lp_wdt` block (14 registers, 6 with a non-zero reset).
pub static LP_WDT: RegNames = RegNames {
    block: "lp_wdt",
    entries: &[
        (0x000, "wdtconfig0"),
        (0x004, "wdtconfig1"),
        (0x008, "wdtconfig2"),
        (0x00c, "wdtconfig3"),
        (0x010, "wdtconfig4"),
        (0x014, "wdtfeed"),
        (0x018, "wdtwprotect"),
        (0x01c, "swd_conf"),
        (0x020, "swd_wprotect"),
        (0x024, "int_raw"),
        (0x028, "int_st"),
        (0x02c, "int_ena"),
        (0x030, "int_clr"),
        (0x3fc, "date"),
    ],
    resets: &[
        (0x000, 0x00013214),
        (0x004, 0x00030d40),
        (0x008, 0x00030d40),
        (0x00c, 0x00030d40),
        (0x010, 0x00030d40),
        (0x01c, 0x12c00000),
    ],
};
