// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/modem_lpcon.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `modem_lpcon` block (12 registers).
pub static MODEM_LPCON: RegNames = RegNames {
    block: "modem_lpcon",
    entries: &[
        (0x000, "test_conf"),
        (0x004, "lp_timer_conf"),
        (0x008, "coex_lp_clk_conf"),
        (0x00c, "wifi_lp_clk_conf"),
        (0x010, "i2c_mst_clk_conf"),
        (0x014, "modem_32k_clk_conf"),
        (0x018, "clk_conf"),
        (0x01c, "clk_conf_force_on"),
        (0x020, "clk_conf_power_st"),
        (0x024, "rst_conf"),
        (0x028, "mem_conf"),
        (0x02c, "date"),
    ],
};
