// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/modem_syscon.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `modem_syscon` block (10 registers, 2 with a non-zero reset).
pub static MODEM_SYSCON: RegNames = RegNames {
    block: "modem_syscon",
    entries: &[
        (0x000, "test_conf"),
        (0x004, "clk_conf"),
        (0x008, "clk_conf_force_on"),
        (0x00c, "clk_conf_power_st"),
        (0x010, "modem_rst_conf"),
        (0x014, "clk_conf1"),
        (0x018, "clk_conf1_force_on"),
        (0x01c, "wifi_bb_cfg"),
        (0x020, "mem_conf"),
        (0x024, "date"),
    ],
    resets: &[
        (0x004, 0x00200000),
        (0x020, 0x00000020),
    ],
};
