// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/plic_ux.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `plic_ux` block (38 registers, 0 with a non-zero reset).
pub static PLIC_UX: RegNames = RegNames {
    block: "plic_ux",
    entries: &[
        (0x000, "uxint_enable"),
        (0x004, "uxint_type"),
        (0x008, "uxint_clear"),
        (0x00c, "euip_status"),
        (0x010, "uxint0_pri"),
        (0x014, "uxint1_pri"),
        (0x018, "uxint2_pri"),
        (0x01c, "uxint3_pri"),
        (0x020, "uxint4_pri"),
        (0x024, "uxint5_pri"),
        (0x028, "uxint6_pri"),
        (0x02c, "uxint7_pri"),
        (0x030, "uxint8_pri"),
        (0x034, "uxint9_pri"),
        (0x038, "uxint10_pri"),
        (0x03c, "uxint11_pri"),
        (0x040, "uxint12_pri"),
        (0x044, "uxint13_pri"),
        (0x048, "uxint14_pri"),
        (0x04c, "uxint15_pri"),
        (0x050, "uxint16_pri"),
        (0x054, "uxint17_pri"),
        (0x058, "uxint18_pri"),
        (0x05c, "uxint19_pri"),
        (0x060, "uxint20_pri"),
        (0x064, "uxint21_pri"),
        (0x068, "uxint22_pri"),
        (0x06c, "uxint23_pri"),
        (0x070, "uxint24_pri"),
        (0x074, "uxint25_pri"),
        (0x078, "uxint26_pri"),
        (0x07c, "uxint27_pri"),
        (0x080, "uxint28_pri"),
        (0x084, "uxint29_pri"),
        (0x088, "uxint30_pri"),
        (0x08c, "uxint31_pri"),
        (0x090, "uxint_thresh"),
        (0x094, "uxint_claim"),
    ],
    resets: &[],
};
