// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/plic_mx.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `plic_mx` block (38 registers, 0 with a non-zero reset).
pub static PLIC_MX: RegNames = RegNames {
    block: "plic_mx",
    entries: &[
        (0x000, "mxint_enable"),
        (0x004, "mxint_type"),
        (0x008, "mxint_clear"),
        (0x00c, "emip_status"),
        (0x010, "mxint0_pri"),
        (0x014, "mxint1_pri"),
        (0x018, "mxint2_pri"),
        (0x01c, "mxint3_pri"),
        (0x020, "mxint4_pri"),
        (0x024, "mxint5_pri"),
        (0x028, "mxint6_pri"),
        (0x02c, "mxint7_pri"),
        (0x030, "mxint8_pri"),
        (0x034, "mxint9_pri"),
        (0x038, "mxint10_pri"),
        (0x03c, "mxint11_pri"),
        (0x040, "mxint12_pri"),
        (0x044, "mxint13_pri"),
        (0x048, "mxint14_pri"),
        (0x04c, "mxint15_pri"),
        (0x050, "mxint16_pri"),
        (0x054, "mxint17_pri"),
        (0x058, "mxint18_pri"),
        (0x05c, "mxint19_pri"),
        (0x060, "mxint20_pri"),
        (0x064, "mxint21_pri"),
        (0x068, "mxint22_pri"),
        (0x06c, "mxint23_pri"),
        (0x070, "mxint24_pri"),
        (0x074, "mxint25_pri"),
        (0x078, "mxint26_pri"),
        (0x07c, "mxint27_pri"),
        (0x080, "mxint28_pri"),
        (0x084, "mxint29_pri"),
        (0x088, "mxint30_pri"),
        (0x08c, "mxint31_pri"),
        (0x090, "mxint_thresh"),
        (0x094, "mxint_claim"),
    ],
    resets: &[
    ],
};
