// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/rmt.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `rmt` block (30 registers, 13 with a non-zero reset).
pub static RMT: RegNames = RegNames {
    block: "rmt",
    entries: &[
        (0x000, "ch0data"),
        (0x004, "ch1data"),
        (0x008, "ch2data"),
        (0x00c, "ch3data"),
        (0x010, "ch0_tx_conf0"),
        (0x014, "ch1_tx_conf0"),
        (0x018, "ch2_rx_conf0"),
        (0x01c, "ch2_rx_conf1"),
        (0x020, "ch3_rx_conf0"),
        (0x024, "ch3_rx_conf1"),
        (0x028, "ch0_tx_status"),
        (0x02c, "ch1_tx_status"),
        (0x030, "ch0_rx_status"),
        (0x034, "ch1_rx_status"),
        (0x038, "int_raw"),
        (0x03c, "int_st"),
        (0x040, "int_ena"),
        (0x044, "int_clr"),
        (0x048, "ch0carrier_duty"),
        (0x04c, "ch1carrier_duty"),
        (0x050, "ch0_rx_carrier_rm"),
        (0x054, "ch1_rx_carrier_rm"),
        (0x058, "ch0_tx_lim"),
        (0x05c, "ch1_tx_lim"),
        (0x060, "ch0_rx_lim"),
        (0x064, "ch1_rx_lim"),
        (0x068, "sys_conf"),
        (0x06c, "tx_sim"),
        (0x070, "ref_cnt_rst"),
        (0x0cc, "date"),
    ],
    resets: &[
        (0x010, 0x00710200),
        (0x014, 0x00710200),
        (0x018, 0x30ffff02),
        (0x01c, 0x000001e8),
        (0x020, 0x30ffff02),
        (0x024, 0x000001e8),
        (0x048, 0x00400040),
        (0x04c, 0x00400040),
        (0x058, 0x00000080),
        (0x05c, 0x00000080),
        (0x060, 0x00000080),
        (0x064, 0x00000080),
        (0x068, 0x05000010),
    ],
};
