// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/sha.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `sha` block (36 registers, 0 with a non-zero reset).
pub static SHA: RegNames = RegNames {
    block: "sha",
    entries: &[
        (0x000, "mode"),
        (0x004, "t_string"),
        (0x008, "t_length"),
        (0x00c, "dma_block_num"),
        (0x010, "start"),
        (0x014, "continue_"),
        (0x018, "busy"),
        (0x01c, "dma_start"),
        (0x020, "dma_continue"),
        (0x024, "clear_irq"),
        (0x028, "irq_ena"),
        (0x02c, "date"),
        (0x040, "h_mem0"),
        (0x044, "h_mem1"),
        (0x048, "h_mem2"),
        (0x04c, "h_mem3"),
        (0x050, "h_mem4"),
        (0x054, "h_mem5"),
        (0x058, "h_mem6"),
        (0x05c, "h_mem7"),
        (0x080, "m_mem0"),
        (0x084, "m_mem1"),
        (0x088, "m_mem2"),
        (0x08c, "m_mem3"),
        (0x090, "m_mem4"),
        (0x094, "m_mem5"),
        (0x098, "m_mem6"),
        (0x09c, "m_mem7"),
        (0x0a0, "m_mem8"),
        (0x0a4, "m_mem9"),
        (0x0a8, "m_mem10"),
        (0x0ac, "m_mem11"),
        (0x0b0, "m_mem12"),
        (0x0b4, "m_mem13"),
        (0x0b8, "m_mem14"),
        (0x0bc, "m_mem15"),
    ],
    resets: &[],
};
