// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/slc.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `slc` block (33 registers, 13 with a non-zero reset).
pub static SLC: RegNames = RegNames {
    block: "slc",
    entries: &[
        (0x000, "slcconf0"),
        (0x004, "slc0int_raw"),
        (0x008, "slc0int_st"),
        (0x00c, "slc0int_ena"),
        (0x010, "slc0int_clr"),
        (0x014, "slc1int_raw"),
        (0x020, "slc1int_clr"),
        (0x03c, "slc0rx_link"),
        (0x040, "slc0rx_link_addr"),
        (0x044, "slc0tx_link"),
        (0x048, "slc0tx_link_addr"),
        (0x04c, "slc1rx_link"),
        (0x050, "slc1rx_link_addr"),
        (0x054, "slc1tx_link"),
        (0x058, "slc1tx_link_addr"),
        (0x05c, "slcintvec_tohost"),
        (0x064, "slc0token1"),
        (0x06c, "slc1token1"),
        (0x070, "slcconf1"),
        (0x0a8, "slc_rx_dscr_conf"),
        (0x0f4, "slc0_len_conf"),
        (0x0f8, "slc0_length"),
        (0x14c, "slc1int_st1"),
        (0x150, "slc1int_ena1"),
        (0x154, "slc0_tx_sharemem_start"),
        (0x158, "slc0_tx_sharemem_end"),
        (0x15c, "slc0_rx_sharemem_start"),
        (0x160, "slc0_rx_sharemem_end"),
        (0x164, "slc1_tx_sharemem_start"),
        (0x168, "slc1_tx_sharemem_end"),
        (0x16c, "slc1_rx_sharemem_start"),
        (0x170, "slc1_rx_sharemem_end"),
        (0x17c, "slc_burst_len"),
    ],
    resets: &[
        (0x000, 0xff3cff00),
        (0x03c, 0x80000000),
        (0x044, 0x80000000),
        (0x04c, 0x80000000),
        (0x054, 0x80000000),
        (0x070, 0x00300078),
        (0x0a8, 0x0203701a),
        (0x0f4, 0x20000000),
        (0x158, 0xffffffff),
        (0x160, 0xffffffff),
        (0x168, 0xffffffff),
        (0x170, 0xffffffff),
        (0x17c, 0x0000000f),
    ],
};
