// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/tee.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `tee` block (34 registers, 1 with a non-zero reset).
pub static TEE: RegNames = RegNames {
    block: "tee",
    entries: &[
        (0x000, "m0_mode_ctrl"),
        (0x004, "m1_mode_ctrl"),
        (0x008, "m2_mode_ctrl"),
        (0x00c, "m3_mode_ctrl"),
        (0x010, "m4_mode_ctrl"),
        (0x014, "m5_mode_ctrl"),
        (0x018, "m6_mode_ctrl"),
        (0x01c, "m7_mode_ctrl"),
        (0x020, "m8_mode_ctrl"),
        (0x024, "m9_mode_ctrl"),
        (0x028, "m10_mode_ctrl"),
        (0x02c, "m11_mode_ctrl"),
        (0x030, "m12_mode_ctrl"),
        (0x034, "m13_mode_ctrl"),
        (0x038, "m14_mode_ctrl"),
        (0x03c, "m15_mode_ctrl"),
        (0x040, "m16_mode_ctrl"),
        (0x044, "m17_mode_ctrl"),
        (0x048, "m18_mode_ctrl"),
        (0x04c, "m19_mode_ctrl"),
        (0x050, "m20_mode_ctrl"),
        (0x054, "m21_mode_ctrl"),
        (0x058, "m22_mode_ctrl"),
        (0x05c, "m23_mode_ctrl"),
        (0x060, "m24_mode_ctrl"),
        (0x064, "m25_mode_ctrl"),
        (0x068, "m26_mode_ctrl"),
        (0x06c, "m27_mode_ctrl"),
        (0x070, "m28_mode_ctrl"),
        (0x074, "m29_mode_ctrl"),
        (0x078, "m30_mode_ctrl"),
        (0x07c, "m31_mode_ctrl"),
        (0x080, "clock_gate"),
        (0xffc, "date"),
    ],
    resets: &[(0x080, 0x00000001)],
};
