// Register offsets and names derived from esp-rs/esp-pacs:
//   esp32c6/src/timg0.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `timg0` block (26 registers).
pub static TIMG0: RegNames = RegNames {
    block: "timg0",
    entries: &[
        (0x000, "t0.config"),
        (0x004, "t0.lo"),
        (0x008, "t0.hi"),
        (0x00c, "t0.update"),
        (0x010, "t0.alarmlo"),
        (0x014, "t0.alarmhi"),
        (0x018, "t0.loadlo"),
        (0x01c, "t0.loadhi"),
        (0x020, "t0.load"),
        (0x048, "wdtconfig0"),
        (0x04c, "wdtconfig1"),
        (0x050, "wdtconfig2"),
        (0x054, "wdtconfig3"),
        (0x058, "wdtconfig4"),
        (0x05c, "wdtconfig5"),
        (0x060, "wdtfeed"),
        (0x064, "wdtwprotect"),
        (0x068, "rtccalicfg"),
        (0x06c, "rtccalicfg1"),
        (0x070, "int_ena"),
        (0x074, "int_raw"),
        (0x078, "int_st"),
        (0x07c, "int_clr"),
        (0x080, "rtccalicfg2"),
        (0x0f8, "ntimers_date"),
        (0x0fc, "regclk"),
    ],
};
