// Register offsets, names and reset values derived from esp-rs/esp-pacs:
//   esp32c6/src/usb_device.rs  (crate esp32c6 0.23.2,
//   generated by svd2rust v0.37.1 (f74f0b3 2026-04-17))
// Repository: https://github.com/esp-rs/esp-pacs
// MIT OR Apache-2.0; MIT text vendored at licenses/esp-pacs-MIT.txt.
// Generated by scripts/emu/pac-regnames.py — do not hand-edit.
// Regenerate and check with `just lint-emu-regnames`.

use lp_emu_esp_common::regnames::RegNames;

/// Register names for the `usb_device` block (28 registers, 12 with a non-zero reset).
pub static USB_DEVICE: RegNames = RegNames {
    block: "usb_device",
    entries: &[
        (0x000, "ep1"),
        (0x004, "ep1_conf"),
        (0x008, "int_raw"),
        (0x00c, "int_st"),
        (0x010, "int_ena"),
        (0x014, "int_clr"),
        (0x018, "conf0"),
        (0x01c, "test"),
        (0x020, "jfifo_st"),
        (0x024, "fram_num"),
        (0x028, "in_ep0_st"),
        (0x02c, "in_ep1_st"),
        (0x030, "in_ep2_st"),
        (0x034, "in_ep3_st"),
        (0x038, "out_ep0_st"),
        (0x03c, "out_ep1_st"),
        (0x040, "out_ep2_st"),
        (0x044, "misc_conf"),
        (0x048, "mem_conf"),
        (0x04c, "chip_rst"),
        (0x050, "set_line_code_w0"),
        (0x054, "set_line_code_w1"),
        (0x058, "get_line_code_w0"),
        (0x05c, "get_line_code_w1"),
        (0x060, "config_update"),
        (0x064, "ser_afifo_config"),
        (0x068, "bus_reset_st"),
        (0x080, "date"),
    ],
    resets: &[
        (0x004, 0x00000002),
        (0x008, 0x00000008),
        (0x018, 0x00004200),
        (0x01c, 0x00000030),
        (0x020, 0x00000044),
        (0x028, 0x00000001),
        (0x02c, 0x00000001),
        (0x030, 0x00000001),
        (0x034, 0x00000001),
        (0x048, 0x00000002),
        (0x064, 0x00000010),
        (0x068, 0x00000001),
    ],
};
