//! The generated linker script that places the engine (`engine.x`).
//!
//! Every engine input section from a Rust object, in address order, into
//! two output sections in an `ENGINE` region at [`ENGINE_BASE`], the header
//! first. Three of the spike's traps live here:
//!
//! - section names are not unique across objects (`compiler_builtins`, never
//!   LTO'd, has its own `OUTLINED_FUNCTION_N`), so a rule names the object
//!   **and** the section;
//! - an object's file name carries a hash that changes with the link
//!   arguments, so the hash is globbed;
//! - archive members use lld's `archive:member` spelling.
//!
//! A C archive member only the engine reaches stays in the core. That is
//! harmless (the core never calls it) and keeps the rules simple.

use std::fmt::Write as _;

use crate::reachability::Split;
use crate::section_graph::SectionGraph;

/// Where the engine is linked: the core maps its flash pages here.
pub const ENGINE_BASE: u32 = 0x4240_0000;
/// The window the engine may occupy.
pub const ENGINE_WINDOW: u32 = 0x40_0000;

/// The pass-1 script: only the header placed, so pass 1 links it where
/// pass 2 will.
pub fn pass1_script() -> String {
    format!(
        "MEMORY {{\n  ENGINE : ORIGIN = {ENGINE_BASE:#x}, LENGTH = {ENGINE_WINDOW:#x}\n}}\n\
         SECTIONS {{\n  .engine_rodata : ALIGN(4) {{\n    KEEP(*(.engine_header))\n  }} > ENGINE\n}}\n\
         INSERT BEFORE .rodata;\n"
    )
}

/// The placement rules for the engine's sections.
pub struct EngineRules {
    pub rodata: Vec<String>,
    pub text: Vec<String>,
}

impl EngineRules {
    pub fn from_split(graph: &SectionGraph, split: &Split) -> Self {
        let mut engine: Vec<usize> = split.engine(graph);
        engine.sort_by_key(|i| graph.nodes[*i].vma);
        let mut rules = Self {
            rodata: Vec::new(),
            text: Vec::new(),
        };
        for i in engine {
            let n = &graph.nodes[i];
            if !n.is_flash() {
                continue;
            }
            let (obj, sec) = n.object_and_section();
            if !is_rust_object(obj) || sec == ".engine_header" {
                continue;
            }
            let pattern = format!("*{}({sec})", object_pattern(obj));
            if n.out == ".text" {
                rules.text.push(pattern);
            } else {
                rules.rodata.push(pattern);
            }
        }
        rules
    }

    /// The whole `engine.x`.
    pub fn script(&self) -> String {
        let mut s = String::new();
        s.push_str("/* split-link image: generated by tools/lp-fw-split. */\n");
        s.push_str(
            "/* Engine region: mapped by the core at runtime, never by the bootloader. */\n",
        );
        let _ = writeln!(
            s,
            "MEMORY {{\n  ENGINE : ORIGIN = {ENGINE_BASE:#x}, LENGTH = {ENGINE_WINDOW:#x}\n}}"
        );
        s.push_str("SECTIONS {\n");
        s.push_str("  .engine_rodata : ALIGN(4) {\n    KEEP(*(.engine_header))\n");
        for r in &self.rodata {
            let _ = writeln!(s, "    {r}");
        }
        s.push_str("  } > ENGINE\n  .engine_text : ALIGN(4) {\n");
        for r in &self.text {
            let _ = writeln!(s, "    {r}");
        }
        s.push_str("  } > ENGINE\n}\nINSERT BEFORE .rodata;\n");
        s
    }
}

/// An object from rustc: the LTO'd codegen unit, an LTO temporary, or an
/// rlib member.
pub fn is_rust_object(obj: &str) -> bool {
    obj.contains(".rcgu.o") || obj.contains("lto.tmp") || obj.ends_with(".rlib")
}

/// The object's file name, its 16-hex-digit hashes globbed, an archive
/// member spelled `archive:member`.
pub fn object_pattern(obj: &str) -> String {
    let base = obj.rsplit('/').next().unwrap_or(obj);
    let base = glob_hashes(base);
    match base.split_once('(') {
        Some((archive, member)) => {
            let member = &member[..member.len().saturating_sub(1)];
            format!("{archive}:{member}")
        }
        None => base,
    }
}

/// Every `-<16 lowercase hex digits>` that ends a word becomes `-*`.
fn glob_hashes(name: &str) -> String {
    let b = name.as_bytes();
    let is_hex = |c: u8| matches!(c, b'0'..=b'9' | b'a'..=b'f');
    let is_word = |c: u8| c.is_ascii_alphanumeric() || c == b'_' || c >= 0x80;
    let mut out = String::with_capacity(name.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'-'
            && i + 17 <= b.len()
            && b[i + 1..i + 17].iter().all(|c| is_hex(*c))
            && (i + 17 == b.len() || !is_word(b[i + 17]))
        {
            out.push_str("-*");
            i += 17;
        } else {
            let ch = name[i..].chars().next().unwrap_or('?');
            out.push(ch);
            i += ch.len_utf8();
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hashes_are_globbed_and_archive_members_respelled() {
        assert_eq!(
            object_pattern(
                "/c/deps/fw_esp32c6-a185b6a2d40176f3.fw_esp32c6.59840389e093d5d9-cgu.0.rcgu.o"
            ),
            "fw_esp32c6-*.fw_esp32c6.59840389e093d5d9-cgu.0.rcgu.o"
        );
        assert_eq!(
            object_pattern(
                "/c/libcompiler_builtins-0123456789abcdef.rlib(compiler_builtins-0123456789abcdef.cb.o)"
            ),
            "libcompiler_builtins-*.rlib:compiler_builtins-*.cb.o"
        );
        // Seventeen digits is not a hash; neither is one followed by a word.
        assert_eq!(
            glob_hashes("a-0123456789abcdef0.o"),
            "a-0123456789abcdef0.o"
        );
        assert_eq!(glob_hashes("a-0123456789abcdefx"), "a-0123456789abcdefx");
    }

    #[test]
    fn rust_objects_are_recognised() {
        assert!(is_rust_object("/x/a.b.rcgu.o"));
        assert!(is_rust_object("/x/lto.tmp"));
        assert!(is_rust_object("/x/libfoo.rlib"));
        assert!(!is_rust_object("/x/libbtdm_app.a(arch_main.o)"));
    }

    #[test]
    fn the_script_places_the_header_first() {
        let rules = EngineRules {
            rodata: vec!["*a.o(.rodata.x)".into()],
            text: vec!["*a.o(.text.y)".into()],
        };
        let s = rules.script();
        let header = s.find("KEEP(*(.engine_header))").unwrap();
        assert!(header < s.find("*a.o(.rodata.x)").unwrap());
        assert!(s.contains("ORIGIN = 0x42400000"));
        assert!(s.ends_with("INSERT BEFORE .rodata;\n"));
    }
}
