//! The journal: a flight recorder, **not** a source of truth.
//!
//! It records BOTH streams — every action and every event, interleaved and
//! timestamped — plus the derived notes that make a timeline readable
//! ("user clicked cancel at t=3.2, heartbeat at t=3.4, evicted at t=8.2").
//! Derivation does not read it: evidence is folded incrementally and intent
//! is plain state. Two things read the journal: forensics and tests.
//!
//! **Replay is the test path.** [`Journal::replay_inputs`] hands back the
//! recorded inputs with derived notes filtered out;
//! [`crate::replay::replay_inputs`] feeds them through a fresh roster and
//! must reproduce the same journal and the same projections.
//!
//! Pruning is a ring: oldest entries go first. Nothing derivation needs is
//! lost, because derivation needs none of it.

use std::collections::VecDeque;

use serde::{Deserialize, Serialize};

use crate::activity::{ActivityKind, ActivityOutcome};
use crate::event::{Action, Event, Input};
use crate::identity::{DeviceId, IdentityBinding};
use crate::link::LinkId;
use crate::time::Millis;

/// Which part of the model an entry belongs to. Also the addressing unit for
/// timers.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub enum Scope {
    Roster,
    Device(DeviceId),
    /// A link the roster is still identifying (not yet a device).
    PendingLink(LinkId),
}

/// One journal line.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct JournalEntry {
    /// Monotonic within a journal; makes replay comparisons order-exact.
    pub seq: u64,
    pub at: Millis,
    pub scope: Scope,
    pub record: JournalRecord,
}

impl JournalEntry {
    /// Whether this entry is a recorded input (replayable) rather than a
    /// derived note (regenerated by replay).
    pub fn is_input(&self) -> bool {
        matches!(self.record, JournalRecord::Input(_))
    }
}

/// What a line holds.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum JournalRecord {
    Input(InputRecord),
    Note(JournalNote),
}

/// A recorded input, verbatim.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum InputRecord {
    Action(Action),
    Event(Event),
}

impl InputRecord {
    pub fn into_input(self) -> Input {
        match self {
            Self::Action(action) => Input::Action(action),
            Self::Event(event) => Input::Event(event),
        }
    }
}

impl From<&Input> for InputRecord {
    fn from(input: &Input) -> Self {
        match input {
            Input::Action(action) => Self::Action(action.clone()),
            Input::Event(event) => Self::Event(event.clone()),
        }
    }
}

/// A derived note: something the model concluded, worth a timeline line.
///
/// These are regenerated on replay, which is exactly why replay is a real
/// test — a fold that stopped noticing a transition would stop writing the
/// note.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum JournalNote {
    DeviceCreated {
        device: DeviceId,
        from_record: bool,
    },
    DeviceForgotten {
        device: DeviceId,
    },
    DevicesMerged {
        from: DeviceId,
        into: DeviceId,
    },
    LinkRouted {
        link: LinkId,
        to: DeviceId,
    },
    LinkRerouted {
        link: LinkId,
        from: DeviceId,
        to: DeviceId,
    },
    PendingLinkOpened {
        link: LinkId,
    },
    PendingLinkDismissed {
        link: LinkId,
    },
    IdentityPromoted {
        binding: IdentityBinding,
        value: String,
    },
    IdentityConflict {
        binding: IdentityBinding,
        value: String,
    },
    /// Freshness went quiet — a TRANSITION, not a sample. Heartbeats
    /// themselves are never journaled as notes.
    WentQuiet {
        last_heard: Millis,
    },
    CameBack {
        quiet_for_ms: u64,
    },
    ActivityStarted {
        kind: ActivityKind,
    },
    ActivityCancelRequested {
        kind: ActivityKind,
    },
    /// The activity did not wind down inside its grace and was removed.
    /// Cancellation is bounded by removal, not by politeness.
    ActivityEvicted {
        kind: ActivityKind,
        reason: EvictionReason,
    },
    ActivityEnded {
        kind: ActivityKind,
        outcome: ActivityOutcome,
    },
    ActivityProgress {
        label: String,
        percent: Option<u8>,
    },
}

/// Why an activity was removed rather than allowed to finish.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EvictionReason {
    /// Cancel was requested and the grace expired.
    CancelGraceExpired,
    /// The activity's own deadline expired.
    DeadlineExpired,
    /// The link went away underneath it.
    LinkLost,
    /// The user asked to disconnect.
    UserDisconnected,
    /// The device was forgotten (or a pending link dismissed).
    DeviceForgotten,
}

/// Ring-buffered recorder.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Journal {
    entries: VecDeque<JournalEntry>,
    capacity: usize,
    next_seq: u64,
}

impl Journal {
    pub fn new(capacity: usize) -> Self {
        Self {
            entries: VecDeque::new(),
            capacity: capacity.max(1),
            next_seq: 0,
        }
    }

    pub fn record_input(&mut self, at: Millis, scope: Scope, input: &Input) {
        self.append(at, scope, JournalRecord::Input(InputRecord::from(input)));
    }

    pub fn note(&mut self, at: Millis, scope: Scope, note: JournalNote) {
        self.append(at, scope, JournalRecord::Note(note));
    }

    pub fn entries(&self) -> impl Iterator<Item = &JournalEntry> {
        self.entries.iter()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Entries for one scope, oldest first.
    pub fn entries_for(&self, scope: Scope) -> impl Iterator<Item = &JournalEntry> {
        self.entries
            .iter()
            .filter(move |entry| entry.scope == scope)
    }

    /// Just the derived notes, for reading a timeline.
    pub fn notes(&self) -> impl Iterator<Item = (&JournalEntry, &JournalNote)> {
        self.entries.iter().filter_map(|entry| match &entry.record {
            JournalRecord::Note(note) => Some((entry, note)),
            JournalRecord::Input(_) => None,
        })
    }

    /// The recorded inputs, in order, ready to be fed to a fresh roster.
    /// Derived notes are dropped: replay regenerates them.
    pub fn replay_inputs(&self) -> Vec<(Millis, Input)> {
        self.entries
            .iter()
            .filter_map(|entry| match &entry.record {
                JournalRecord::Input(record) => Some((entry.at, record.clone().into_input())),
                JournalRecord::Note(_) => None,
            })
            .collect()
    }

    /// Drop the oldest entries until at most `retain` remain.
    ///
    /// Safe because derivation never reads the journal: evidence is folded
    /// incrementally and intent is plain state. What pruning costs is
    /// forensic depth, and that is the intended trade.
    pub fn prune(&mut self, retain: usize) {
        while self.entries.len() > retain {
            self.entries.pop_front();
        }
    }

    fn append(&mut self, at: Millis, scope: Scope, record: JournalRecord) {
        self.next_seq += 1;
        self.entries.push_back(JournalEntry {
            seq: self.next_seq,
            at,
            scope,
            record,
        });
        let capacity = self.capacity;
        self.prune(capacity);
    }
}

impl Default for Journal {
    fn default() -> Self {
        Self::new(512)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::Action;

    #[test]
    fn both_streams_land_in_one_interleaved_timeline() {
        let mut journal = Journal::new(16);
        let device = DeviceId(1);

        journal.record_input(
            Millis(3_200),
            Scope::Device(device),
            &Input::Action(Action::CancelActivity { device }),
        );
        journal.note(
            Millis(3_400),
            Scope::Device(device),
            JournalNote::CameBack { quiet_for_ms: 200 },
        );
        journal.note(
            Millis(8_200),
            Scope::Device(device),
            JournalNote::ActivityEvicted {
                kind: ActivityKind::Identify,
                reason: EvictionReason::CancelGraceExpired,
            },
        );

        let seqs: Vec<u64> = journal.entries().map(|entry| entry.seq).collect();
        assert_eq!(seqs, vec![1, 2, 3]);
        assert_eq!(journal.notes().count(), 2);
        assert_eq!(journal.replay_inputs().len(), 1);
    }

    #[test]
    fn pruning_is_a_ring_and_keeps_the_newest() {
        let mut journal = Journal::new(2);
        for index in 0..5 {
            journal.note(
                Millis(index),
                Scope::Roster,
                JournalNote::PendingLinkOpened {
                    link: LinkId(index),
                },
            );
        }

        assert_eq!(journal.len(), 2);
        let links: Vec<u64> = journal
            .notes()
            .map(|(_, note)| match note {
                JournalNote::PendingLinkOpened { link } => link.0,
                other => panic!("unexpected note {other:?}"),
            })
            .collect();
        assert_eq!(links, vec![3, 4]);
    }

    #[test]
    fn scope_filtering_separates_devices_from_the_roster() {
        let mut journal = Journal::new(16);
        journal.note(
            Millis(0),
            Scope::Roster,
            JournalNote::PendingLinkOpened { link: LinkId(1) },
        );
        journal.note(
            Millis(1),
            Scope::Device(DeviceId(4)),
            JournalNote::ActivityStarted {
                kind: ActivityKind::Identify,
            },
        );

        assert_eq!(journal.entries_for(Scope::Roster).count(), 1);
        assert_eq!(journal.entries_for(Scope::Device(DeviceId(4))).count(), 1);
        assert_eq!(journal.entries_for(Scope::Device(DeviceId(9))).count(), 0);
    }
}
